import Link from "next/link";
import { useState } from "react";
import TournamentBannerImage from "@/components/tournaments/TournamentBannerImage";
import EmptyState from "@/components/ui/empty-state";
import { Section } from "@/components/ui/section";
import { buttonClassName } from "@/components/ui/button";
import { getTournamentRegistrationLabel } from "@/lib/tournaments";
import type { EventSeries, Tournament } from "@/lib/tournaments";
import { formatTournamentDate } from "@/lib/utils";

export default function EventTournamentList({ event }: { event: EventSeries }) {
  const [filter, setFilter] = useState("all");
  const categories = Array.from(new Map(event.tournaments.map((item) => [item.gameCategory?.slug || item.game, { key: item.gameCategory?.slug || item.game, label: item.gameCategory?.displayName || item.game }])).values());
  const tournaments = event.tournaments.filter((item) => filter === "all" || (item.gameCategory?.slug || item.game) === filter);
  return <Section className="pb-16" containerClassName="scroll-mt-8" ><div id="tournaments"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.3em] text-purple-200">Choose your game</p><h2 className="mt-3 font-display text-4xl text-white">Tournament titles</h2></div><span className="hidden text-sm text-slate-500 sm:block">{tournaments.length} {tournaments.length === 1 ? "game" : "games"}</span></div>
    <div className="mb-7 flex flex-wrap gap-2" role="group" aria-label="Filter event games">{[{ key: "all", label: "All Games" }, ...categories].map((item) => <button key={item.key} type="button" aria-pressed={filter === item.key} onClick={() => setFilter(item.key)} className={`rounded-full border px-4 py-2 text-sm transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-purple-300 ${filter === item.key ? "border-purple-300 bg-purple-300/15 text-white" : "border-white/10 text-slate-300 hover:border-purple-300/50"}`}>{item.label}</button>)}</div>
    {tournaments.length === 0 ? <EmptyState title="Games are being announced" description="Check back soon for the tournament line-up." /> : <>
      <div className="hidden overflow-hidden border border-white/10 bg-[#0d0c13] md:block"><div className="grid grid-cols-[minmax(0,1.5fr)_150px_170px_160px_130px] border-b border-white/10 bg-white/[0.03] px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500"><span>Game</span><span>Prize pool</span><span>Starts</span><span>Status</span><span /></div>{tournaments.map((tournament) => <DesktopRow key={tournament.id} tournament={tournament} />)}</div>
      <div className="grid gap-4 md:hidden">{tournaments.map((tournament) => <MobileCard key={tournament.id} tournament={tournament} />)}</div>
    </>}
  </div></Section>;
}

function DesktopRow({ tournament }: { tournament: Tournament }) { const open = tournament.isRegistrationOpen; const waitlist = tournament.registrationState === "waitlist_open"; return <div className="grid min-h-28 grid-cols-[minmax(0,1.5fr)_150px_170px_160px_130px] items-center gap-4 border-b border-white/8 px-5 py-4 last:border-0"><Link href={`/tournaments/${tournament.slug}`} className="flex min-w-0 items-center gap-4 rounded-xl motion-reduce:transition-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-purple-300"><TournamentBannerImage bannerUrl={tournament.bannerUrl} title={tournament.title} showFallbackTitle={false} className="h-16 w-24 shrink-0 object-cover" /><span className="min-w-0"><span className="block truncate text-xs uppercase tracking-[0.16em] text-purple-200">{tournament.game}</span><strong className="mt-1 block truncate text-lg text-white">{tournament.title}</strong></span></Link><span className="text-sm font-semibold text-white">{tournament.prizePool || "TBA"}</span><span className="text-sm text-slate-300">{formatTournamentDate(tournament.startDate, tournament.startDateStatus)}</span><span className={open || waitlist ? "text-sm font-semibold text-emerald-300" : "text-sm font-semibold text-slate-400"}>{getTournamentRegistrationLabel(tournament)}</span><Link href={open || waitlist ? `/tournaments/${tournament.slug}/register` : `/tournaments/${tournament.slug}`} className={buttonClassName({ size: "sm", className: "w-full motion-reduce:transition-none" })}>{waitlist ? "Waitlist" : open ? "Register" : "View"}</Link></div>; }

function MobileCard({ tournament }: { tournament: Tournament }) { const open = tournament.isRegistrationOpen; const waitlist = tournament.registrationState === "waitlist_open"; const actionable = open || waitlist; return <article className="overflow-hidden border border-white/10 bg-[#0d0c13]"><Link href={`/tournaments/${tournament.slug}`} className="block motion-reduce:transition-none focus-visible:outline focus-visible:outline-2 focus-visible:outline-purple-300"><TournamentBannerImage bannerUrl={tournament.bannerUrl} title={tournament.title} className="h-44 w-full object-cover" /><div className="p-5"><p className="text-xs uppercase tracking-[0.18em] text-purple-200">{tournament.game}</p><h3 className="mt-2 text-2xl text-white">{tournament.title}</h3><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Prize pool</dt><dd className="mt-1 font-semibold text-white">{tournament.prizePool || "TBA"}</dd></div><div><dt className="text-slate-500">Starts</dt><dd className="mt-1 font-semibold text-white">{formatTournamentDate(tournament.startDate, tournament.startDateStatus)}</dd></div></dl><p className={`mt-5 text-sm font-semibold ${actionable ? "text-emerald-300" : "text-slate-400"}`}>{getTournamentRegistrationLabel(tournament)}</p></div></Link><div className="px-5 pb-5"><Link href={actionable ? `/tournaments/${tournament.slug}/register` : `/tournaments/${tournament.slug}`} className={buttonClassName({ className: "w-full motion-reduce:transition-none" })}>{waitlist ? getTournamentRegistrationLabel(tournament) : open ? "Register for this game" : "View game details"}</Link></div></article>; }
