import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import AdminSupportManager from "../../components/admin/AdminSupportManager";
import AdminSupportThread from "../../components/admin/support/AdminSupportThread";
import type { SupportConversation } from "../../lib/support";

const mocks = vi.hoisted(() => ({ list: vi.fn(), get: vi.fn(), read: vi.fn(), assign: vi.fn(), send: vi.fn(), status: vi.fn(), remove: vi.fn(), archive: vi.fn(), auth: { user: { id: "staff-1" }, isLoading: false } }));
const navigation = vi.hoisted(() => ({ conversationId: null as string | null }));
vi.mock("@/lib/support", () => ({ listAdminSupportConversations: mocks.list, getAdminSupportConversation: mocks.get, markAdminSupportConversationRead: mocks.read, assignSupportConversation: mocks.assign, sendAdminSupportMessage: mocks.send, updateAdminSupportStatus: mocks.status, deleteAdminSupportConversation: mocks.remove, archiveAdminSupportConversation: mocks.archive }));
vi.mock("@/components/auth/AuthProvider", () => ({ useAuth: () => mocks.auth }));
vi.mock("@/components/admin/AdminShell", () => ({ default: ({ children }: React.PropsWithChildren) => <div>{children}</div> }));
vi.mock("next/navigation", () => ({ useSearchParams: () => new URLSearchParams(navigation.conversationId ? `conversationId=${navigation.conversationId}` : "") }));

const conversation = (status: SupportConversation["status"] = "PENDING_STAFF"): SupportConversation => ({ id: "c-1", ownerUserId: "player-1", subject: "Registration help", status, assignedStaffUserId: null, createdAt: "2026-08-19T11:00:00.000Z", updatedAt: "2026-08-19T12:00:00.000Z", resolvedAt: null, owner: { id: "player-1", username: "player", firstName: "Player", lastName: "One", avatarUrl: null }, assignedStaff: null, unreadCount: 1, messages: [{ id: "m-1", conversationId: "c-1", senderUserId: "player-1", body: "Please help", createdAt: "2026-08-19T12:00:00.000Z", sender: null }] });
const summary = { ...conversation(), lastMessage: conversation().messages[0], preview: "Please help" };

beforeEach(() => { vi.clearAllMocks(); navigation.conversationId = null; mocks.list.mockResolvedValue({ items: [summary], nextCursor: null }); mocks.get.mockResolvedValue(conversation()); mocks.read.mockResolvedValue({ lastReadAt: "now", unreadCount: 0 }); mocks.assign.mockResolvedValue(conversation()); mocks.send.mockResolvedValue({ message: { ...conversation().messages[0], id: "m-2", senderUserId: "staff-1", body: "We can help" }, status: "PENDING_USER" }); mocks.status.mockResolvedValue(conversation("RESOLVED")); });
afterEach(() => cleanup());

describe("admin support queue", () => {
  it("filters the queue and opens a thread", async () => { const user = userEvent.setup(); render(<AdminSupportManager />); await screen.findByText("Registration help"); await user.selectOptions(screen.getByLabelText("Filter by status"), "RESOLVED"); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ assigned: "all", status: "RESOLVED" })); await user.click(screen.getByRole("button", { name: /Registration help/ })); expect(await screen.findByText("Private support thread")).toBeInTheDocument(); });
  it("opens a conversation selected by the notification query", async () => { navigation.conversationId = "c-1"; render(<AdminSupportManager />); expect(await screen.findByRole("heading", { level: 2, name: "Registration help" })).toBeInTheDocument(); expect(mocks.get).toHaveBeenCalledWith("c-1"); });
  it("covers assigned views and search filters", async () => { const user = userEvent.setup(); render(<AdminSupportManager />); await screen.findByText("Registration help"); await user.click(screen.getByRole("tab", { name: "Mine" })); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ assigned: "mine" })); await user.click(screen.getByRole("tab", { name: "Unassigned" })); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ assigned: "unassigned" })); await user.type(screen.getByLabelText("Search conversations"), "login"); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ assigned: "unassigned", search: "login" })); await user.click(screen.getByRole("tab", { name: "Archived" })); await waitFor(() => expect(mocks.list).toHaveBeenLastCalledWith({ assigned: "all", archived: true, search: "login" })); expect(screen.getByRole("tab", { name: "Archived" })).toHaveAttribute("aria-selected", "true"); });
  it("assigns, unassigns, replies, and resolves", async () => { const user = userEvent.setup(); render(<AdminSupportManager />); await user.click(await screen.findByRole("button", { name: /Registration help/ })); await user.selectOptions(await screen.findByLabelText("Conversation owner"), "staff-1"); await waitFor(() => expect(mocks.assign).toHaveBeenCalledWith("c-1", "staff-1")); await user.selectOptions(screen.getByLabelText("Conversation owner"), ""); await waitFor(() => expect(mocks.assign).toHaveBeenCalledWith("c-1", null)); await user.type(screen.getByLabelText(/Reply to/), "We can help"); await user.click(screen.getByRole("button", { name: "Send reply" })); await waitFor(() => expect(mocks.send).toHaveBeenCalledWith("c-1", "We can help")); await user.selectOptions(screen.getByLabelText("Conversation status"), "RESOLVED"); await waitFor(() => expect(mocks.status).toHaveBeenCalledWith("c-1", "RESOLVED")); });
  it("reopens a resolved thread", async () => { const user = userEvent.setup(); render(<AdminSupportThread conversation={conversation("RESOLVED")} currentUserId="staff-1" onChanged={vi.fn()} onAssign={vi.fn().mockResolvedValue(undefined)} onDeleted={vi.fn()} />); await user.selectOptions(screen.getByLabelText("Conversation status"), "OPEN"); await waitFor(() => expect(mocks.status).toHaveBeenCalledWith("c-1", "OPEN")); });
  it("sends and resolves in one step, and sends with Ctrl+Enter", async () => { const user = userEvent.setup(); render(<AdminSupportThread conversation={conversation()} currentUserId="staff-1" onChanged={vi.fn()} onAssign={vi.fn().mockResolvedValue(undefined)} onDeleted={vi.fn()} />); await user.type(screen.getByLabelText(/Reply to/), "Fixed now"); await user.click(screen.getByRole("button", { name: "Send & resolve" })); await waitFor(() => expect(mocks.status).toHaveBeenCalledWith("c-1", "RESOLVED")); expect(mocks.send).toHaveBeenCalledWith("c-1", "Fixed now"); await user.type(screen.getByLabelText(/Reply to/), "Quick one"); await user.keyboard("{Control>}{Enter}{/Control}"); await waitFor(() => expect(mocks.send).toHaveBeenCalledWith("c-1", "Quick one")); });
  it("archives from the actions menu and can move it back", async () => { const user = userEvent.setup(); const onChanged = vi.fn(); mocks.archive.mockResolvedValueOnce({ ...conversation(), archivedAt: "2026-10-10T00:00:00.000Z" }).mockResolvedValueOnce(conversation()); render(<AdminSupportThread conversation={conversation()} currentUserId="staff-1" onChanged={onChanged} onAssign={vi.fn().mockResolvedValue(undefined)} onDeleted={vi.fn()} />); await user.click(screen.getByRole("button", { name: "More actions" })); await user.click(screen.getByRole("menuitem", { name: "Archive" })); await waitFor(() => expect(mocks.archive).toHaveBeenCalledWith("c-1", true)); expect(await screen.findByText(/Hidden from the inbox/)).toBeInTheDocument(); expect(onChanged).toHaveBeenCalledWith("c-1"); await user.click(screen.getAllByRole("button", { name: "Move to inbox" })[0]); await waitFor(() => expect(mocks.archive).toHaveBeenCalledWith("c-1", false)); });
  it("deletes a thread only after confirmation and clears it from the queue", async () => { const user = userEvent.setup(); mocks.remove.mockResolvedValue({ id: "c-1" }); render(<AdminSupportManager />); await user.click(await screen.findByRole("button", { name: /Registration help/ })); await screen.findByText("Private support thread"); await user.click(screen.getByRole("button", { name: "More actions" })); await user.click(screen.getByRole("menuitem", { name: /Delete permanently/ })); const dialog = screen.getByRole("alertdialog"); expect(dialog).toHaveTextContent("cannot be undone"); expect(screen.getByRole("button", { name: "Cancel" })).toHaveFocus(); await user.keyboard("{Escape}"); expect(screen.queryByRole("alertdialog")).not.toBeInTheDocument(); expect(mocks.remove).not.toHaveBeenCalled(); mocks.list.mockResolvedValue({ items: [], nextCursor: null }); await user.click(screen.getByRole("button", { name: "More actions" })); await user.click(screen.getByRole("menuitem", { name: /Delete permanently/ })); await user.click(screen.getByRole("button", { name: "Delete permanently" })); await waitFor(() => expect(mocks.remove).toHaveBeenCalledWith("c-1")); expect(await screen.findByText("Queue is clear")).toBeInTheDocument(); expect(screen.queryByText("Private support thread")).not.toBeInTheDocument(); });
  it("shows retry and authorization errors", async () => { mocks.list.mockRejectedValueOnce(new Error("Staff authorization is required.")); render(<AdminSupportManager />); expect(await screen.findByRole("alert")).toHaveTextContent("Staff authorization is required."); expect(screen.getByRole("button", { name: "Try again" })).toBeInTheDocument(); });
  it("shows a useful empty state", async () => { mocks.list.mockResolvedValue({ items: [], nextCursor: null }); render(<AdminSupportManager />); expect(await screen.findByText("Queue is clear")).toBeInTheDocument(); });
  it("keeps loading visible while the queue request is pending", () => { mocks.list.mockReturnValue(new Promise(() => undefined)); render(<AdminSupportManager />); expect(screen.getByRole("status", { name: "Loading support queue" })).toBeInTheDocument(); });
  it("retries the selected thread after a detail failure", async () => { const user = userEvent.setup(); mocks.get.mockRejectedValueOnce(new Error("Thread unavailable")).mockResolvedValueOnce(conversation()); render(<AdminSupportManager />); await user.click(await screen.findByRole("button", { name: /Registration help/ })); expect(await screen.findByRole("alert")).toHaveTextContent("Thread unavailable"); await user.click(screen.getByRole("button", { name: "Try again" })); await waitFor(() => expect(mocks.get).toHaveBeenCalledTimes(2)); expect(await screen.findByText("Private support thread")).toBeInTheDocument(); });
  it("keeps the thread read error visible", async () => { const user = userEvent.setup(); mocks.read.mockRejectedValueOnce(new Error("Read status unavailable")); render(<AdminSupportManager />); await user.click(await screen.findByRole("button", { name: /Registration help/ })); expect(await screen.findByRole("alert")).toHaveTextContent("Read status unavailable"); });
  it("shows the thread before a pending read request completes", async () => { const user = userEvent.setup(); mocks.read.mockReturnValue(new Promise(() => undefined)); render(<AdminSupportManager />); await user.click(await screen.findByRole("button", { name: /Registration help/ })); expect(await screen.findByRole("heading", { level: 2, name: "Registration help" })).toBeInTheDocument(); expect(screen.queryByRole("status", { name: "Loading support conversation" })).not.toBeInTheDocument(); expect(mocks.read).toHaveBeenCalledWith("c-1"); });
  it("preserves a failed reply for retry", async () => { const user = userEvent.setup(); mocks.send.mockRejectedValueOnce(new Error("Reply failed")).mockResolvedValueOnce({ message: { ...conversation().messages[0], id: "m-2", senderUserId: "staff-1" }, status: "PENDING_USER" }); render(<AdminSupportManager />); await user.click(await screen.findByRole("button", { name: /Registration help/ })); const reply = await screen.findByLabelText(/Reply to/); await user.type(reply, "Try again"); await user.click(screen.getByRole("button", { name: "Send reply" })); expect(await screen.findByRole("alert")).toHaveTextContent("Reply failed"); await user.click(screen.getByRole("button", { name: "Send reply" })); await waitFor(() => expect(mocks.send).toHaveBeenCalledTimes(2)); });
  it("ignores an older queue response after filters change", async () => { let resolveFirst!: (value: { items: typeof summary[]; nextCursor: null }) => void; let resolveSecond!: (value: { items: typeof summary[]; nextCursor: null }) => void; mocks.list.mockImplementationOnce(() => new Promise((resolve) => { resolveFirst = resolve; })).mockImplementationOnce(() => new Promise((resolve) => { resolveSecond = resolve; })); render(<AdminSupportManager />); fireEvent.change(screen.getByLabelText("Search conversations"), { target: { value: "new" } }); await waitFor(() => expect(mocks.list).toHaveBeenCalledTimes(2)); resolveSecond({ items: [{ ...summary, subject: "New result" }], nextCursor: null }); await waitFor(() => expect(screen.getByText("New result")).toBeInTheDocument()); resolveFirst({ items: [{ ...summary, subject: "Old result" }], nextCursor: null }); await waitFor(() => expect(screen.queryByText("Old result")).not.toBeInTheDocument()); });
  it("keeps the newest selected thread when detail responses finish out of order", async () => { let resolveFirst!: (value: SupportConversation) => void; let resolveSecond!: (value: SupportConversation) => void; const secondSummary = { ...summary, id: "c-2", subject: "Second thread" }; mocks.list.mockResolvedValue({ items: [summary, secondSummary], nextCursor: null }); mocks.get.mockImplementationOnce(() => new Promise((resolve) => { resolveFirst = resolve; })).mockImplementationOnce(() => new Promise((resolve) => { resolveSecond = resolve; })); const user = userEvent.setup(); render(<AdminSupportManager />); await screen.findByText("Second thread"); const buttons = screen.getAllByRole("button", { name: /thread|Registration help/i }); await user.click(buttons[0]); await user.click(buttons[1]); resolveSecond({ ...conversation(), id: "c-2", subject: "Second thread" }); await waitFor(() => expect(screen.getByRole("heading", { level: 2, name: "Second thread" })).toBeInTheDocument()); resolveFirst(conversation()); await waitFor(() => expect(screen.getByRole("heading", { level: 2, name: "Second thread" })).toBeInTheDocument()); });
  it("does not refresh conversation A after its mutation completes while B is selected", async () => { let resolveAssignment!: (value: SupportConversation) => void; const secondSummary = { ...summary, id: "c-2", subject: "Second thread" }; mocks.list.mockResolvedValue({ items: [summary, secondSummary], nextCursor: null }); mocks.get.mockImplementation((id: string) => Promise.resolve(id === "c-2" ? { ...conversation(), id: "c-2", subject: "Second thread" } : conversation())); mocks.assign.mockReturnValue(new Promise((resolve) => { resolveAssignment = resolve; })); const user = userEvent.setup(); render(<AdminSupportManager />); await screen.findByText("Second thread"); await user.click(screen.getByRole("button", { name: /Registration help/ })); await user.selectOptions(await screen.findByLabelText("Conversation owner"), "staff-1"); await user.click(screen.getByRole("button", { name: /Second thread/ })); expect(await screen.findByRole("heading", { level: 2, name: "Second thread" })).toBeInTheDocument(); resolveAssignment({ ...conversation(), assignedStaffUserId: "staff-1" }); await new Promise((resolve) => setTimeout(resolve, 0)); expect(screen.getByRole("heading", { level: 2, name: "Second thread" })).toBeInTheDocument(); });
});
