-- CreateTable
CREATE TABLE "TournamentRegistration" (
    "id" SERIAL NOT NULL,
    "tournament" TEXT NOT NULL,
    "teamName" TEXT NOT NULL,
    "teamLogoName" TEXT,
    "captainName" TEXT NOT NULL,
    "captainEmail" TEXT NOT NULL,
    "captainPhone" TEXT NOT NULL,
    "captainDiscord" TEXT NOT NULL,
    "captainRiotId" TEXT NOT NULL,
    "player2Name" TEXT NOT NULL,
    "player2Discord" TEXT NOT NULL,
    "player2RiotId" TEXT NOT NULL,
    "player3Name" TEXT NOT NULL,
    "player3Discord" TEXT NOT NULL,
    "player3RiotId" TEXT NOT NULL,
    "player4Name" TEXT NOT NULL,
    "player4Discord" TEXT NOT NULL,
    "player4RiotId" TEXT NOT NULL,
    "player5Name" TEXT NOT NULL,
    "player5Discord" TEXT NOT NULL,
    "player5RiotId" TEXT NOT NULL,
    "sub1Name" TEXT,
    "sub1Discord" TEXT,
    "sub1RiotId" TEXT,
    "sub2Name" TEXT,
    "sub2Discord" TEXT,
    "sub2RiotId" TEXT,
    "coachName" TEXT,
    "coachDiscord" TEXT,
    "coachRiotId" TEXT,
    "contactEmail" TEXT NOT NULL,
    "rulebook" BOOLEAN NOT NULL DEFAULT false,
    "falsityWarning" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TournamentRegistration_pkey" PRIMARY KEY ("id")
);
