"""Characterization tests pinning exact numerical parity with the legacy ELO module.

`app/legacy/elo_calculator.py` is a byte-for-byte copy of the sibling repo's
`valorant-lk-elo/elo_calculator.py` (255 lines, verified with
`git diff --no-index`). The legacy README is known to disagree with the code,
so the *code* is the source of truth.

Golden values below were generated by EXECUTING the copied module with the
project-local interpreter (Python 3.14.6, project `.venv`) — see the Task 10
report for the generator output. Each test recomputes the value through the
module and pins it with `pytest.approx(abs=1e-9)`; one test
(`test_full_precision_float_parity`) additionally asserts full float precision.

Anything relying on legacy *persistence* behavior (the `round(..., 0)`
semantics of `services.py`) is pinned separately in
`test_persisted_round_zero_order_rounds_the_difference`.
"""

import pytest

from app.legacy.elo_calculator import EloCalculator

E = EloCalculator


def assert_almost_equal(actual, desired, decimal=None):
    """Full-precision float comparison (decimal=None == exact `==`)."""
    if decimal is None:
        assert actual == desired, f"{actual!r} != {desired!r}"
    else:
        assert round(actual, decimal) == round(desired, decimal), (
            f"{actual!r} != {desired!r}"
        )


# --- K-factor boundaries (matches < 10 -> 40, < 30 -> 30, else 20) ----------


@pytest.mark.parametrize(
    ("matches", "expected_k"),
    [
        (9, 40),
        (10, 30),
        (29, 30),
        (30, 20),
    ],
)
def test_k_factor_boundaries_exact(matches, expected_k):
    """Boundaries at exactly 10 and 30 matches; 30 -> 20 (not <30)."""
    assert E.get_k_factor(matches) == expected_k


def test_k_factor_zero_and_negative():
    # Legacy: matches_played < 10 (including 0/negative) -> 40
    assert E.get_k_factor(0) == 40
    assert E.get_k_factor(-5) == 40


# --- Expected score ----------------------------------------------------------


def test_expected_score_equal_ratings():
    assert E.expected_score(1000.0, 1000.0) == pytest.approx(0.5, abs=1e-9)


def test_expected_score_favored():
    # 1500 vs 1000 -> strongly favored
    assert E.expected_score(1500.0, 1000.0) == pytest.approx(0.9467597847979775, abs=1e-9)


def test_expected_score_underdog():
    assert E.expected_score(1000.0, 1500.0) == pytest.approx(0.05324021520202244, abs=1e-9)


def test_expected_score_large_disparity():
    # 1800 vs 1000
    assert E.expected_score(1800.0, 1000.0) == pytest.approx(0.9900990099009901, abs=1e-9)


def test_winner_loser_expected_scores_complement():
    # Concrete matchup used across the calculate_new_elo series tests
    expected_winner = E.expected_score(1400.0, 1500.0)
    expected_loser = E.expected_score(1500.0, 1400.0)
    assert expected_winner == pytest.approx(0.35993500019711494, abs=1e-9)
    assert expected_loser == pytest.approx(0.6400649998028851, abs=1e-9)
    # The two are complementary by construction
    assert expected_winner + expected_loser == pytest.approx(1.0, abs=1e-9)


# --- BO1 round-differential multiplier --------------------------------------


@pytest.mark.parametrize(
    ("winner_rounds", "loser_rounds", "round_diff", "expected_mult"),
    [
        (13, 13, 0, 1.0),   # interior of very-close bucket
        (13, 12, 1, 1.0),   # threshold-adjacent (below <= 2)
        (13, 11, 2, 1.0),   # boundary: <= 2 -> very close
        (13, 10, 3, 1.1),   # interior of close bucket
        (13, 9, 4, 1.1),    # boundary: <= 4 -> close
        (13, 8, 5, 1.25),   # interior of comfortable bucket
        (13, 7, 6, 1.25),   # boundary: <= 6 -> comfortable
        (13, 6, 7, 1.4),    # interior of dominant bucket
        (13, 5, 8, 1.4),    # boundary: <= 8 -> dominant
        (13, 4, 9, 1.5),    # just above 8 -> stomp
        (13, 3, 10, 1.5),   # interior of stomp bucket
    ],
)
def test_bo1_round_differential_multiplier_vectors(winner_rounds, loser_rounds, round_diff, expected_mult):
    """Every boundary AND every interior difference is pinned, so a refactor
    shifting any of the <=2/<=4/<=6/<=8 bucket edges cannot pass."""
    assert winner_rounds - loser_rounds == round_diff
    assert E.get_round_differential_multiplier(winner_rounds, loser_rounds) == pytest.approx(
        expected_mult, abs=1e-9
    )


# --- BO3 / BO5 series multipliers -------------------------------------------


@pytest.mark.parametrize(
    ("winner_maps", "loser_maps", "winner_rounds", "loser_rounds", "expected_mult"),
    [
        # Round-bonus branches: <=5 -> 0.0, <=10 -> 0.05, <=15 -> 0.1, else 0.15.
        # Boundaries exercised at 5/6, 10/11, 15/16; map_diff 2 -> 1.4, else 1.1.
        # --- 2-0 sweep (map_mult 1.4) ---
        (2, 0, 26, 21, 1.4),                    # diff 5  -> bonus 0.0
        (2, 0, 26, 20, 1.45),                   # diff 6  -> bonus 0.05 (transition 5/6)
        (2, 0, 26, 16, 1.45),                   # diff 10 -> bonus 0.05
        (2, 0, 26, 15, 1.5),                    # diff 11 -> bonus 0.1  (transition 10/11)
        (2, 0, 26, 11, 1.5),                    # diff 15 -> bonus 0.1
        (2, 0, 26, 10, 1.5499999999999998),     # diff 16 -> bonus 0.15 (transition 15/16)
        # --- 2-1 close series (map_mult 1.1) ---
        (2, 1, 26, 21, 1.1),                    # diff 5  -> bonus 0.0
        (2, 1, 26, 20, 1.1500000000000001),     # diff 6  -> bonus 0.05 (transition 5/6)
        (2, 1, 26, 16, 1.1500000000000001),     # diff 10 -> bonus 0.05
        (2, 1, 26, 15, 1.2000000000000002),     # diff 11 -> bonus 0.1  (transition 10/11)
        (2, 1, 26, 11, 1.2000000000000002),     # diff 15 -> bonus 0.1
        (2, 1, 26, 10, 1.25),                   # diff 16 -> bonus 0.15 (transition 15/16)
    ],
)
def test_bo3_series_multiplier(winner_maps, loser_maps, winner_rounds, loser_rounds, expected_mult):
    assert E.get_series_multiplier(
        winner_maps, loser_maps, winner_rounds, loser_rounds, "bo3"
    ) == pytest.approx(expected_mult, abs=1e-9)


@pytest.mark.parametrize(
    ("winner_maps", "loser_maps", "winner_rounds", "loser_rounds", "expected_mult"),
    [
        # Round-bonus branches: <=8 -> 0.0, <=15 -> 0.05, <=25 -> 0.1, else 0.15.
        # Boundaries exercised at 8/9, 15/16, 25/26; map_diff 3 -> 1.6, 2 -> 1.35, else 1.1.
        # --- 3-0 domination (map_mult 1.6) ---
        (3, 0, 39, 34, 1.6),                        # diff 5  -> bonus 0.0
        (3, 0, 39, 31, 1.6),                        # diff 8  -> bonus 0.0  (boundary)
        (3, 0, 39, 30, 1.6500000000000001),         # diff 9  -> bonus 0.05 (transition 8/9)
        (3, 0, 39, 24, 1.6500000000000001),         # diff 15 -> bonus 0.05 (boundary)
        (3, 0, 39, 23, 1.7000000000000002),         # diff 16 -> bonus 0.1  (transition 15/16)
        (3, 0, 39, 14, 1.7000000000000002),         # diff 25 -> bonus 0.1  (boundary)
        (3, 0, 39, 13, 1.75),                       # diff 26 -> bonus 0.15 (transition 25/26)
        (3, 0, 39, 9, 1.75),                        # diff 30 -> bonus 0.15
        # --- 3-1 dominant (map_mult 1.35) ---
        (3, 1, 39, 34, 1.35),                       # diff 5  -> bonus 0.0
        (3, 1, 39, 31, 1.35),                       # diff 8  -> bonus 0.0  (boundary)
        (3, 1, 39, 30, 1.4000000000000001),         # diff 9  -> bonus 0.05 (transition 8/9)
        (3, 1, 39, 24, 1.4000000000000001),         # diff 15 -> bonus 0.05 (boundary)
        (3, 1, 39, 23, 1.4500000000000002),         # diff 16 -> bonus 0.1  (transition 15/16)
        (3, 1, 39, 14, 1.4500000000000002),         # diff 25 -> bonus 0.1  (boundary)
        (3, 1, 39, 13, 1.5),                        # diff 26 -> bonus 0.15 (transition 25/26)
        # --- 3-2 close series (map_mult 1.1) ---
        (3, 2, 39, 34, 1.1),                        # diff 5  -> bonus 0.0
        (3, 2, 39, 31, 1.1),                        # diff 8  -> bonus 0.0  (boundary)
        (3, 2, 39, 30, 1.1500000000000001),         # diff 9  -> bonus 0.05 (transition 8/9)
        (3, 2, 39, 24, 1.1500000000000001),         # diff 15 -> bonus 0.05 (boundary)
        (3, 2, 39, 23, 1.2000000000000002),         # diff 16 -> bonus 0.1  (transition 15/16)
        (3, 2, 39, 14, 1.2000000000000002),         # diff 25 -> bonus 0.1  (boundary)
        (3, 2, 39, 13, 1.25),                       # diff 26 -> bonus 0.15 (transition 25/26)
        (3, 2, 39, 9, 1.25),                        # diff 30 -> bonus 0.15
    ],
)
def test_bo5_series_multiplier(winner_maps, loser_maps, winner_rounds, loser_rounds, expected_mult):
    assert E.get_series_multiplier(
        winner_maps, loser_maps, winner_rounds, loser_rounds, "bo5"
    ) == pytest.approx(expected_mult, abs=1e-9)


def test_bo1_series_multiplier_identity():
    # BO1 path: map_mult 1.0, round_bonus 0.0 regardless of inputs
    assert E.get_series_multiplier(1, 0, 13, 5, "bo1") == pytest.approx(1.0, abs=1e-9)


# --- Upset bonus -------------------------------------------------------------


def test_upset_bonus_equal_ratings_is_five():
    # LOCK (ADR-015): equal ratings -> elo_diff 0 is NOT < 0, falls into < 100 -> +5
    assert E.get_upset_bonus(1000.0, 1000.0) == 5


@pytest.mark.parametrize(
    ("elo_diff", "expected_bonus"),
    [
        (-1, 0),   # favorite won
        (0, 5),    # equal ratings -> +5 (legacy lock)
        (99, 5),   # just below 100
        (100, 10), # exactly at 100 -> medium upset
        (199, 10), # just below 200
        (200, 15), # exactly at 200 -> big upset
        (299, 15), # just below 300
        (300, 20), # exactly at 300 -> huge upset
    ],
)
def test_upset_bonus_thresholds(elo_diff, expected_bonus):
    # loser_elo - winner_elo == elo_diff with winner fixed at 1000
    assert E.get_upset_bonus(1000.0, 1000.0 + elo_diff) == expected_bonus


# --- calculate_new_elo: BO1 scenarios ----------------------------------------


def test_calculate_new_elo_equal_ratings_bo1():
    # K=40 both, E=0.5 both. winner_rounds=13, loser_rounds=0 -> round_diff 13,
    # which is in the stomp bucket (>8) -> performance_mult 1.5.
    # winner: 40 * (1 - 0.5) * 1.5 + upset 5 = 35
    # loser:  40 * (0 - 0.5) * 1.5 = -30
    new_w, new_l = E.calculate_new_elo(1000.0, 1000.0, 5, 5)
    assert new_w == pytest.approx(1035.0, abs=1e-9)
    assert new_l == pytest.approx(970.0, abs=1e-9)
    # The +5 upset bonus is present for the winner
    assert new_w - (1000.0 + 40 * (1 - E.expected_score(1000.0, 1000.0)) * 1.5) == pytest.approx(5.0, abs=1e-9)


def test_calculate_new_elo_bo1_favored_wins():
    # 1500 (10 matches, K=30) beats 1000 (5 matches, K=40), 13-0
    new_w, new_l = E.calculate_new_elo(1500.0, 1000.0, 10, 5)
    assert new_w == pytest.approx(1502.395809684091, abs=1e-9)
    assert new_l == pytest.approx(996.8055870878786, abs=1e-9)


def test_calculate_new_elo_bo1_upset():
    # 1000 (5 matches) upsets 1500 (10 matches), 13-0 -> underdog gets upset bonus
    new_w, new_l = E.calculate_new_elo(1000.0, 1500.0, 5, 10)
    assert new_w == pytest.approx(1076.8055870878786, abs=1e-9)
    assert new_l == pytest.approx(1457.395809684091, abs=1e-9)


def test_calculate_new_elo_large_disparity():
    # 1800 vs 1000, both 40 matches (K=20), 13-0 stomp (perf 1.5)
    new_w, new_l = E.calculate_new_elo(1800.0, 1000.0, 40, 40)
    assert new_w == pytest.approx(1800.2970297029703, abs=1e-9)
    assert new_l == pytest.approx(999.7029702970297, abs=1e-9)


def test_calculate_new_elo_bo1_stomp():
    # 13-4 round diff 9 -> perf 1.5, both K=30
    new_w, new_l = E.calculate_new_elo(1400.0, 1200.0, 20, 20, 13, 4)
    assert new_w == pytest.approx(1410.8113883008418, abs=1e-9)
    assert new_l == pytest.approx(1189.1886116991582, abs=1e-9)


def test_winner_loser_asymmetric_k():
    """Winner and loser use their OWN K factors (winner 10 matches K=30, loser
    5 matches K=40)."""
    k_w = E.get_k_factor(10)
    k_l = E.get_k_factor(5)
    assert (k_w, k_l) == (30, 40)
    e_w = E.expected_score(1500.0, 1000.0)
    e_l = E.expected_score(1000.0, 1500.0)
    perf = E.get_round_differential_multiplier(13, 0)
    assert perf == pytest.approx(1.5, abs=1e-9)
    expected_new_w = 1500.0 + k_w * (1 - e_w) * perf
    expected_new_l = 1000.0 + k_l * (0 - e_l) * perf
    new_w, new_l = E.calculate_new_elo(1500.0, 1000.0, 10, 5)
    assert new_w == pytest.approx(expected_new_w, abs=1e-9)
    assert new_l == pytest.approx(expected_new_l, abs=1e-9)


# --- calculate_new_elo: BO3 / BO5 series -------------------------------------


@pytest.mark.parametrize(
    ("winner_rounds", "loser_rounds", "winner_maps", "loser_maps", "expected"),
    [
        # 1500 (K=30) vs 1400 (K=30), 26-18 2-0 sweep: perf 1.45
        (26, 18, 2, 0, (1515.6571725085746, 1384.3428274914254)),
        # 26-22 2-1 close: perf 1.1
        (26, 22, 2, 1, (1511.877855006505, 1388.122144993495)),
    ],
)
def test_calculate_new_elo_bo3(winner_rounds, loser_rounds, winner_maps, loser_maps, expected):
    new_w, new_l = E.calculate_new_elo(
        1500.0, 1400.0, 10, 20,
        winner_rounds, loser_rounds, "regular", "bo3", winner_maps, loser_maps,
    )
    assert new_w == pytest.approx(expected[0], abs=1e-9)
    assert new_l == pytest.approx(expected[1], abs=1e-9)


@pytest.mark.parametrize(
    ("winner_rounds", "loser_rounds", "winner_maps", "loser_maps", "expected"),
    [
        # 39-24 3-0 domination: perf 1.65
        (39, 24, 3, 0, (1517.816782509757, 1382.183217490243)),
        # 39-29 3-1 dominant: perf 1.4
        (39, 29, 3, 1, (1515.1172700082789, 1384.8827299917211)),
        # 39-34 3-2 close: perf 1.1
        (39, 34, 3, 2, (1511.877855006505, 1388.122144993495)),
    ],
)
def test_calculate_new_elo_bo5(winner_rounds, loser_rounds, winner_maps, loser_maps, expected):
    new_w, new_l = E.calculate_new_elo(
        1500.0, 1400.0, 10, 20,
        winner_rounds, loser_rounds, "regular", "bo5", winner_maps, loser_maps,
    )
    assert new_w == pytest.approx(expected[0], abs=1e-9)
    assert new_l == pytest.approx(expected[1], abs=1e-9)


def test_calculate_new_elo_bo3_round_bonus_010():
    """BO3 2-1 with aggregate diff 11 -> round bonus 0.1 (perf 1.1 + 0.1 = 1.2)."""
    new_w, new_l = E.calculate_new_elo(
        1500.0, 1400.0, 10, 20, 26, 15, "regular", "bo3", 2, 1
    )
    assert new_w == pytest.approx(1512.9576600070961, abs=1e-9)
    assert new_l == pytest.approx(1387.0423399929039, abs=1e-9)


def test_calculate_new_elo_bo5_round_bonus_010():
    """BO5 3-1 with aggregate diff 25 -> round bonus 0.1 (perf 1.35 + 0.1 = 1.45)."""
    new_w, new_l = E.calculate_new_elo(
        1500.0, 1400.0, 10, 20, 39, 14, "regular", "bo5", 3, 1
    )
    assert new_w == pytest.approx(1515.6571725085746, abs=1e-9)
    assert new_l == pytest.approx(1384.3428274914254, abs=1e-9)


def test_calculate_new_elo_bo5_round_bonus_015():
    """BO5 3-0 with aggregate diff 30 -> round bonus 0.15 (perf 1.6 + 0.15 = 1.75)."""
    new_w, new_l = E.calculate_new_elo(
        1500.0, 1400.0, 10, 20, 39, 9, "regular", "bo5", 3, 0
    )
    assert new_w == pytest.approx(1518.8965875103486, abs=1e-9)
    assert new_l == pytest.approx(1381.1034124896514, abs=1e-9)


# --- Match importance (applied to K) -----------------------------------------


@pytest.mark.parametrize(
    ("importance", "expected_new"),
    [
        # K 40 -> regular 1.0 (K=40), playoff 1.3 (K=52), finals 1.5 (K=60)
        # equal ratings, 13-0 (perf 1.5): winner = K*0.5*1.5 + 5, loser = -K*0.5*1.5
        ("regular", (1035.0, 970.0)),
        ("playoff", (1044.0, 961.0)),
        ("finals", (1050.0, 955.0)),
    ],
)
def test_match_importance_multipliers(importance, expected_new):
    new_w, new_l = E.calculate_new_elo(
        1000.0, 1000.0, 5, 5, 13, 0, importance, "bo1"
    )
    assert new_w == pytest.approx(expected_new[0], abs=1e-9)
    assert new_l == pytest.approx(expected_new[1], abs=1e-9)


def test_unknown_importance_defaults_to_regular():
    # Legacy get() fallback: unknown importance -> 1.0 multiplier
    new_w_unknown, _ = E.calculate_new_elo(1000.0, 1000.0, 5, 5, 13, 0, "super_bowl")
    new_w_regular, _ = E.calculate_new_elo(1000.0, 1000.0, 5, 5, 13, 0, "regular")
    assert new_w_unknown == new_w_regular


def test_calculate_new_elo_playoff_bo5():
    new_w, new_l = E.calculate_new_elo(
        1500.0, 1400.0, 10, 20, 39, 34, "playoff", "bo5", 3, 2
    )
    assert new_w == pytest.approx(1515.4412115084563, abs=1e-9)
    assert new_l == pytest.approx(1384.5587884915437, abs=1e-9)


# --- Unrounded outputs --------------------------------------------------------


def test_calculate_new_elo_returns_unrounded_floats():
    """Legacy calculator returns full-precision floats; rounding happens only at
    persistence time (services.py), never inside the calculator."""
    new_w, new_l = E.calculate_new_elo(1500.0, 1000.0, 10, 5)
    assert new_w != round(new_w, 0)
    assert new_l != round(new_l, 0)
    assert isinstance(new_w, float)
    assert isinstance(new_l, float)


def test_expected_score_returns_unrounded_float():
    assert isinstance(E.expected_score(1500.0, 1000.0), float)


# --- Legacy persistence semantics (services.py round(..., 0)) -----------------


def test_persisted_round_zero_order_rounds_the_difference():
    """Mirrors legacy services.py persistence exactly — the ORDER matters:
    - competitive_elo / elo_after: round(new_elo, 0)
    - elo_before:                   round(before, 0)
    - elo_change:                   round(after - before, 0)  # difference FIRST,
                                    # then round (NOT round(after,0) - round(before,0))

    Non-integer ratings make the order observable: the winner's new rating
    1502.895809684091 rounds to 1503 but the change is 2.3958 -> 2.0, whereas
    `round(after, 0) - round(before, 0)` would yield 1503 - 1500 = 3.0.
    """
    winner_elo, loser_elo = 1500.5, 1000.5
    new_w, new_l = E.calculate_new_elo(winner_elo, loser_elo, 10, 5)

    # competitive_elo / elo_after: round(new_elo, 0)
    assert round(new_w, 0) == 1503.0
    assert round(new_l, 0) == 997.0

    # elo_before: round(before, 0)  (1500.5 -> 1500 via banker's rounding)
    assert round(winner_elo, 0) == 1500.0
    assert round(loser_elo, 0) == 1000.0

    # elo_change: round(after - before, 0) — computed from the UNROUNDED inputs
    assert round(new_w - winner_elo, 0) == 2.0
    assert round(new_l - loser_elo, 0) == -3.0

    # The legacy order genuinely differs from the naive difference-of-rounds:
    legacy_order = round(new_w - winner_elo, 0)
    naive_order = round(new_w, 0) - round(winner_elo, 0)
    assert legacy_order == 2.0
    assert naive_order == 3.0
    assert legacy_order != naive_order


# --- Full-precision pin -------------------------------------------------------


def test_full_precision_float_parity():
    """Golden values were produced by executing this exact module; recomputation
    must agree bit-for-bit (full float precision)."""
    assert_almost_equal(
        E.expected_score(1500.0, 1000.0), 0.9467597847979775, decimal=None
    )
    assert_almost_equal(
        E.calculate_new_elo(1500.0, 1000.0, 10, 5)[0], 1502.395809684091, decimal=None
    )
    assert_almost_equal(
        E.get_series_multiplier(2, 0, 26, 18, "bo3"), 1.45, decimal=None
    )
