-- Discord identity as competitive infrastructure, not as a login.
--
-- oauth_accounts already stores the snowflake, but it is an AUTHENTICATION
-- record: it exists so somebody can sign in, and it cascades away with the user
-- row. Tournament operations need the link to outlive that, and need it to
-- exist for a player with no Quest account at all — a LAN entrant a captain
-- registered on their behalf is still someone a referee has to reach.
--
-- discord_user_id is the snowflake and the only identity key. username and
-- global_name are a cached display snapshot: Discord names change, snowflakes
-- do not.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'DiscordLinkSource') THEN
    CREATE TYPE "DiscordLinkSource" AS ENUM ('oauth', 'admin');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "discord_identities" (
  -- No database default on `id`/`updated_at`: Prisma's @default(uuid()) and
  -- @updatedAt are generated by the client, so a DB-side default is drift and
  -- `prisma migrate diff` fails CI on it. The backfill supplies both.
  "id"              UUID                NOT NULL,
  "player_id"       UUID                NOT NULL,
  "discord_user_id" TEXT                NOT NULL,
  "username"        TEXT,
  "global_name"     TEXT,
  "source"          "DiscordLinkSource" NOT NULL DEFAULT 'oauth',
  "linked_at"       TIMESTAMP(3)        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_seen_at"    TIMESTAMP(3),
  "created_at"      TIMESTAMP(3)        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"      TIMESTAMP(3)        NOT NULL,
  CONSTRAINT "discord_identities_pkey" PRIMARY KEY ("id")
);

-- The abuse boundary, mirroring game_accounts: one Discord account belongs to
-- one player, and one player holds one Discord account. Without both, two
-- people could claim the same account and a tournament role could be granted to
-- the wrong person.
CREATE UNIQUE INDEX IF NOT EXISTS "discord_identities_player_id_key"
  ON "discord_identities" ("player_id");
CREATE UNIQUE INDEX IF NOT EXISTS "discord_identities_discord_user_id_key"
  ON "discord_identities" ("discord_user_id");
CREATE INDEX IF NOT EXISTS "discord_identities_discord_user_id_idx"
  ON "discord_identities" ("discord_user_id");

-- A snowflake is digits only. Storing anything else means a caller passed a
-- username, which is exactly the confusion this table exists to prevent.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'discord_identities_snowflake_check'
  ) THEN
    ALTER TABLE "discord_identities"
      ADD CONSTRAINT "discord_identities_snowflake_check"
      CHECK ("discord_user_id" ~ '^[0-9]{5,32}$');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'discord_identities_player_id_fkey'
  ) THEN
    ALTER TABLE "discord_identities"
      ADD CONSTRAINT "discord_identities_player_id_fkey"
      FOREIGN KEY ("player_id") REFERENCES "players"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END
$$;

-- Backfill from the OAuth records.
--
-- This one IS backfilled, unlike the roster snapshots. The difference is that
-- a completed Discord OAuth flow already established the fact — Discord itself
-- confirmed the account belongs to that user — so copying it asserts nothing
-- new. `source` is 'oauth' for exactly that reason.
--
-- username is seeded from the mutable users.discord_tag purely as a display
-- snapshot. It is never an identity key, and a NULL here simply means no
-- cached name yet.
INSERT INTO "discord_identities" ("id", "player_id", "discord_user_id", "username", "source", "linked_at", "updated_at")
SELECT gen_random_uuid(), p."id", o."provider_user_id", NULLIF(btrim(u."discord_tag"), ''), 'oauth', o."created_at", CURRENT_TIMESTAMP
FROM "oauth_accounts" o
JOIN "players" p ON p."user_id" = o."user_id"
JOIN "users"   u ON u."id"      = o."user_id"
WHERE o."provider" = 'discord'
  AND o."provider_user_id" ~ '^[0-9]{5,32}$'
ON CONFLICT DO NOTHING;

-- Supabase hardening, matching 20260823120000_add_players_and_game_accounts.
--
-- A Discord snowflake plus a display name is directly personally identifying
-- and links a Quest player to an account outside Quest, so this table must be
-- as unreachable from the Data API roles as players and game_accounts are.
-- Quest reaches it only through the Prisma runtime role.
ALTER TABLE public."discord_identities" ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public."discord_identities" FROM PUBLIC;

DO $migration$
DECLARE role_name TEXT;
BEGIN
  FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated', 'service_role'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
      EXECUTE format(
        'REVOKE ALL PRIVILEGES ON TABLE public."discord_identities" FROM %I',
        role_name
      );
    END IF;
  END LOOP;
END
$migration$;
