"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import type { SupportConversation } from "@/lib/support";
import { reopenSupportConversation, resolveSupportConversation, sendSupportMessage } from "@/lib/support";
import { statusLabel, statusTone } from "./SupportConversationList";
import SupportComposer from "./SupportComposer";
const format = (value: string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
export default function SupportThread({ conversation: initial, currentUserId, onChanged }: { conversation: SupportConversation; currentUserId: string; onChanged: () => void }) {
  const [conversation, setConversation] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => setConversation(initial), [initial]);
  const send = async ({ body }: { subject: string; body: string }) => { setBusy(true); setError(null); try { const result = await sendSupportMessage(conversation.id, body); setConversation((current) => ({ ...current, status: result.status, messages: [...current.messages, result.message] })); onChanged(); } catch (e) { setError(e instanceof Error ? e.message : "Message could not be sent. Try again."); } finally { setBusy(false); } };
  const changeStatus = async () => { setBusy(true); setError(null); try { const next = conversation.status === "RESOLVED" ? await reopenSupportConversation(conversation.id) : await resolveSupportConversation(conversation.id); setConversation(next); onChanged(); } catch (e) { setError(e instanceof Error ? e.message : "Status could not be updated."); } finally { setBusy(false); } };
  return <div className="flex min-h-[34rem] flex-col"><header className="border-b border-white/8 px-5 py-5 sm:px-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-slate-500">Conversation</p><h2 className="mt-2 text-2xl text-white">{conversation.subject}</h2></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone[conversation.status]}`}>{statusLabel[conversation.status]}</span><Button size="sm" variant="ghost" disabled={busy} onClick={() => void changeStatus()}>{conversation.status === "RESOLVED" ? "Reopen" : "Resolve"}</Button></div></div><p className="mt-3 text-sm text-slate-500">Support replies here, usually within one business day.</p></header><div className="flex-1 space-y-4 overflow-y-auto px-5 py-6 sm:px-7">{conversation.messages.map((message) => { const mine = message.senderUserId === currentUserId; return <div key={message.id} className={`flex ${mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[90%] rounded-2xl px-4 py-3 sm:max-w-[75%] ${mine ? "rounded-br-sm bg-cyan-300 text-slate-950" : "rounded-bl-sm border border-white/10 bg-white/[.05] text-slate-200"}`}><p className="whitespace-pre-wrap text-sm leading-6">{message.body}</p><time className={`mt-2 block text-[11px] ${mine ? "text-slate-800/70" : "text-slate-500"}`}>{mine ? "You" : message.sender?.firstName || "Quest Support"} · {format(message.createdAt)}</time></div></div>})}</div><div className="border-t border-white/8 px-5 py-5 sm:px-7"><SupportComposer compact subject={conversation.subject} busy={busy} error={error} onSubmit={send} /></div></div>;
}
