"use client";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
import { useToastStore } from "@/hooks/useToastStore";
import { listSupportConversations, createSupportConversation, getSupportConversation, markSupportConversationRead, type SupportConversation, type SupportConversationSummary } from "@/lib/support";
import { subscribeToRealtimeUpdates } from "@/lib/realtime";
import SupportConversationList from "./SupportConversationList";
import SupportComposer from "./SupportComposer";
import SupportThread from "./SupportThread";
export default function SupportInbox({ conversationId }: { conversationId?: string }) {
  const { user, isLoading: authLoading } = useAuth(); const showToast = useToastStore((s) => s.showToast); const [items, setItems] = useState<SupportConversationSummary[]>([]); const [conversation, setConversation] = useState<SupportConversation | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [creating, setCreating] = useState(false);
  const loadList = useCallback(async () => { try { const result = await listSupportConversations(); setItems(result.items); setError(null); } catch (e) { setError(e instanceof Error ? e.message : "Inbox could not be loaded."); } finally { setLoading(false); } }, []);
  const loadThread = useCallback(async () => { if (!conversationId) return; try { const result = await getSupportConversation(conversationId); setConversation(result); await markSupportConversationRead(conversationId); } catch (e) { setError(e instanceof Error ? e.message : "Conversation could not be loaded."); } }, [conversationId]);
  useEffect(() => { if (!authLoading && user) void loadList(); }, [authLoading, user, loadList]);
  useEffect(() => { if (!authLoading && user && conversationId) void loadThread(); }, [authLoading, user, conversationId, loadThread]);
  useEffect(() => { if (!user) return; const close = subscribeToRealtimeUpdates(`user:${user.id}`, () => { void loadList(); if (conversationId) void loadThread(); }); return close; }, [user, conversationId, loadList, loadThread]);
  const create = async ({ subject, body }: { subject: string; body: string }) => { setCreating(true); try { const next = await createSupportConversation(subject, body); showToast({ title: "Message sent", description: "Your support conversation is ready.", tone: "success" }); window.history.pushState({}, "", `/support/${next.id}`); setConversation(next); await loadList(); } catch (e) { throw e; } finally { setCreating(false); } };
  if (authLoading) return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-10 text-center text-sm text-slate-400">Checking your account…</div>;
  if (!user) return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-10 text-center"><h2 className="text-xl text-white">Sign in to contact support</h2><p className="mt-2 text-sm text-slate-400">Your conversations stay private and available whenever you return.</p></div>;
  if (loading && !items.length) return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-10 text-center text-sm text-slate-400">Loading your conversations…</div>;
  return <div className="grid gap-4 lg:grid-cols-[19rem_1fr]"><aside className="overflow-hidden rounded-2xl border border-white/10 bg-[#0d0c13]"><div className="border-b border-white/8 px-4 py-5"><p className="text-xs uppercase tracking-[.25em] text-slate-500">Your inbox</p><h2 className="mt-2 text-xl text-white">Support conversations</h2></div>{error && !items.length ? <div className="p-4 text-sm text-red-100"><p>{error}</p><button className="mt-3 text-cyan-200 underline" onClick={() => { setLoading(true); void loadList(); }}>Try again</button></div> : items.length ? <SupportConversationList items={items} selectedId={conversationId} /> : <div className="p-5 text-sm leading-6 text-slate-400">No conversations yet. Start a message and the Quest team will pick it up.</div>}</aside><main className="min-w-0 overflow-hidden rounded-2xl border border-white/10 bg-[#0d0c13]">{conversation ? <SupportThread conversation={conversation} currentUserId={user.id} onChanged={() => void loadList()} /> : <div className="p-5 sm:p-8"><p className="text-xs uppercase tracking-[.25em] text-cyan-200">Need a hand?</p><h2 className="mt-3 text-3xl text-white">Start a support conversation</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-400">Share the details once. Keep the thread open for updates from Quest Support.</p><div className="mt-7 max-w-2xl"><SupportComposer busy={creating} onSubmit={create} /></div></div>}</main></div>;
}
