#!/usr/bin/env bash
set -euo pipefail
umask 077
fail() { echo "Restore rehearsal evidence refused: $1" >&2; exit 1; }
[[ $# -eq 1 ]] || fail "usage: verify-rehearsal-evidence.sh /absolute/evidence-directory"
dir="$1"
[[ "$dir" == /* && "$dir" != / && -d "$dir" && ! -L "$dir" ]] || fail "evidence directory is missing or unsafe"
mode="$(stat -c '%a' -- "$dir" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "evidence directory is not private"
case "${dir,,}" in *questesports*|*supabase*|*production*|*/var/www/*|*/srv/quest-esports/*) fail "evidence directory looks like production" ;; esac
file="$dir/rehearsal-evidence.env"; [[ -f "$file" && ! -L "$file" ]] || fail "machine-readable evidence is missing"
mode="$(stat -c '%a' -- "$file" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "evidence file is not private"
declare -A e=()
while IFS= read -r line || [[ -n "$line" ]]; do
  [[ "$line" =~ ^([a-z][a-z0-9_]*)=([^[:space:]]+)$ ]] || fail "evidence has a malformed line"
  key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ -z "${e[$key]+x}" ]] || fail "evidence contains duplicate fields"; e["$key"]="$value"
  [[ "$key" == archive_name || ( "$value" != *://* && "$value" != */* && "$value" != *@* ) ]] || fail "evidence contains a URL/path"
  case "${value,,}" in *questesports*|*supabase*|*production*|*paris*|*/var/www/*|*/srv/quest-esports/*) [[ "$key" == archive_name ]] || fail "evidence looks like production" ;; esac
done < "$file"
observations="$dir/rehearsal-observations.env"; [[ -f "$observations" && ! -L "$observations" ]] || fail "raw command observations are missing"
mode="$(stat -c '%a' -- "$observations" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "raw observations are not private"
required=(format_version evidence_status rehearsal_mode restore_status created_at_utc restore_start_utc restore_end_utc restore_duration_seconds archive_name archive_sha256 observations_sha256 checksum_status decryption_status manifest_database_scope manifest_valorant_schema_included source_postgres_major target_postgres_major source_major_gate source_version_provenance source_version_record_sha256 client_psql_major client_pg_restore_major client_pg_dump_major public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_ledger_status quest_migration_count valorant_migration_ledger_status valorant_migration_count roles_status owners_status grants_status default_acl_status memberships_status security_verify_status security_verify_output_sha256 extensions_status extensions_count extensions_inventory_sha256 settings_status settings_inventory_sha256 rls_status roles_observations_sha256 memberships_observations_sha256 owners_observations_sha256 grants_observations_sha256 default_acl_observations_sha256 rls_observations_sha256 rls_enabled_table_count rls_table_count public_upload_file_count public_upload_byte_count public_upload_checksum private_upload_file_count private_upload_byte_count private_upload_checksum upload_checksum_scope upload_source_equivalence quest_liveness_status quest_readiness_status quest_database_status valorant_health_status valorant_database_status valorant_ca_status freeze_mode writers_disabled mutation_rejection no_writer_admission failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback resource_cpu_seconds resource_peak_memory_kb resource_disk_bytes rto_seconds rto_decision)
for key in "${required[@]}"; do [[ -n "${e[$key]:-}" ]] || fail "required field missing: $key"; done
for key in "${!e[@]}"; do found=false; for known in "${required[@]}"; do [[ "$key" == "$known" ]] && found=true; done; [[ "$found" == true ]] || fail "unknown evidence field: $key"; done
[[ "${e[observations_sha256]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "observation binding is malformed"
actual_observations_sha256="$(sha256sum "$observations" | cut -d' ' -f1)"; [[ "$actual_observations_sha256" == "${e[observations_sha256]}" ]] || fail "raw observations do not match summary binding"
declare -A o=()
while IFS= read -r line || [[ -n "$line" ]]; do
  [[ "$line" =~ ^([a-z][a-z0-9_]*)=([^[:space:]]+)$ ]] || fail "raw observations have a malformed line"
  key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ -z "${o[$key]+x}" ]] || fail "raw observations contain duplicate fields"; o["$key"]="$value"
  [[ "$value" != *://* && "$value" != */* && "$value" != *@* ]] || fail "raw observations contain a URL/path"
done < "$observations"
observed=(format_version observation_status restore_command_status checksum_command_status decryption_command_status source_version_provenance source_version_record_sha256 source_postgres_major target_postgres_major client_psql_major client_pg_restore_major client_pg_dump_major manifest_scope manifest_valorant_schema_included public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_ledger_status quest_migration_count valorant_migration_ledger_status valorant_migration_count roles_command_status memberships_command_status owners_command_status grants_command_status default_acl_command_status rls_command_status roles_observations_sha256 memberships_observations_sha256 owners_observations_sha256 grants_observations_sha256 default_acl_observations_sha256 rls_observations_sha256 security_verify_status security_verify_output_sha256 extensions_inventory_sha256 settings_inventory_sha256 public_upload_file_count public_upload_byte_count public_upload_checksum private_upload_file_count private_upload_byte_count private_upload_checksum upload_checksum_scope upload_source_equivalence quest_liveness_status quest_readiness_status quest_database_status valorant_health_status valorant_database_status valorant_ca_status freeze_mode writers_disabled mutation_rejection no_writer_admission failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback resource_cpu_seconds resource_peak_memory_kb resource_disk_bytes rto_seconds rto_decision)
for key in "${observed[@]}"; do [[ -n "${o[$key]:-}" ]] || fail "raw observation field missing: $key"; done
for key in "${!o[@]}"; do found=false; for known in "${observed[@]}"; do [[ "$key" == "$known" ]] && found=true; done; [[ "$found" == true ]] || fail "unknown raw observation field: $key"; done
[[ "${o[format_version]}" == 1 && "${o[observation_status]}" == complete && "${o[restore_command_status]}" == verified && "${o[checksum_command_status]}" == verified && "${o[decryption_command_status]}" == verified ]] || fail "raw command observations are incomplete"
for artifact in roles memberships owners grants acl ext settings rls; do artifact_file="$dir/rehearsal-${artifact}.tsv"; [[ -f "$artifact_file" && ! -L "$artifact_file" ]] || fail "raw command artifact is missing: $artifact"; mode="$(stat -c '%a' -- "$artifact_file" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "raw command artifact is not private: $artifact"; done
source_artifact="$dir/rehearsal-source-version.env"; [[ -f "$source_artifact" && ! -L "$source_artifact" ]] || fail "source-version evidence artifact is missing"; mode="$(stat -c '%a' -- "$source_artifact" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "source-version evidence artifact is not private"
[[ "$(sha256sum "$source_artifact" | cut -d' ' -f1)" == "${e[source_version_record_sha256]}" ]] || fail "source-version evidence binding failed"
artifact_source_major="$(grep -m1 '^source_major=' "$source_artifact" | cut -d= -f2-)"; artifact_source_version="$(grep -m1 '^source_version=' "$source_artifact" | cut -d= -f2-)"
grep -Eq '://|/|@' "$source_artifact" && fail "source-version evidence contains a URL/path"; [[ "$artifact_source_major" == "${e[source_postgres_major]}" && "$artifact_source_version" =~ ^PostgreSQL_${e[source_postgres_major]}([.][0-9]+)?$ ]] && grep -qx 'provenance=operator_recorded' "$source_artifact" || fail "source-version evidence artifact is malformed"
for pair in "roles|roles_observations_sha256" "memberships|memberships_observations_sha256" "owners|owners_observations_sha256" "grants|grants_observations_sha256" "acl|default_acl_observations_sha256" "rls|rls_observations_sha256"; do artifact="${pair%%|*}"; field="${pair#*|}"; hash="$(sha256sum "$dir/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; [[ "$hash" == "${e[$field]}" && "$hash" == "${o[$field]}" ]] || fail "raw command artifact binding failed: $artifact"; done
[[ "$(wc -l < "$dir/rehearsal-roles.tsv" | tr -d ' ')" == 4 ]] || fail "role observation does not contain four roles"
while IFS='|' read -r role login inherit super createdb createrole replication bypass; do [[ "$role" =~ ^(quest_migrator|quest_runtime|val_migrator|val_runtime)$ && "$login" == t && "$inherit" == f && "$super" == f && "$createdb" == f && "$createrole" == f && "$replication" == f && "$bypass" == f ]] || fail "raw role attributes are unsafe"; done < "$dir/rehearsal-roles.tsv"
[[ "$(tr -d '[:space:]' < "$dir/rehearsal-memberships.tsv")" == 0 ]] || fail "raw membership observation is unsafe"
grep -qx 'public|quest_migrator' "$dir/rehearsal-owners.tsv" && grep -qx 'valorant|val_migrator' "$dir/rehearsal-owners.tsv" || fail "raw schema owner observation is unsafe"
[[ "$(tr -d '[:space:]' < "$dir/rehearsal-grants.tsv")" == verified && "$(tr -d '[:space:]' < "$dir/rehearsal-acl.tsv")" == verified ]] || fail "raw grants/default ACL observations are incomplete"
grep -Eq '^[A-Za-z0-9_]+\|[^[:space:]]+$' "$dir/rehearsal-ext.tsv" || fail "raw extension inventory is malformed"
grep -Eq '^[a-z_]+\|[^[:space:]]+$' "$dir/rehearsal-settings.tsv" || fail "raw settings inventory is malformed"
grep -Eq '^server_version_num\|17[0-9]{4}$' "$dir/rehearsal-settings.tsv" || fail "raw target server setting is not PostgreSQL 17"
[[ "${o[extensions_inventory_sha256]}" == "${e[extensions_inventory_sha256]}" && "${o[settings_inventory_sha256]}" == "${e[settings_inventory_sha256]}" ]] || fail "inventory binding is inconsistent"
[[ "${e[source_version_provenance]}" == operator_recorded && "${o[source_version_provenance]}" == operator_recorded && "${e[source_version_record_sha256]}" == "${o[source_version_record_sha256]}" && "${e[source_version_record_sha256]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "source provenance is not explicitly operator-recorded"
[[ "${e[format_version]}" == 1 && "${e[evidence_status]}" == complete && "${e[rehearsal_mode]}" == disposable && "${e[restore_status]}" == verified ]] || fail "evidence is not complete disposable runtime evidence"
[[ "${e[manifest_database_scope]}" == application_public_and_valorant_schemas && "${e[manifest_valorant_schema_included]}" == true ]] || fail "manifest scope is incomplete"
[[ "${e[checksum_status]}" == verified && "${e[decryption_status]}" == verified && "${e[archive_sha256]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "archive integrity evidence is incomplete"
[[ "${e[archive_name]}" =~ ^quest-production-[0-9]{8}T[0-9]{6}Z\.tar\.gz\.enc$ ]] || fail "archive name is not an expected production archive basename"
[[ "${e[source_postgres_major]}" =~ ^[0-9]+$ && "${e[source_postgres_major]}" -gt 0 ]] || fail "source major is invalid"
[[ "${e[target_postgres_major]}" == "${o[target_postgres_major]}" && "${e[source_postgres_major]}" == "${o[source_postgres_major]}" && "${e[client_psql_major]}" == "${o[client_psql_major]}" && "${e[client_pg_restore_major]}" == "${o[client_pg_restore_major]}" && "${e[client_pg_dump_major]}" == "${o[client_pg_dump_major]}" ]] || fail "summary versions do not match raw observations"
[[ "${e[manifest_database_scope]}" == "${o[manifest_scope]}" && "${e[manifest_valorant_schema_included]}" == "${o[manifest_valorant_schema_included]}" ]] || fail "summary manifest does not match raw observation"
for key in public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_count valorant_migration_count public_upload_file_count public_upload_byte_count public_upload_checksum private_upload_file_count private_upload_byte_count private_upload_checksum quest_liveness_status quest_readiness_status quest_database_status valorant_health_status valorant_database_status valorant_ca_status freeze_mode writers_disabled mutation_rejection no_writer_admission failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback resource_cpu_seconds resource_peak_memory_kb resource_disk_bytes rto_seconds rto_decision upload_checksum_scope upload_source_equivalence; do [[ "${e[$key]}" == "${o[$key]}" ]] || fail "summary does not match raw observation: $key"; done
for pair in "roles_status|roles_command_status" "memberships_status|memberships_command_status" "owners_status|owners_command_status" "grants_status|grants_command_status" "default_acl_status|default_acl_command_status" "rls_status|rls_command_status" "security_verify_status|security_verify_status" "extensions_inventory_sha256|extensions_inventory_sha256" "settings_inventory_sha256|settings_inventory_sha256" "security_verify_output_sha256|security_verify_output_sha256"; do left="${pair%%|*}"; right="${pair#*|}"; [[ "${e[$left]}" == "${o[$right]}" ]] || fail "summary status does not match raw observation: $left"; done
if [[ "${e[source_postgres_major]}" == 17 ]]; then [[ "${e[source_major_gate]}" == none ]] || fail "unexpected major-migration gate"; else [[ "${e[source_major_gate]}" == approved_logical_major_migration ]] || fail "source-major migration gate is missing"; fi
for key in client_psql_major client_pg_restore_major client_pg_dump_major; do [[ "${e[$key]}" == 17 ]] || fail "client is not PostgreSQL 17: $key"; done
[[ "${e[target_postgres_major]}" == 17 ]] || fail "target server is not PostgreSQL 17"
for key in public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_count valorant_migration_count rls_enabled_table_count rls_table_count; do [[ "${e[$key]}" =~ ^[0-9]+$ && "${e[$key]}" -gt 0 ]] || fail "non-zero runtime evidence is missing: $key"; done
for key in roles_status memberships_status owners_status grants_status default_acl_status security_verify_status extensions_status settings_status rls_status quest_migration_ledger_status valorant_migration_ledger_status valorant_ca_status; do [[ "${e[$key]}" == verified ]] || fail "status is not verified: $key"; done
for key in public_upload_file_count public_upload_byte_count private_upload_file_count private_upload_byte_count resource_peak_memory_kb resource_disk_bytes rto_seconds extensions_count; do [[ "${e[$key]}" =~ ^[0-9]+$ ]] || fail "numeric evidence is malformed: $key"; done
[[ "${e[rto_seconds]}" -gt 0 && "${e[resource_peak_memory_kb]}" -gt 0 ]] || fail "RTO or resource range is invalid"
[[ "${e[upload_checksum_scope]}" == post_restore_tree && "${e[upload_source_equivalence]}" == not_claimed_without_source_inventory ]] || fail "upload checksum scope is overclaimed"
for key in public_upload_checksum private_upload_checksum; do [[ "${e[$key]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "upload checksum is malformed: $key"; done
for key in quest_liveness_status quest_readiness_status valorant_health_status; do [[ "${e[$key]}" == ok ]] || fail "health status is not ok: $key"; done
[[ "${e[quest_database_status]}" == up && "${e[valorant_database_status]}" == up ]] || fail "database health is not up"
[[ "${e[freeze_mode]}" == validation && "${e[writers_disabled]}" == true && "${e[mutation_rejection]}" == verified && "${e[no_writer_admission]}" == verified ]] || fail "freeze evidence is incomplete"
for key in failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback; do [[ "${e[$key]}" == passed ]] || fail "failure injection is not passed: $key"; done
[[ "${e[resource_cpu_seconds]}" =~ ^[0-9]+([.][0-9]+)?$ ]] || fail "CPU resource evidence is malformed"
[[ "${e[rto_decision]}" == met || "${e[rto_decision]}" == not_met ]] || fail "RTO decision is missing"
for key in created_at_utc restore_start_utc restore_end_utc; do [[ "${e[$key]}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] || fail "timestamp is malformed: $key"; date -u -d "${e[$key]}" +%s >/dev/null 2>&1 || fail "timestamp is invalid: $key"; done
now="$(date -u +%s)"; end="$(date -u -d "${e[restore_end_utc]}" +%s)"; age=$((now-end)); max_age="${REHEARSAL_EVIDENCE_MAX_AGE_SECONDS:-604800}"
[[ "$max_age" =~ ^[0-9]+$ && "$age" -ge 0 && "$age" -le "$max_age" ]] || fail "evidence is stale or from the future"
start="$(date -u -d "${e[restore_start_utc]}" +%s)"; [[ "$end" -ge "$start" && "${e[restore_duration_seconds]}" == $((end-start)) ]] || fail "timestamps and restore duration are inconsistent"
echo "Restore rehearsal evidence verified: complete disposable PostgreSQL 17 two-schema evidence."
