#!/usr/bin/env bash
set -euo pipefail
umask 077
repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"
fail() { echo "Restore rehearsal evidence refused: $1" >&2; exit 1; }
contract="$repo_root/ops/rehearsal/rehearsal-contract.sh"
[[ -r "$contract" && ! -L "$contract" ]] || fail "rehearsal contract is missing"
# shellcheck source=/dev/null
source "$contract"
[[ $# -eq 2 ]] || fail "usage: verify-rehearsal-evidence.sh /absolute/archive.tar.gz.enc /absolute/evidence-directory"
archive="$1"; dir="$2"
[[ "$archive" == /* && -f "$archive" && ! -L "$archive" ]] || fail "selected archive is missing or unsafe"
[[ "$(basename "$archive")" =~ ^quest-production-[0-9]{8}T[0-9]{6}Z\.tar\.gz\.enc$ ]] || fail "selected archive basename is invalid"
checksum="$archive.sha256"; [[ -f "$checksum" && ! -L "$checksum" ]] || fail "selected archive checksum is missing"
case "${archive,,}" in */questesports*|*/supabase*|*/var/www/quest-esports*|*/srv/quest-esports*|*/production/*) fail "selected archive path looks like production" ;; esac
[[ "$dir" == /* && "$dir" != / && -d "$dir" && ! -L "$dir" ]] || fail "evidence directory is missing or unsafe"
for path in "$archive" "$checksum" "$dir"; do
  while IFS= read -r part; do
    [[ -z "$part" ]] && continue
    [[ "$part" != . && "$part" != .. ]] || fail "evidence path contains a traversal component"
  done < <(printf '%s\n' "$path" | tr / '\n')
done
mode="$(stat -c '%a' -- "$dir" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "evidence directory is not private"
[[ "$(stat -c '%u:%g' -- "$dir" 2>/dev/null)" == "$(id -u):$(id -g)" ]] || fail "evidence directory ownership is not private"
case "${dir,,}" in *questesports*|*supabase*|*production*|*/var/www/*|*/srv/quest-esports/*) fail "evidence directory looks like production" ;; esac
file="$dir/rehearsal-evidence.env"; [[ -f "$file" && ! -L "$file" ]] || fail "machine-readable evidence is missing"
mode="$(stat -c '%a' -- "$file" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "evidence file is not private"
trusted_key="${REHEARSAL_TRUSTED_SIGNING_PUBLIC_KEY:-}"; [[ "$trusted_key" == /* && -f "$trusted_key" && ! -L "$trusted_key" && -r "$trusted_key" ]] || fail "trusted verification public key is required"
command -v openssl >/dev/null 2>&1 || fail "openssl is required to verify evidence signatures"
check_key_mode="$(stat -c '%a' -- "$trusted_key" 2>/dev/null)"; [[ "$check_key_mode" =~ ^[0-7]+$ ]] && (( (8#$check_key_mode & 022) == 0 )) || fail "trusted verification key is writable by group/world"
manifest="$dir/rehearsal-evidence.manifest"; signature="$dir/rehearsal-evidence.sig"; [[ -f "$manifest" && ! -L "$manifest" && -f "$signature" && ! -L "$signature" ]] || fail "signed evidence manifest/signature is missing"
manifest_mode="$(stat -c '%a' -- "$manifest")"; signature_mode="$(stat -c '%a' -- "$signature")"; [[ "$manifest_mode" =~ ^[0-7]+$ && "$signature_mode" =~ ^[0-7]+$ ]] && (( (8#$manifest_mode & 077) == 0 && (8#$signature_mode & 077) == 0 )) || fail "signed evidence files are not private"
openssl dgst -sha256 -verify "$trusted_key" -signature "$signature" "$manifest" >/dev/null 2>&1 || fail "evidence manifest signature is invalid"
declare -A e=()
while IFS= read -r line || [[ -n "$line" ]]; do
  [[ "$line" =~ ^([a-z][a-z0-9_]*)=([^[:space:]]+)$ ]] || fail "evidence has a malformed line"
  key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ -z "${e[$key]+x}" ]] || fail "evidence contains duplicate fields"; e["$key"]="$value"
  [[ "$key" == archive_name || ( "$value" != *://* && "$value" != */* && "$value" != *@* ) ]] || fail "evidence contains a URL/path"
  case "${value,,}" in *questesports*|*supabase*|*production*|*paris*|*/var/www/*|*/srv/quest-esports/*) [[ "$key" == archive_name ]] || fail "evidence looks like production" ;; esac
done < "$file"
observations="$dir/rehearsal-observations.env"; [[ -f "$observations" && ! -L "$observations" ]] || fail "raw command observations are missing"
mode="$(stat -c '%a' -- "$observations" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "raw observations are not private"
required=(format_version evidence_status rehearsal_mode restore_status created_at_utc restore_start_utc restore_end_utc restore_duration_seconds archive_name archive_sha256 observations_sha256 checksum_status decryption_status manifest_database_scope manifest_valorant_schema_included source_postgres_major target_postgres_major source_major_gate source_version_provenance source_version_record_sha256 client_psql_major client_pg_restore_major client_pg_dump_major public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_ledger_before_status valorant_migration_ledger_before_status quest_migration_ledger_status quest_migration_count valorant_migration_ledger_status valorant_migration_count roles_status owners_status grants_status default_acl_status memberships_status security_verify_status security_verify_output_sha256 extensions_status extensions_count extensions_inventory_sha256 extensions_before_status extensions_before_count extensions_before_inventory_sha256 settings_status settings_inventory_sha256 settings_before_status settings_before_inventory_sha256 rls_status roles_observations_sha256 memberships_observations_sha256 owners_observations_sha256 grants_observations_sha256 default_acl_observations_sha256 rls_observations_sha256 rls_enabled_table_count rls_table_count public_upload_file_count public_upload_byte_count public_upload_checksum private_upload_file_count private_upload_byte_count private_upload_checksum upload_checksum_scope upload_source_equivalence quest_liveness_status quest_readiness_status quest_database_status valorant_health_status valorant_database_status valorant_ca_status freeze_mode writers_disabled mutation_rejection no_writer_admission failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback resource_cpu_seconds resource_peak_memory_kb resource_disk_bytes rpo_seconds rpo_decision rto_seconds rto_decision target_kind target_id target_container_id target_sentinel_sha256 target_container_disk_bytes_before target_container_disk_bytes_after target_database_size_bytes target_host target_port target_nonce_sha256 bootstrap_sql_sha256 quest_read_probe_status quest_read_probe_count)
required+=(target_database_name target_nonce_after_sha256 quest_read_probe_session_user quest_read_probe_current_user quest_read_probe_application_name quest_read_probe_backend_pid quest_read_probe_ssl target_docker_before_sha256 target_mapping_sha256 target_mapping_after_sha256 target_connection_before_sha256 target_docker_connection_before_sha256 target_docker_after_sha256 target_connection_after_sha256 target_docker_connection_after_sha256)
required+=(target_server_version_num target_ssl_status target_ssl_session_status public_policy_count valorant_policy_count runtime_policy_status roles_nobypassrls_status quest_read_write_probe_status quest_write_probe_status cross_schema_denial_status quest_write_probe_session_user quest_write_probe_current_user quest_write_probe_application_name quest_write_probe_backend_pid quest_write_probe_ssl cross_schema_denial_session_user cross_schema_denial_current_user cross_schema_denial_application_name cross_schema_denial_backend_pid cross_schema_denial_ssl upload_cleanup_status schema_counts_observations_sha256 policy_counts_observations_sha256 quest_write_probe_observations_sha256 cross_schema_denial_observations_sha256 target_session_tls_observations_sha256 upload_cleanup_observations_sha256 live_disposable_rehearsal_gate)
for key in "${required[@]}"; do [[ -n "${e[$key]:-}" ]] || fail "required field missing: $key"; done
for key in "${!e[@]}"; do found=false; for known in "${required[@]}"; do [[ "$key" == "$known" ]] && found=true; done; [[ "$found" == true ]] || fail "unknown evidence field: $key"; done
[[ "$(wc -l < "$checksum" | tr -d ' ')" == 1 ]] || fail "archive checksum must contain exactly one row"; archive_line="$(tr -d '\r' < "$checksum")"; [[ "$archive_line" =~ ^[a-fA-F0-9]{64}[[:space:]]+\*?$(basename "$archive")$ ]] || fail "archive checksum does not identify selected archive"; (cd -- "$(dirname "$archive")" && sha256sum --check --status "$(basename "$checksum")") || fail "selected archive checksum failed"; [[ "$(sha256sum "$archive" | cut -d' ' -f1)" == "${e[archive_sha256]}" ]] || fail "summary is bound to a different archive"
expected_artifacts=(rehearsal-evidence.env rehearsal-observations.env rehearsal-source-version.env rehearsal-security-verifier.output rehearsal-target-sentinel.env rehearsal-failure-injections.tsv rehearsal-failure-bad_checksum.output rehearsal-failure-bad_decryption.output rehearsal-failure-wrong_ca.output rehearsal-failure-blocked_network.output rehearsal-failure-failed_service_health.output rehearsal-failure-attempted_mutation_callback.output rehearsal-failure-hook-bad_checksum.sh rehearsal-failure-hook-bad_decryption.sh rehearsal-failure-hook-wrong_ca.sh rehearsal-failure-hook-blocked_network.sh rehearsal-failure-hook-failed_service_health.sh rehearsal-failure-hook-attempted_mutation_callback.sh rehearsal-roles.tsv rehearsal-memberships.tsv rehearsal-owners.tsv rehearsal-grants.tsv rehearsal-acl.tsv rehearsal-ext-before.tsv rehearsal-ext.tsv rehearsal-settings-before.tsv rehearsal-settings.tsv rehearsal-rls.tsv rehearsal-schema-counts.tsv rehearsal-policy-counts.tsv rehearsal-target-session-tls.tsv rehearsal-quest-write-probe.tsv rehearsal-cross-schema-denial.tsv rehearsal-upload-cleanup.tsv rehearsal-quest-migrations-before.tsv rehearsal-valorant-migrations-before.tsv rehearsal-quest-migrations.tsv rehearsal-valorant-migrations.tsv rehearsal-target-docker-before.txt rehearsal-target-port-mapping.txt rehearsal-target-port-mapping-after.txt rehearsal-connection-binding.txt rehearsal-docker-connection-binding.txt rehearsal-target-docker-after.txt rehearsal-connection-binding-after.txt rehearsal-docker-connection-binding-after.txt rehearsal-quest-read-probe.tsv)
declare -A listed=()
while read -r listed_hash listed_name; do
  listed_name="${listed_name#\*}"
  [[ "$listed_hash" =~ ^[a-fA-F0-9]{64}$ && "$listed_name" != */* && "$listed_name" != *:* && -n "$listed_name" ]] || fail "evidence manifest row is malformed"
  [[ -z "${listed[$listed_name]+x}" ]] || fail "evidence manifest contains a duplicate"
  listed["$listed_name"]="$listed_hash"
  expected=false; for expected_name in "${expected_artifacts[@]}"; do [[ "$listed_name" == "$expected_name" ]] && expected=true; done
  [[ "$expected" == true ]] || fail "evidence manifest lists an unexpected artifact: $listed_name"
  [[ "$(sha256sum "$dir/$listed_name" | cut -d' ' -f1)" == "$listed_hash" ]] || fail "evidence artifact hash does not match manifest"
done < "$manifest"
[[ "${#listed[@]}" == "${#expected_artifacts[@]}" ]] || fail "evidence manifest does not cover every required artifact"
while IFS= read -r -d '' evidence_entry; do
  evidence_name="$(basename "$evidence_entry")"
  case "$evidence_name" in
    rehearsal-evidence.manifest|rehearsal-evidence.sig) ;;
    *) [[ -n "${listed[$evidence_name]+x}" ]] || fail "evidence directory contains an unlisted artifact" ;;
  esac
done < <(find -P "$dir" -mindepth 1 -maxdepth 1 -print0)
[[ "${e[observations_sha256]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "observation binding is malformed"
actual_observations_sha256="$(sha256sum "$observations" | cut -d' ' -f1)"; [[ "$actual_observations_sha256" == "${e[observations_sha256]}" ]] || fail "raw observations do not match summary binding"
declare -A o=()
while IFS= read -r line || [[ -n "$line" ]]; do
  [[ "$line" =~ ^([a-z][a-z0-9_]*)=([^[:space:]]+)$ ]] || fail "raw observations have a malformed line"
  key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ -z "${o[$key]+x}" ]] || fail "raw observations contain duplicate fields"; o["$key"]="$value"
  [[ "$value" != *://* && "$value" != */* && "$value" != *@* ]] || fail "raw observations contain a URL/path"
done < "$observations"
observed=(format_version observation_status restore_command_status checksum_command_status decryption_command_status source_version_provenance source_version_record_sha256 source_postgres_major target_postgres_major client_psql_major client_pg_restore_major client_pg_dump_major manifest_scope manifest_valorant_schema_included public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_ledger_before_status valorant_migration_ledger_before_status quest_migration_ledger_status quest_migration_count valorant_migration_ledger_status valorant_migration_count roles_command_status memberships_command_status owners_command_status grants_command_status default_acl_command_status rls_command_status roles_observations_sha256 memberships_observations_sha256 owners_observations_sha256 grants_observations_sha256 default_acl_observations_sha256 rls_observations_sha256 security_verify_status security_verify_output_sha256 extensions_inventory_sha256 settings_inventory_sha256 public_upload_file_count public_upload_byte_count public_upload_checksum private_upload_file_count private_upload_byte_count private_upload_checksum upload_checksum_scope upload_source_equivalence quest_liveness_status quest_readiness_status quest_database_status valorant_health_status valorant_database_status valorant_ca_status freeze_mode writers_disabled mutation_rejection no_writer_admission failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback resource_cpu_seconds resource_peak_memory_kb resource_disk_bytes rpo_seconds rpo_decision rto_seconds rto_decision)
observed+=(upload_checksum_scope upload_source_equivalence target_kind target_id target_container_id target_sentinel_sha256 target_container_disk_bytes_before target_container_disk_bytes_after target_database_size_bytes target_host target_port target_nonce_sha256 target_nonce_after_sha256 target_database_name bootstrap_sql_sha256 extensions_before_status extensions_before_count extensions_before_inventory_sha256 settings_before_status settings_before_inventory_sha256 quest_read_probe_status quest_read_probe_count quest_read_probe_session_user quest_read_probe_current_user quest_read_probe_application_name quest_read_probe_backend_pid quest_read_probe_ssl target_docker_before_sha256 target_mapping_sha256 target_mapping_after_sha256 target_connection_before_sha256 target_docker_connection_before_sha256 target_docker_after_sha256 target_connection_after_sha256 target_docker_connection_after_sha256)
observed+=(target_server_version_num target_ssl_status target_ssl_session_status public_policy_count valorant_policy_count runtime_policy_status roles_nobypassrls_status quest_read_write_probe_status quest_write_probe_status cross_schema_denial_status quest_write_probe_session_user quest_write_probe_current_user quest_write_probe_application_name quest_write_probe_backend_pid quest_write_probe_ssl cross_schema_denial_session_user cross_schema_denial_current_user cross_schema_denial_application_name cross_schema_denial_backend_pid cross_schema_denial_ssl upload_cleanup_status schema_counts_observations_sha256 policy_counts_observations_sha256 quest_write_probe_observations_sha256 cross_schema_denial_observations_sha256 target_session_tls_observations_sha256 upload_cleanup_observations_sha256 live_disposable_rehearsal_gate)
for key in "${observed[@]}"; do [[ -n "${o[$key]:-}" ]] || fail "raw observation field missing: $key"; done
for key in "${!o[@]}"; do found=false; for known in "${observed[@]}"; do [[ "$key" == "$known" ]] && found=true; done; [[ "$found" == true ]] || fail "unknown raw observation field: $key"; done
[[ "${o[format_version]}" == 1 && "${o[observation_status]}" == complete && "${o[restore_command_status]}" == verified && "${o[checksum_command_status]}" == verified && "${o[decryption_command_status]}" == verified ]] || fail "raw command observations are incomplete"
for artifact in roles memberships owners grants acl ext settings rls; do artifact_file="$dir/rehearsal-${artifact}.tsv"; [[ -f "$artifact_file" && ! -L "$artifact_file" ]] || fail "raw command artifact is missing: $artifact"; mode="$(stat -c '%a' -- "$artifact_file" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "raw command artifact is not private: $artifact"; done
source_artifact="$dir/rehearsal-source-version.env"; [[ -f "$source_artifact" && ! -L "$source_artifact" ]] || fail "source-version evidence artifact is missing"; mode="$(stat -c '%a' -- "$source_artifact" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "source-version evidence artifact is not private"
[[ "$(sha256sum "$source_artifact" | cut -d' ' -f1)" == "${e[source_version_record_sha256]}" ]] || fail "source-version evidence binding failed"
artifact_source_major="$(grep -m1 '^source_major=' "$source_artifact" | cut -d= -f2-)"; artifact_source_version="$(grep -m1 '^source_version=' "$source_artifact" | cut -d= -f2-)"
grep -Eq '://|/|@' "$source_artifact" && fail "source-version evidence contains a URL/path"; [[ "$artifact_source_major" == "${e[source_postgres_major]}" && "$artifact_source_version" =~ ^PostgreSQL_${e[source_postgres_major]}([.][0-9]+)?$ ]] && grep -qx 'provenance=operator_recorded' "$source_artifact" || fail "source-version evidence artifact is malformed"
target_artifact="$dir/rehearsal-target-sentinel.env"; mode="$(stat -c '%a' -- "$target_artifact" 2>/dev/null)"; [[ "$mode" == 600 ]] || fail "target sentinel artifact must have exact mode 600"; [[ "$(sha256sum "$target_artifact" | cut -d' ' -f1)" == "${e[target_sentinel_sha256]}" ]] || fail "target sentinel binding failed"
declare -A s=()
while IFS= read -r line || [[ -n "$line" ]]; do [[ "$line" =~ ^([a-z_]+)=([^[:space:]]+)$ ]] || fail "target sentinel artifact is malformed"; key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ -z "${s[$key]+x}" ]] || fail "target sentinel artifact contains a duplicate"; case "$key" in target_kind|target_id|container_id|public_root|private_root) s["$key"]="$value" ;; *) fail "target sentinel artifact contains an unknown field" ;; esac; done < "$target_artifact"
for key in target_kind target_id container_id public_root private_root; do [[ -n "${s[$key]:-}" ]] || fail "target sentinel artifact is incomplete"; done
[[ "${s[target_kind]}" == "${e[target_kind]}" && "${s[target_id]}" == "${e[target_id]}" && "${s[container_id]}" == "${e[target_container_id]}" ]] || fail "target sentinel artifact does not match evidence"
for migration_artifact in rehearsal-quest-migrations-before.tsv rehearsal-valorant-migrations-before.tsv; do [[ "$(tr -d '\r' < "$dir/$migration_artifact")" == status\|absent ]] || fail "pre-restore migration inventory is not absent: $migration_artifact"; done
for migration_artifact in rehearsal-quest-migrations.tsv rehearsal-valorant-migrations.tsv; do [[ "$(wc -l < "$dir/$migration_artifact" | tr -d ' ')" =~ ^[1-9][0-9]*$ ]] || fail "post-restore migration inventory is empty: $migration_artifact"; while IFS='|' read -r migration_id completion; do [[ "$migration_id" =~ ^[A-Za-z0-9_.-]+$ && "$completion" == complete ]] || fail "post-restore migration inventory is incomplete: $migration_artifact"; done < "$dir/$migration_artifact"; done
[[ "$(wc -l < "$dir/rehearsal-quest-migrations.tsv" | tr -d ' ')" == "${e[quest_migration_count]}" && "$(wc -l < "$dir/rehearsal-valorant-migrations.tsv" | tr -d ' ')" == "${e[valorant_migration_count]}" ]] || fail "migration summary counts do not match signed inventories"
[[ "$(sha256sum "$dir/rehearsal-ext-before.tsv" | cut -d' ' -f1)" == "${e[extensions_before_inventory_sha256]}" && "$(sha256sum "$dir/rehearsal-settings-before.tsv" | cut -d' ' -f1)" == "${e[settings_before_inventory_sha256]}" && "$(sha256sum "$dir/rehearsal-ext.tsv" | cut -d' ' -f1)" == "${e[extensions_inventory_sha256]}" && "$(sha256sum "$dir/rehearsal-settings.tsv" | cut -d' ' -f1)" == "${e[settings_inventory_sha256]}" ]] || fail "extension/settings artifacts are not bound"
cmp -s "$dir/rehearsal-ext-before.tsv" "$dir/rehearsal-ext.tsv" || fail "extension inventory changed between before/after restore"
cmp -s "$dir/rehearsal-settings-before.tsv" "$dir/rehearsal-settings.tsv" || fail "PostgreSQL settings changed between before/after restore"
[[ "$(wc -l < "$dir/rehearsal-ext.tsv" | tr -d ' ')" == 1 && "$(tr -d '\r' < "$dir/rehearsal-ext.tsv")" == 'plpgsql|1.0' && "$(tr -d '\r' < "$dir/rehearsal-ext-before.tsv")" == 'plpgsql|1.0' ]] || fail "extension inventory is outside the explicit allowlist"
for target_artifact in target-docker-before target-port-mapping target-port-mapping-after connection-binding docker-connection-binding target-docker-after connection-binding-after docker-connection-binding-after; do
  case "$target_artifact" in
    target-docker-before) field=target_docker_before_sha256 ;;
    target-port-mapping) field=target_mapping_sha256 ;;
    target-port-mapping-after) field=target_mapping_after_sha256 ;;
    connection-binding) field=target_connection_before_sha256 ;;
    docker-connection-binding) field=target_docker_connection_before_sha256 ;;
    target-docker-after) field=target_docker_after_sha256 ;;
    connection-binding-after) field=target_connection_after_sha256 ;;
    docker-connection-binding-after) field=target_docker_connection_after_sha256 ;;
  esac
  target_hash="$(sha256sum "$dir/rehearsal-${target_artifact}.txt" | cut -d' ' -f1)"; [[ "$target_hash" == "${e[$field]}" && "$target_hash" == "${o[$field]}" ]] || fail "target binding artifact is not bound: $target_artifact"
done
for artifact_pair in 'schema-counts|schema_counts_observations_sha256' 'policy-counts|policy_counts_observations_sha256' 'target-session-tls|target_session_tls_observations_sha256' 'quest-write-probe|quest_write_probe_observations_sha256' 'cross-schema-denial|cross_schema_denial_observations_sha256' 'upload-cleanup|upload_cleanup_observations_sha256'; do
  artifact="${artifact_pair%%|*}"; field="${artifact_pair#*|}"; artifact_file="$dir/rehearsal-${artifact}.tsv"; [[ -f "$artifact_file" && ! -L "$artifact_file" ]] || fail "new signed artifact is missing: $artifact"; mode="$(stat -c '%a' -- "$artifact_file" 2>/dev/null)"; [[ "$mode" =~ ^[0-7]+$ ]] && (( (8#$mode & 077) == 0 )) || fail "new signed artifact is not private: $artifact"; hash="$(sha256sum "$artifact_file" | cut -d' ' -f1)"; [[ "$hash" == "${e[$field]}" && "$hash" == "${o[$field]}" ]] || fail "new signed artifact binding failed: $artifact";
done
[[ "$(wc -l < "$dir/rehearsal-schema-counts.tsv" | tr -d ' ')" == 2 ]] || fail "schema count artifact must contain exactly two schemas"
declare -A seen_schema_counts=()
while IFS='|' read -r schema tables objects; do [[ "$schema" == public || "$schema" == valorant ]] || fail "schema count artifact has an unsafe schema"; [[ "$tables" =~ ^[0-9]+$ && "$objects" =~ ^[0-9]+$ && "$tables" -gt 0 && "$objects" -gt 0 ]] || fail "schema count artifact is malformed"; case "$schema" in public) [[ "$tables" == "${e[public_table_count]}" && "$objects" == "${e[public_object_count]}" ]] || fail "public counts are not recomputed from the signed artifact" ;; valorant) [[ "$tables" == "${e[valorant_table_count]}" && "$objects" == "${e[valorant_object_count]}" ]] || fail "VALORANT counts are not recomputed from the signed artifact" ;; esac; done < "$dir/rehearsal-schema-counts.tsv"
while IFS='|' read -r schema tables objects; do [[ -z "${seen_schema_counts[$schema]+x}" ]] || fail "schema count artifact contains a duplicate schema"; seen_schema_counts["$schema"]=1; done < "$dir/rehearsal-schema-counts.tsv"
[[ -n "${seen_schema_counts[public]:-}" && -n "${seen_schema_counts[valorant]:-}" ]] || fail "schema count artifact does not contain exactly public and valorant"
[[ "$(wc -l < "$dir/rehearsal-policy-counts.tsv" | tr -d ' ')" == 2 ]] || fail "policy count artifact must contain exactly two schemas"
declare -A seen_policy_counts=()
while IFS='|' read -r schema count; do [[ "$schema" == public || "$schema" == valorant ]] || fail "policy count artifact has an unsafe schema"; [[ -z "${seen_policy_counts[$schema]+x}" ]] || fail "policy count artifact contains a duplicate schema"; seen_policy_counts["$schema"]=1; [[ "$count" =~ ^[0-9]+$ && "$count" -gt 0 ]] || fail "policy count artifact is malformed"; case "$schema" in public) [[ "$count" == "${e[public_policy_count]}" ]] || fail "public policy count is not recomputed from the signed artifact" ;; valorant) [[ "$count" == "${e[valorant_policy_count]}" ]] || fail "VALORANT policy count is not recomputed from the signed artifact" ;; esac; done < "$dir/rehearsal-policy-counts.tsv"
[[ -n "${seen_policy_counts[public]:-}" && -n "${seen_policy_counts[valorant]:-}" ]] || fail "policy count artifact does not contain exactly public and valorant"
IFS='|' read -r tls_app tls_pid tls_status < "$dir/rehearsal-target-session-tls.tsv"; tls_nonce="${tls_app#quest-rehearsal-}"; [[ "$tls_app" =~ ^quest-rehearsal-[0-9a-f]{64}$ && "$tls_pid" =~ ^[0-9]+$ && "$tls_status" == on && "$(printf '%s' "$tls_nonce" | sha256sum | cut -d' ' -f1)" == "${e[target_nonce_sha256]}" ]] || fail "session-level pg_stat_ssl evidence is invalid or nonce-unbound"
IFS='|' read -r before_binding_app _ _ _ _ before_binding_pid < "$dir/rehearsal-connection-binding.txt"; [[ "$tls_app" == "$before_binding_app" && "$tls_pid" == "$before_binding_pid" ]] || fail "session-level TLS evidence is not bound to the validated target session"
for binding_phase in before after; do
  if [[ "$binding_phase" == before ]]; then direct_file="$dir/rehearsal-connection-binding.txt"; expected_nonce="${e[target_nonce_sha256]}"; else direct_file="$dir/rehearsal-connection-binding-after.txt"; expected_nonce="${e[target_nonce_after_sha256]}"; fi
  [[ "$(wc -l < "$direct_file" | tr -d ' ')" == 2 ]] || fail "raw target connection binding/TLS output is incomplete: $binding_phase"
  IFS='|' read -r raw_binding_app raw_binding_database raw_binding_session_user raw_binding_current_user raw_binding_port raw_binding_pid < "$direct_file"
  IFS='|' read -r raw_database raw_version raw_ssl raw_app raw_pid < <(sed -n '2p' "$direct_file")
  raw_nonce="${raw_app#quest-rehearsal-}"
  [[ "$raw_binding_app" == "$raw_app" && "$raw_binding_database" == "$raw_database" && "$raw_binding_pid" == "$raw_pid" && "$raw_database" == "${e[target_database_name]}" && "$raw_version" =~ ^17[0-9]{4}$ && "$raw_ssl" == on && "$raw_app" =~ ^quest-rehearsal-[0-9a-f]{64}$ && "$raw_pid" =~ ^[0-9]+$ && "$(printf '%s' "$raw_nonce" | sha256sum | cut -d' ' -f1)" == "$expected_nonce" ]] || fail "raw target connection binding/TLS output is invalid: $binding_phase"
done
IFS='|' read -r write_session_user write_current_user _ write_app write_pid write_ssl < <(grep -E '^quest_runtime\|quest_runtime\|write_verified\|quest-write-probe-[0-9a-f]{64}\|[0-9]+\|on$' "$dir/rehearsal-quest-write-probe.tsv")
[[ "$(grep -Ec '^quest_runtime\|quest_runtime\|write_verified\|quest-write-probe-[0-9a-f]{64}\|[0-9]+\|on$' "$dir/rehearsal-quest-write-probe.tsv")" == 1 && "$(grep -Fxc 'BEGIN' "$dir/rehearsal-quest-write-probe.tsv" || true)" == 1 && "$(grep -Fxc 'INSERT 0 1' "$dir/rehearsal-quest-write-probe.tsv" || true)" == 1 && "$(grep -Fxc 'ROLLBACK' "$dir/rehearsal-quest-write-probe.tsv" || true)" == 1 ]] || fail "signed write probe artifact is invalid"
write_nonce="${write_app#quest-write-probe-}"; [[ "$write_session_user" == quest_runtime && "$write_current_user" == quest_runtime && "$write_app" =~ ^quest-write-probe-[0-9a-f]{64}$ && "$(printf '%s' "$write_nonce" | sha256sum | cut -d' ' -f1)" == "${e[target_nonce_after_sha256]}" && "$write_pid" =~ ^[0-9]+$ && "$write_ssl" == on ]] || fail "signed write probe is not bound to its nonce session and TLS"
! grep -Eiq '(^|[[:space:]])(ERROR|FATAL|PANIC)(:|[[:space:]])' "$dir/rehearsal-quest-write-probe.tsv" || fail "signed write probe contains an error"
declare -A denial=()
while IFS= read -r line || [[ -n "$line" ]]; do
  [[ "$line" =~ ^([a-z_]+)=(.*)$ ]] || fail "signed cross-schema denial artifact is malformed"
  key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ -z "${denial[$key]+x}" ]] || fail "signed cross-schema denial artifact contains a duplicate"
  case "$key" in session_user|current_user|application_name|backend_pid|ssl|sqlstate|error_class|diagnostic) denial["$key"]="$value" ;; *) fail "signed cross-schema denial artifact contains an unknown field" ;; esac
done < "$dir/rehearsal-cross-schema-denial.tsv"
for key in session_user current_user application_name backend_pid ssl sqlstate error_class diagnostic; do [[ -n "${denial[$key]:-}" ]] || fail "signed cross-schema denial artifact is incomplete"; done
denial_nonce="${denial[application_name]#quest-denial-probe-}"
[[ "${denial[session_user]}" == quest_runtime && "${denial[current_user]}" == quest_runtime && "${denial[application_name]}" =~ ^quest-denial-probe-[0-9a-f]{64}$ && "$(printf '%s' "$denial_nonce" | sha256sum | cut -d' ' -f1)" == "${e[target_nonce_after_sha256]}" && "${denial[backend_pid]}" =~ ^[0-9]+$ && "${denial[ssl]}" == on && "${denial[sqlstate]}" == 42501 && "${denial[error_class]}" == permission_denied ]] || fail "signed cross-schema denial is not bound to its nonce session and TLS"
grep -Eiq '^diagnostic=.*permission denied for (schema valorant|table _migration_ledger)' "$dir/rehearsal-cross-schema-denial.tsv" || fail "signed cross-schema denial diagnostic is invalid"; ! grep -Eiq 'authentication|malformed|syntax error|timeout|could not connect|://|(^|[[:space:]])(PASSWORD|TOKEN|SECRET)=' "$dir/rehearsal-cross-schema-denial.tsv" || fail "signed cross-schema denial diagnostic contains an unexpected failure"
[[ "${e[quest_write_probe_session_user]}" == "$write_session_user" && "${e[quest_write_probe_current_user]}" == "$write_current_user" && "${e[quest_write_probe_application_name]}" == "$write_app" && "${e[quest_write_probe_backend_pid]}" == "$write_pid" && "${e[quest_write_probe_ssl]}" == "$write_ssl" && "${e[cross_schema_denial_session_user]}" == "${denial[session_user]}" && "${e[cross_schema_denial_current_user]}" == "${denial[current_user]}" && "${e[cross_schema_denial_application_name]}" == "${denial[application_name]}" && "${e[cross_schema_denial_backend_pid]}" == "${denial[backend_pid]}" && "${e[cross_schema_denial_ssl]}" == "${denial[ssl]}" ]] || fail "summary runtime probe identities do not match signed probe artifacts"
[[ "$(tr -d '\r' < "$dir/rehearsal-upload-cleanup.tsv")" == $'status=verified\npublic_root_removed=true\nprivate_root_removed=true\nparent_removed=true' ]] || fail "signed disposable upload cleanup evidence is invalid"
canonical_acl="$(rehearsal_canonical_acl_rows | LC_ALL=C sort)"; observed_acl="$(LC_ALL=C sort "$dir/rehearsal-acl.tsv")"; [[ "$observed_acl" == "$canonical_acl" ]] || fail "default ACL payload does not match canonical bootstrap contract"
for docker_artifact in rehearsal-target-docker-before.txt rehearsal-target-docker-after.txt; do IFS='|' read -r docker_id docker_name docker_running docker_image docker_size < "$dir/$docker_artifact"; [[ "$docker_id" == "${e[target_container_id]}" && "$docker_name" == /quest-rehearsal-* && "$docker_running" == true && "$docker_image" =~ ^postgres:17-bookworm@sha256:[0-9a-f]{64}$ && "$docker_size" =~ ^[0-9]+$ ]] || fail "Docker target identity artifact is unsafe: $docker_artifact"; done
before_nonce=""
for binding_phase in before after; do
  if [[ "$binding_phase" == before ]]; then direct_file="$dir/rehearsal-connection-binding.txt"; docker_file="$dir/rehearsal-docker-connection-binding.txt"; else direct_file="$dir/rehearsal-connection-binding-after.txt"; docker_file="$dir/rehearsal-docker-connection-binding-after.txt"; fi
  IFS='|' read -r binding_app binding_database binding_session_user binding_current_user binding_port binding_pid < "$direct_file"
  IFS='|' read -r observed_app observed_database observed_user observed_state observed_port observed_pid < "$docker_file"
  [[ "$binding_app" =~ ^quest-rehearsal-[0-9a-f]{64}$ && "$binding_database" == "${e[target_database_name]}" && "$binding_session_user" =~ ^[A-Za-z_][A-Za-z0-9_]*$ && "$binding_current_user" =~ ^[A-Za-z_][A-Za-z0-9_]*$ && "$binding_port" == 5432 && "$binding_pid" =~ ^[0-9]+$ && "$observed_app" == "$binding_app" && "$observed_database" == "$binding_database" && "$observed_user" == "$binding_session_user" && "$observed_state" == active && "$observed_port" == 5432 && "$observed_pid" == "$binding_pid" ]] || fail "active target connection-binding artifacts are malformed: $binding_phase"
  nonce="${binding_app#quest-rehearsal-}"; nonce_hash="$(printf '%s' "$nonce" | sha256sum | cut -d' ' -f1)"
  if [[ "$binding_phase" == before ]]; then before_nonce="$nonce"; [[ "$nonce_hash" == "${e[target_nonce_sha256]}" && "$nonce_hash" == "${o[target_nonce_sha256]}" ]] || fail "fresh target nonce hash does not match the observed connection"; else [[ "$nonce_hash" == "${e[target_nonce_after_sha256]}" && "$nonce_hash" == "${o[target_nonce_after_sha256]}" && "$nonce" != "$before_nonce" ]] || fail "post-restore target nonce is not fresh and bound"; fi
done
IFS='|' read -r read_session_user read_current_user read_count read_app read_pid read_ssl < "$dir/rehearsal-quest-read-probe.tsv"; runtime_nonce="${read_app#quest-runtime-probe-}"
[[ "$read_session_user" == quest_runtime && "$read_current_user" == quest_runtime && "$read_count" =~ ^[0-9]+$ && "$read_count" == "${e[quest_read_probe_count]}" && "$read_app" =~ ^quest-runtime-probe-[0-9a-f]{64}$ && "$(printf '%s' "$runtime_nonce" | sha256sum | cut -d' ' -f1)" == "${e[target_nonce_after_sha256]}" && "$read_pid" =~ ^[0-9]+$ && "$read_ssl" == on && "${e[quest_read_probe_session_user]}" == "$read_session_user" && "${e[quest_read_probe_current_user]}" == "$read_current_user" && "${e[quest_read_probe_application_name]}" == "$read_app" && "${e[quest_read_probe_backend_pid]}" == "$read_pid" && "${e[quest_read_probe_ssl]}" == "$read_ssl" && "${o[quest_read_probe_session_user]}" == "$read_session_user" && "${o[quest_read_probe_current_user]}" == "$read_current_user" ]] || fail "Quest read probe is not bound to the authenticated quest_runtime session, target nonce, and TLS"
for mapping_artifact in rehearsal-target-port-mapping.txt rehearsal-target-port-mapping-after.txt; do grep -Eq '"HostIp"[[:space:]]*:[[:space:]]*"127\.0\.0\.1"' "$dir/$mapping_artifact" && grep -Eq '"HostPort"[[:space:]]*:[[:space:]]*"'"${e[target_port]}"'"' "$dir/$mapping_artifact" || fail "target port mapping artifact is not bound to the approved loopback endpoint"; done
cmp -s "$dir/rehearsal-target-port-mapping.txt" "$dir/rehearsal-target-port-mapping-after.txt" || fail "target port mapping changed during restore"
[[ "$(wc -l < "$dir/rehearsal-acl.tsv" | tr -d ' ')" == 12 ]] || fail "default ACL payload contains unexpected extra rows"
[[ "$(wc -l < "$dir/rehearsal-failure-injections.tsv" | tr -d ' ')" == 6 ]] || fail "failure-injection inventory is incomplete"
declare -A inventory_endpoint_id=() inventory_endpoint_sha256=()
while IFS='|' read -r injection hook hook_hash staged_hook staged_hook_hash endpoint_id endpoint_sha256 result output_hash; do [[ "$injection" =~ ^(bad_checksum|bad_decryption|wrong_ca|blocked_network|failed_service_health|attempted_mutation_callback)$ && "$hook_hash" =~ ^[a-fA-F0-9]{64}$ && "$staged_hook" == "$dir/rehearsal-failure-hook-${injection}.sh" && "$staged_hook_hash" =~ ^[a-fA-F0-9]{64}$ && "$endpoint_sha256" =~ ^[a-fA-F0-9]{64}$ && "$result" == passed && "$output_hash" =~ ^[a-fA-F0-9]{64}$ ]] || fail "failure-injection executable identity is malformed"; rehearsal_safe_hook_path "$hook" || fail "failure-injection source path is unsafe"; rehearsal_safe_hook_path "$staged_hook" || fail "staged failure-injection path is unsafe"; [[ "$(sha256sum "$hook" | cut -d' ' -f1)" == "$hook_hash" ]] || fail "configured failure-injection source hash does not match"; [[ -z "${inventory_endpoint_id[$injection]+x}" ]] || fail "failure-injection inventory contains a duplicate"; expected_endpoint_id="$(rehearsal_failure_endpoint_id "$injection")" || fail "failure-injection endpoint mapping is missing"; [[ "$endpoint_id" == "$expected_endpoint_id" ]] || fail "failure-injection endpoint ID is not canonical"; inventory_endpoint_id["$injection"]="$endpoint_id"; inventory_endpoint_sha256["$injection"]="$endpoint_sha256"; [[ "$(sha256sum "$staged_hook" | cut -d' ' -f1)" == "$staged_hook_hash" ]] || fail "staged failure-injection executable hash does not match"; output_file="$dir/rehearsal-failure-${injection}.output"; [[ "$(sha256sum "$output_file" | cut -d' ' -f1)" == "$output_hash" ]] || fail "failure-injection output hash does not match"; done < "$dir/rehearsal-failure-injections.tsv"
declare -A expected_failure_class=([bad_checksum]=archive_checksum_failed [bad_decryption]=age_decryption_failed [wrong_ca]=certificate_verification_failed [blocked_network]=network_blocked [failed_service_health]=service_health_failed [attempted_mutation_callback]=writer_mutation_rejected)
declare -A expected_failure_service=([bad_checksum]=quest-backup [bad_decryption]=quest-backup [wrong_ca]=valorant-health [blocked_network]=valorant-health [failed_service_health]=valorant-health [attempted_mutation_callback]=quest-api)
for injection in bad_checksum bad_decryption wrong_ca blocked_network failed_service_health attempted_mutation_callback; do
  output_file="$dir/rehearsal-failure-${injection}.output"; declare -A failure=()
  while IFS= read -r line || [[ -n "$line" ]]; do [[ "$line" =~ ^([a-z][a-z0-9_]*)=([^[:space:]]+)$ ]] || fail "failure-injection output is malformed"; key="${BASH_REMATCH[1]}"; value="${BASH_REMATCH[2]}"; [[ "$key" == result || "$key" == failure_class || "$key" == service_identity || "$key" == endpoint_id || "$key" == endpoint_sha256 || "$key" == pre_state || "$key" == post_state || "$key" == containment || "$key" == unaffected_service ]] || fail "failure-injection output has an unknown field"; [[ -z "${failure[$key]+x}" ]] || fail "failure-injection output contains a duplicate"; failure["$key"]="$value"; done < "$output_file"
  for key in result failure_class service_identity endpoint_id endpoint_sha256 pre_state post_state containment unaffected_service; do [[ -n "${failure[$key]:-}" ]] || fail "failure-injection output is incomplete"; done
  case "$injection" in bad_checksum|bad_decryption|wrong_ca) expected_pre_state=running; expected_post_state=running ;; blocked_network|attempted_mutation_callback) expected_pre_state=running; expected_post_state=blocked ;; failed_service_health) expected_pre_state=running; expected_post_state=stopped ;; esac
  [[ "${failure[result]}" == passed && "${failure[failure_class]}" == "${expected_failure_class[$injection]}" && "${failure[service_identity]}" == "${expected_failure_service[$injection]}" && "${failure[endpoint_id]}" == "${inventory_endpoint_id[$injection]}" && "${failure[endpoint_sha256]}" == "${inventory_endpoint_sha256[$injection]}" && "${failure[pre_state]}" == "$expected_pre_state" && "${failure[post_state]}" == "$expected_post_state" && "${failure[containment]}" == verified && "${failure[unaffected_service]}" == verified ]] || fail "failure-injection containment evidence is invalid"
done
security_artifact="$dir/rehearsal-security-verifier.output"; [[ -f "$security_artifact" && ! -L "$security_artifact" ]] || fail "security verifier output artifact is missing"; [[ "$(sha256sum "$security_artifact" | cut -d' ' -f1)" == "${e[security_verify_output_sha256]}" && "$(sha256sum "$security_artifact" | cut -d' ' -f1)" == "${o[security_verify_output_sha256]}" ]] || fail "security verifier output binding failed"; [[ "$(tr -d '\r' < "$security_artifact")" == security-verified ]] || fail "security verifier output token is invalid"; grep -Eq '://|(^|[[:space:]])(PASSWORD|TOKEN|SECRET)=' "$security_artifact" && fail "security verifier output contains sensitive text"
for pair in "roles|roles_observations_sha256" "memberships|memberships_observations_sha256" "owners|owners_observations_sha256" "grants|grants_observations_sha256" "acl|default_acl_observations_sha256" "rls|rls_observations_sha256"; do artifact="${pair%%|*}"; field="${pair#*|}"; hash="$(sha256sum "$dir/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; [[ "$hash" == "${e[$field]}" && "$hash" == "${o[$field]}" ]] || fail "raw command artifact binding failed: $artifact"; done
[[ "$(wc -l < "$dir/rehearsal-roles.tsv" | tr -d ' ')" == 4 ]] || fail "role observation does not contain four roles"
while IFS='|' read -r role login inherit super createdb createrole replication bypass; do [[ "$role" =~ ^(quest_migrator|quest_runtime|val_migrator|val_runtime)$ && "$login" == t && "$inherit" == f && "$super" == f && "$createdb" == f && "$createrole" == f && "$replication" == f && "$bypass" == f ]] || fail "raw role attributes are unsafe"; done < "$dir/rehearsal-roles.tsv"
[[ "$(tr -d '[:space:]' < "$dir/rehearsal-memberships.tsv")" == 0 ]] || fail "raw membership observation is unsafe"
grep -qx 'public|quest_migrator' "$dir/rehearsal-owners.tsv" && grep -qx 'valorant|val_migrator' "$dir/rehearsal-owners.tsv" || fail "raw schema owner observation is unsafe"
[[ "$(wc -l < "$dir/rehearsal-grants.tsv" | tr -d ' ')" == 12 ]] || fail "raw grant inventory is incomplete"
while IFS='|' read -r kind scope role privilege granted; do [[ "$granted" == t && ( "$kind" == schema || "$kind" == table || "$kind" == sequence ) ]] || fail "raw grant inventory contains an unsafe row"; done < "$dir/rehearsal-grants.tsv"
for expected in 'schema|public|quest_migrator|USAGE|t' 'schema|public|quest_migrator|CREATE|t' 'schema|public|quest_runtime|USAGE|t' 'schema|valorant|val_migrator|USAGE|t' 'schema|valorant|val_migrator|CREATE|t' 'schema|valorant|val_runtime|USAGE|t' 'schema|valorant|quest_runtime|USAGE_DENIED|t' 'schema|public|val_runtime|USAGE_DENIED|t' 'table|public|quest_runtime|all|t' 'table|valorant|val_runtime|all|t' 'sequence|public|quest_runtime|usage_select|t' 'sequence|valorant|val_runtime|usage_select|t'; do grep -qx "$expected" "$dir/rehearsal-grants.tsv" || fail "expected grant/denial is missing"; done
while IFS='|' read -r role schema object acl; do [[ "$role" == quest_migrator || "$role" == val_migrator ]] || fail "raw default ACL role is unsafe"; [[ "$schema" == public || "$schema" == valorant || "$schema" == '<global>' ]] || fail "raw default ACL scope is unsafe"; [[ "$object" == r || "$object" == S || "$object" == f || "$object" == F || "$object" == T ]] || fail "raw default ACL object type is unsafe"; done < "$dir/rehearsal-acl.tsv"
for expected in 'quest_migrator|public|r' 'quest_migrator|public|S' 'quest_migrator|public|f' 'quest_migrator|public|T' 'val_migrator|valorant|r' 'val_migrator|valorant|S' 'val_migrator|valorant|f' 'val_migrator|valorant|T' 'quest_migrator|<global>|f' 'quest_migrator|<global>|T' 'val_migrator|<global>|f' 'val_migrator|<global>|T'; do grep -q "^${expected}|" "$dir/rehearsal-acl.tsv" || fail "expected default ACL entry is missing"; done
grep -Eq '(^|[{,])=' "$dir/rehearsal-acl.tsv" && fail "raw default ACL contains a PUBLIC grant"
grep -Eq '^[A-Za-z0-9_]+\|[^[:space:]]+$' "$dir/rehearsal-ext.tsv" || fail "raw extension inventory is malformed"
grep -Eq '^[A-Za-z0-9_]+\|[^[:space:]]+$' "$dir/rehearsal-ext-before.tsv" || fail "raw pre-restore extension inventory is malformed"
[[ "$(wc -l < "$dir/rehearsal-ext.tsv" | tr -d ' ')" == 1 && "$(tr -d '\r' < "$dir/rehearsal-ext.tsv")" == 'plpgsql|1.0' && "$(tr -d '\r' < "$dir/rehearsal-ext-before.tsv")" == 'plpgsql|1.0' ]] || fail "extension inventory is outside the explicit allowlist"
grep -Eq '^[a-z_]+\|[^[:space:]]+$' "$dir/rehearsal-settings.tsv" || fail "raw settings inventory is malformed"
grep -Eq '^[a-z_]+\|[^[:space:]]+$' "$dir/rehearsal-settings-before.tsv" || fail "raw pre-restore settings inventory is malformed"
grep -Eq '^server_version_num\|17[0-9]{4}$' "$dir/rehearsal-settings.tsv" || fail "raw target server setting is not PostgreSQL 17"
grep -Eq '^server_version_num\|17[0-9]{4}$' "$dir/rehearsal-settings-before.tsv" || fail "raw pre-restore server setting is not PostgreSQL 17"
for settings_file in "$dir/rehearsal-settings.tsv" "$dir/rehearsal-settings-before.tsv"; do grep -qx 'ssl|on' "$settings_file" && grep -Eq '^ssl_min_protocol_version\|TLSv1\.(2|3)$' "$settings_file" && grep -qx 'row_security|on' "$settings_file" && grep -qx 'default_transaction_read_only|off' "$settings_file" && grep -Eq '^listen_addresses\|([*]|localhost|127\.0\.0\.1)$' "$settings_file" || fail "unsafe PostgreSQL setting observed"; done
for settings_file in "$dir/rehearsal-settings.tsv" "$dir/rehearsal-settings-before.tsv"; do [[ "$(wc -l < "$settings_file" | tr -d ' ')" == 7 ]] || fail "PostgreSQL settings inventory contains extra rows"; grep -Eq '^server_version\|17[.][0-9]+(_[A-Za-z0-9_.:+*/-]+)?$' "$settings_file" || fail "PostgreSQL server_version is not a 17.x value"; done
[[ "$(wc -l < "$dir/rehearsal-rls.tsv" | tr -d ' ')" -gt 0 ]] || fail "raw RLS inventory is empty"
public_rls_tables=0; valorant_rls_tables=0; public_policy_rows=0; valorant_policy_rows=0; declare -A seen_runtime_rls_rows=()
while IFS=$'\t' read -r schema table protected policy roles command qual with_check; do
  [[ "$schema" == public || "$schema" == valorant ]] || fail "raw RLS schema is unsafe"
  [[ -n "$table" && ( "$protected" == t || "$protected" == f ) && -n "$policy" && -n "$roles" && -n "$command" && -n "$qual" && -n "$with_check" ]] || fail "raw RLS row is incomplete"
  expected_role=quest_runtime; [[ "$schema" == valorant ]] && expected_role=val_runtime
  if [[ "$schema" == valorant && "$table" != _migration_ledger ]]; then [[ -z "${seen_runtime_rls_rows["$schema|$table"]+x}" ]] || fail "signed RLS artifact contains duplicate runtime table rows"; seen_runtime_rls_rows["$schema|$table"]=1; valorant_rls_tables=$((valorant_rls_tables+1)); [[ "$protected" == t && "$policy" == "${table}_runtime_all" && "$roles" == "$expected_role" && "$command" == 'ALL' && "$qual" == true && "$with_check" == true ]] || fail "VALORANT RLS policy is incomplete"; valorant_policy_rows=$((valorant_policy_rows+1)); fi
  if [[ "$schema" == public && "$table" != _prisma_migrations ]]; then [[ -z "${seen_runtime_rls_rows["$schema|$table"]+x}" ]] || fail "signed RLS artifact contains duplicate runtime table rows"; seen_runtime_rls_rows["$schema|$table"]=1; public_rls_tables=$((public_rls_tables+1)); [[ "$protected" == t && "$policy" == "${table}_runtime_all" && "$roles" == "$expected_role" && "$command" == 'ALL' && "$qual" == true && "$with_check" == true ]] || fail "Quest RLS policy is incomplete"; public_policy_rows=$((public_policy_rows+1)); fi
done < "$dir/rehearsal-rls.tsv"
[[ "$public_policy_rows" == "${e[public_policy_count]}" && "$valorant_policy_rows" == "${e[valorant_policy_count]}" && "$public_rls_tables" == "${e[public_table_count]}" && "$valorant_rls_tables" == "${e[valorant_table_count]}" ]] || fail "policy counts do not match semantically validated signed RLS rows"
[[ "${o[extensions_inventory_sha256]}" == "${e[extensions_inventory_sha256]}" && "${o[settings_inventory_sha256]}" == "${e[settings_inventory_sha256]}" && "${o[extensions_before_inventory_sha256]}" == "${e[extensions_before_inventory_sha256]}" && "${o[settings_before_inventory_sha256]}" == "${e[settings_before_inventory_sha256]}" ]] || fail "inventory binding is inconsistent"
[[ "${e[target_kind]}" == disposable_postgresql17 && "${o[target_kind]}" == "${e[target_kind]}" && "${e[target_id]}" =~ ^[a-z0-9][a-z0-9-]{7,63}$ && "${o[target_id]}" == "${e[target_id]}" && "${e[target_container_id]}" =~ ^[a-f0-9]{64}$ && "${o[target_container_id]}" == "${e[target_container_id]}" && "${e[target_sentinel_sha256]}" =~ ^[a-fA-F0-9]{64}$ && "${o[target_sentinel_sha256]}" == "${e[target_sentinel_sha256]}" ]] || fail "target sentinel evidence is invalid"
[[ "${e[target_database_name]}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ && "${e[target_server_version_num]}" =~ ^17[0-9]{4}$ && "${e[target_ssl_status]}" == on && "${e[target_ssl_session_status]}" == verified && "${o[target_database_name]}" == "${e[target_database_name]}" ]] || fail "target database identity evidence is invalid"
[[ "${e[target_host]}" == 127.0.0.1 && "${o[target_host]}" == "${e[target_host]}" && "${e[target_port]}" =~ ^[0-9]+$ && "${o[target_port]}" == "${e[target_port]}" && "${e[target_nonce_sha256]}" =~ ^[a-fA-F0-9]{64}$ && "${o[target_nonce_sha256]}" == "${e[target_nonce_sha256]}" && "${e[bootstrap_sql_sha256]}" == "$(sha256sum "$repo_root/ops/docker/postgres/init/001-bootstrap-roles.sql" | cut -d' ' -f1)" && "${o[bootstrap_sql_sha256]}" == "${e[bootstrap_sql_sha256]}" ]] || fail "target connection or canonical ACL binding is invalid"
[[ "${e[target_server_version_num]}" == "${o[target_server_version_num]}" && "${e[target_ssl_status]}" == "${o[target_ssl_status]}" && "${e[target_ssl_session_status]}" == "${o[target_ssl_session_status]}" && "${e[public_policy_count]}" == "${o[public_policy_count]}" && "${e[valorant_policy_count]}" == "${o[valorant_policy_count]}" && "${e[runtime_policy_status]}" == "${o[runtime_policy_status]}" && "${e[roles_nobypassrls_status]}" == "${o[roles_nobypassrls_status]}" && "${e[quest_read_write_probe_status]}" == "${o[quest_read_write_probe_status]}" && "${e[quest_write_probe_status]}" == "${o[quest_write_probe_status]}" && "${e[cross_schema_denial_status]}" == "${o[cross_schema_denial_status]}" ]] || fail "runtime security probe evidence is incomplete"
for key in target_ssl_session_status quest_read_probe_status runtime_policy_status roles_nobypassrls_status quest_read_write_probe_status quest_write_probe_status cross_schema_denial_status upload_cleanup_status; do [[ "${e[$key]}" == verified && "${o[$key]}" == verified ]] || fail "runtime security probe status is not the exact success value: $key"; done
[[ "${e[live_disposable_rehearsal_gate]}" == owner_deployment_host_evidence_required && "${o[live_disposable_rehearsal_gate]}" == owner_deployment_host_evidence_required && "$(rehearsal_live_gate_token)" == owner_deployment_host_evidence_required ]] || fail "live rehearsal gate is absent or not the exact owner/deployment-host contract token"
for key in quest_write_probe_session_user quest_write_probe_current_user quest_write_probe_application_name quest_write_probe_backend_pid quest_write_probe_ssl cross_schema_denial_session_user cross_schema_denial_current_user cross_schema_denial_application_name cross_schema_denial_backend_pid cross_schema_denial_ssl; do [[ "${e[$key]}" == "${o[$key]}" ]] || fail "runtime probe session identity does not match raw observations: $key"; done
[[ "${e[source_version_provenance]}" == operator_recorded && "${o[source_version_provenance]}" == operator_recorded && "${e[source_version_record_sha256]}" == "${o[source_version_record_sha256]}" && "${e[source_version_record_sha256]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "source provenance is not explicitly operator-recorded"
[[ "${e[format_version]}" == 1 && "${e[evidence_status]}" == complete && "${e[rehearsal_mode]}" == disposable && "${e[restore_status]}" == verified ]] || fail "evidence is not complete disposable runtime evidence"
[[ "${e[manifest_database_scope]}" == application_public_and_valorant_schemas && "${e[manifest_valorant_schema_included]}" == true ]] || fail "manifest scope is incomplete"
for key in quest_migration_ledger_before_status valorant_migration_ledger_before_status; do
  [[ "${e[$key]}" == absent && "${o[$key]}" == absent ]] || fail "pre-restore migration ledger status is not exactly absent: $key"
done
[[ "${e[checksum_status]}" == verified && "${e[decryption_status]}" == verified && "${e[archive_sha256]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "archive integrity evidence is incomplete"
[[ "${e[archive_name]}" =~ ^quest-production-[0-9]{8}T[0-9]{6}Z\.tar\.gz\.enc$ ]] || fail "archive name is not an expected production archive basename"
[[ "${e[source_postgres_major]}" =~ ^[0-9]+$ && "${e[source_postgres_major]}" -gt 0 ]] || fail "source major is invalid"
[[ "${e[target_postgres_major]}" == "${o[target_postgres_major]}" && "${e[source_postgres_major]}" == "${o[source_postgres_major]}" && "${e[client_psql_major]}" == "${o[client_psql_major]}" && "${e[client_pg_restore_major]}" == "${o[client_pg_restore_major]}" && "${e[client_pg_dump_major]}" == "${o[client_pg_dump_major]}" ]] || fail "summary versions do not match raw observations"
[[ "${e[manifest_database_scope]}" == "${o[manifest_scope]}" && "${e[manifest_valorant_schema_included]}" == "${o[manifest_valorant_schema_included]}" ]] || fail "summary manifest does not match raw observation"
for key in public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_ledger_before_status valorant_migration_ledger_before_status quest_migration_count valorant_migration_count public_upload_file_count public_upload_byte_count public_upload_checksum private_upload_file_count private_upload_byte_count private_upload_checksum quest_liveness_status quest_readiness_status quest_database_status valorant_health_status valorant_database_status valorant_ca_status freeze_mode writers_disabled mutation_rejection no_writer_admission failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback resource_cpu_seconds resource_peak_memory_kb resource_disk_bytes rpo_seconds rpo_decision rto_seconds rto_decision upload_checksum_scope upload_source_equivalence target_kind target_id target_container_id target_sentinel_sha256 target_container_disk_bytes_before target_container_disk_bytes_after target_database_size_bytes; do [[ "${e[$key]}" == "${o[$key]}" ]] || fail "summary does not match raw observation: $key"; done
for key in target_database_name target_nonce_sha256 target_nonce_after_sha256 quest_read_probe_count quest_read_probe_session_user quest_read_probe_current_user quest_read_probe_application_name quest_read_probe_backend_pid quest_read_probe_ssl target_docker_before_sha256 target_mapping_sha256 target_mapping_after_sha256 target_connection_before_sha256 target_docker_connection_before_sha256 target_docker_after_sha256 target_connection_after_sha256 target_docker_connection_after_sha256; do [[ "${e[$key]}" == "${o[$key]}" ]] || fail "summary does not match raw observation: $key"; done
for key in schema_counts_observations_sha256 policy_counts_observations_sha256 quest_write_probe_observations_sha256 cross_schema_denial_observations_sha256 target_session_tls_observations_sha256 upload_cleanup_observations_sha256 live_disposable_rehearsal_gate; do [[ "${e[$key]}" == "${o[$key]}" ]] || fail "summary does not match raw observation: $key"; done
for pair in "roles_status|roles_command_status" "memberships_status|memberships_command_status" "owners_status|owners_command_status" "grants_status|grants_command_status" "default_acl_status|default_acl_command_status" "rls_status|rls_command_status" "security_verify_status|security_verify_status" "extensions_inventory_sha256|extensions_inventory_sha256" "settings_inventory_sha256|settings_inventory_sha256" "security_verify_output_sha256|security_verify_output_sha256"; do left="${pair%%|*}"; right="${pair#*|}"; [[ "${e[$left]}" == "${o[$right]}" ]] || fail "summary status does not match raw observation: $left"; done
if [[ "${e[source_postgres_major]}" == 17 ]]; then [[ "${e[source_major_gate]}" == none ]] || fail "unexpected major-migration gate"; else [[ "${e[source_major_gate]}" == approved_logical_major_migration ]] || fail "source-major migration gate is missing"; fi
for key in client_psql_major client_pg_restore_major client_pg_dump_major; do [[ "${e[$key]}" == 17 ]] || fail "client is not PostgreSQL 17: $key"; done
[[ "${e[target_postgres_major]}" == 17 ]] || fail "target server is not PostgreSQL 17"
for key in public_policy_count valorant_policy_count; do [[ "${e[$key]}" =~ ^[0-9]+$ && "${e[$key]}" -gt 0 ]] || fail "runtime policy coverage is missing: $key"; done
for key in public_table_count valorant_table_count public_object_count valorant_object_count quest_migration_count valorant_migration_count rls_enabled_table_count rls_table_count; do [[ "${e[$key]}" =~ ^[0-9]+$ && "${e[$key]}" -gt 0 ]] || fail "non-zero runtime evidence is missing: $key"; done
for key in roles_status memberships_status owners_status grants_status default_acl_status security_verify_status extensions_status extensions_before_status settings_status settings_before_status rls_status quest_migration_ledger_status valorant_migration_ledger_status valorant_ca_status quest_read_probe_status; do [[ "${e[$key]}" == verified ]] || fail "status is not verified: $key"; done
for key in public_upload_file_count public_upload_byte_count private_upload_file_count private_upload_byte_count resource_peak_memory_kb resource_disk_bytes rpo_seconds rto_seconds extensions_count extensions_before_count quest_read_probe_count target_container_disk_bytes_before target_container_disk_bytes_after target_database_size_bytes target_port; do [[ "${e[$key]}" =~ ^[0-9]+$ ]] || fail "numeric evidence is malformed: $key"; done
[[ "${e[rpo_seconds]}" -gt 0 && "${e[rto_seconds]}" -gt 0 && "${e[resource_peak_memory_kb]}" -gt 0 && "${e[target_database_size_bytes]}" -gt 0 ]] || fail "RPO, RTO, or resource range is invalid"
[[ "${e[rpo_decision]}" == met || "${e[rpo_decision]}" == not_met ]] || fail "RPO decision is missing"
[[ "${e[upload_checksum_scope]}" == post_restore_tree && "${e[upload_source_equivalence]}" == verified:public,private ]] || fail "upload source equivalence is not proven for both roots"
for key in public_upload_checksum private_upload_checksum; do [[ "${e[$key]}" =~ ^[a-fA-F0-9]{64}$ ]] || fail "upload checksum is malformed: $key"; done
for key in quest_liveness_status quest_readiness_status valorant_health_status; do [[ "${e[$key]}" == ok ]] || fail "health status is not ok: $key"; done
[[ "${e[quest_database_status]}" == up && "${e[valorant_database_status]}" == up ]] || fail "database health is not up"
[[ "${e[freeze_mode]}" == validation && "${e[writers_disabled]}" == true && "${e[mutation_rejection]}" == verified && "${e[no_writer_admission]}" == verified ]] || fail "freeze evidence is incomplete"
for key in failure_injection_bad_checksum failure_injection_bad_decryption failure_injection_wrong_ca failure_injection_blocked_network failure_injection_failed_service_health failure_injection_attempted_mutation_callback; do [[ "${e[$key]}" == passed ]] || fail "failure injection is not passed: $key"; done
[[ "${e[resource_cpu_seconds]}" =~ ^[0-9]+([.][0-9]+)?$ ]] || fail "CPU resource evidence is malformed"
[[ "${e[rto_decision]}" == met || "${e[rto_decision]}" == not_met ]] || fail "RTO decision is missing"
for key in created_at_utc restore_start_utc restore_end_utc; do [[ "${e[$key]}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]] || fail "timestamp is malformed: $key"; date -u -d "${e[$key]}" +%s >/dev/null 2>&1 || fail "timestamp is invalid: $key"; done
now="$(date -u +%s)"; end="$(date -u -d "${e[restore_end_utc]}" +%s)"; age=$((now-end)); max_age="${REHEARSAL_EVIDENCE_MAX_AGE_SECONDS:-604800}"
[[ "$max_age" =~ ^[0-9]+$ && "$age" -ge 0 && "$age" -le "$max_age" ]] || fail "evidence is stale or from the future"
start="$(date -u -d "${e[restore_start_utc]}" +%s)"; [[ "$end" -ge "$start" && "${e[restore_duration_seconds]}" == $((end-start)) ]] || fail "timestamps and restore duration are inconsistent"
echo "Restore rehearsal evidence verified: complete disposable PostgreSQL 17 two-schema evidence."
