#!/usr/bin/env bash
set -euo pipefail
umask 077
root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)"; rehearsal="$root/ops/rehearsal/postgres17-restore-rehearsal.sh"; verify="$root/ops/rehearsal/verify-rehearsal-evidence.sh"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/quest-rehearsal-test.XXXXXXXX")"; mode_tmp="${TMPDIR:-/tmp}/quest-rehearsal-mode.$$"; (umask 000; mkdir "$mode_tmp"); trap 'rm -rf -- "$tmp" "$mode_tmp"' EXIT
archive_scope_binding="$(grep -F 'archive_scope="$(manifest_value database_scope)"' "$rehearsal" 2>/dev/null || true)"
[[ -n "$archive_scope_binding" ]] || { echo "FAIL: archive manifest scope must be bound to a distinct variable" >&2; exit 1; }
grant_scope_loop="$(grep -F "while IFS='|' read -r kind grant_scope role privilege granted;" "$rehearsal" 2>/dev/null || true)"
[[ -n "$grant_scope_loop" ]] || { echo "FAIL: grant loop must not overwrite archive scope" >&2; exit 1; }
raw_scope_emission="$(grep -F "'manifest_scope=%s" "$rehearsal" 2>/dev/null || true)"
[[ "$raw_scope_emission" == *'"$archive_scope"'* ]] || { echo "FAIL: raw observations must emit the preserved archive scope" >&2; exit 1; }
summary_scope_emission="$(grep -F 'manifest_database_scope=%s' "$rehearsal" 2>/dev/null || true)"
[[ "$summary_scope_emission" == *'"$archive_scope"'* ]] || { echo "FAIL: summary must emit the preserved archive scope" >&2; exit 1; }
for restore_flag in --no-owner --no-acl --single-transaction --exit-on-error; do
  grep -F -- "$restore_flag" "$root/ops/restore-production-backup.sh" >/dev/null || { echo "FAIL: restore primitive is missing $restore_flag" >&2; exit 1; }
done
grep -F 'part" != ..' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal paths must reject traversal components" >&2; exit 1; }
grep -F 'REHEARSAL_RPO_SECONDS' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must require an approved RPO" >&2; exit 1; }
grep -F 'quest_migration_ledger_before_status' "$verify" >/dev/null || { echo "FAIL: verifier must require pre-restore ledger evidence" >&2; exit 1; }
role_query="$(grep -F 'psql_query "$scratch/roles"' "$rehearsal" 2>/dev/null || true)"; for attribute in rolcanlogin rolinherit rolsuper rolcreatedb rolcreaterole rolreplication rolbypassrls; do [[ "$role_query" == *"CASE WHEN $attribute THEN 't' ELSE 'f' END"* ]] || { echo "FAIL: role query does not emit canonical t/f for $attribute" >&2; exit 1; }; done
[[ "$role_query" == *"ORDER BY rolname"* ]] || { echo "FAIL: role inventory ordering changed" >&2; exit 1; }
membership_query="$(grep -F 'psql_query "$scratch/memberships"' "$rehearsal" 2>/dev/null || true)"
[[ "$membership_query" == *'SELECT count(*) FROM'* ]] || { echo "FAIL: membership query must emit an explicit count" >&2; exit 1; }
for role in quest_migrator quest_runtime val_migrator val_runtime; do [[ "$membership_query" == *"'$role'"* ]] || { echo "FAIL: membership query is not restricted to the four database roles" >&2; exit 1; }; done
[[ "$membership_query" == *"WHERE granted.rolname IN ('quest_migrator','quest_runtime','val_migrator','val_runtime') OR member.rolname IN ('quest_migrator','quest_runtime','val_migrator','val_runtime')"* ]] || { echo "FAIL: membership query role restriction changed" >&2; exit 1; }
membership_count_validation="$(grep -F 'membership_count="$(tr -d '\''[:space:]'\'' < "$scratch/memberships")"' "$rehearsal" 2>/dev/null || true)"
[[ "$membership_count_validation" == *'[[ "$membership_count" == 0 ]]'* ]] || { echo "FAIL: membership count must validate an explicit zero" >&2; exit 1; }
for aggregate_query in "$(grep -F 'psql_query "$scratch/grants-status"' "$rehearsal" 2>/dev/null || true)" "$(grep -F 'psql_query "$scratch/grant-aggregate"' "$rehearsal" 2>/dev/null || true)"; do
  [[ "$aggregate_query" == *"WHERE n.nspname='public' AND c.relkind='S'), true)"* && "$aggregate_query" == *"WHERE n.nspname='valorant' AND c.relkind='S'), true)"* ]] || { echo "FAIL: empty sequence aggregates must default to true" >&2; exit 1; }
  [[ "$aggregate_query" == *"WHERE n.nspname='public' AND c.relkind IN ('r','p','f')), false)"* && "$aggregate_query" == *"WHERE n.nspname='valorant' AND c.relkind IN ('r','p','f')), false)"* ]] || { echo "FAIL: empty table aggregates must default to false" >&2; exit 1; }
done
grant_inventory_query="$(grep -F 'psql_query "$scratch/grants"' "$rehearsal" 2>/dev/null || true)"
for privilege in \
  "has_schema_privilege('quest_migrator','public','USAGE')" \
  "has_schema_privilege('quest_migrator','public','CREATE')" \
  "has_schema_privilege('quest_runtime','public','USAGE')" \
  "has_schema_privilege('val_migrator','valorant','USAGE')" \
  "has_schema_privilege('val_migrator','valorant','CREATE')" \
  "has_schema_privilege('val_runtime','valorant','USAGE')"; do
  [[ "$grant_inventory_query" == *"CASE WHEN $privilege THEN 't' ELSE 'f' END"* ]] || { echo "FAIL: detailed grant inventory does not emit canonical t/f for $privilege" >&2; exit 1; }
done
for denied_privilege in \
  "has_schema_privilege('quest_runtime','valorant','USAGE')" \
  "has_schema_privilege('val_runtime','public','USAGE')"; do
  [[ "$grant_inventory_query" == *"CASE WHEN NOT $denied_privilege THEN 't' ELSE 'f' END"* ]] || { echo "FAIL: denied grant inventory does not emit canonical t/f for $denied_privilege" >&2; exit 1; }
done
grant_aggregate_query="$(grep -F 'psql_query "$scratch/grant-aggregate"' "$rehearsal" 2>/dev/null || true)"
for aggregate_prefix in \
  'table|public|quest_runtime|all' \
  'table|valorant|val_runtime|all' \
  'sequence|public|quest_runtime|usage_select' \
  'sequence|valorant|val_runtime|usage_select'; do
  [[ "$grant_aggregate_query" == *"SELECT '$aggregate_prefix|' || CASE WHEN COALESCE((SELECT bool_and("* ]] || { echo "FAIL: grant aggregate does not emit canonical t/f for $aggregate_prefix" >&2; exit 1; }
done
[[ "$(grep -o "THEN 't' ELSE 'f' END" <<< "$grant_aggregate_query" | wc -l | tr -d ' ')" == 4 ]] || { echo "FAIL: grant aggregate must canonicalize all four boolean fields" >&2; exit 1; }
acl_query="$(grep -F 'psql_query "$scratch/acl"' "$rehearsal" 2>/dev/null || true)"
[[ "$acl_query" == *"d.defaclobjtype::text"* ]] || { echo "FAIL: default ACL inventory must cast defaclobjtype to text" >&2; exit 1; }
[[ "$acl_query" == *"COALESCE(array_to_string(d.defaclacl,','),'')"* && "$acl_query" == *"ORDER BY r.rolname,n.nspname,d.defaclobjtype"* ]] || { echo "FAIL: default ACL inventory behavior changed" >&2; exit 1; }
grep -F 'LC_ALL=C sort "$scratch/acl"' "$rehearsal" >/dev/null || { echo "FAIL: producer must normalize the ACL inventory deterministically" >&2; exit 1; }
grep -F 'rehearsal_canonical_acl_rows | LC_ALL=C sort' "$rehearsal" >/dev/null || { echo "FAIL: producer must normalize the canonical ACL contract deterministically" >&2; exit 1; }
grep -F 'observed_acl="$(LC_ALL=C sort "$dir/rehearsal-acl.tsv")"' "$verify" >/dev/null || { echo "FAIL: verifier must normalize the ACL inventory deterministically" >&2; exit 1; }
grep -F 'canonical_acl="$(rehearsal_canonical_acl_rows | LC_ALL=C sort)"' "$verify" >/dev/null || { echo "FAIL: verifier must normalize the canonical ACL contract deterministically" >&2; exit 1; }
rls_policy_check="$(grep -F 'VALORANT table lacks its exact val_runtime RLS policy' "$rehearsal" 2>/dev/null || true)"
[[ "$rls_policy_check" == *'"$command" == '\''ALL'\'''* ]] || { echo "FAIL: VALORANT RLS policy command must use canonical ALL" >&2; exit 1; }
extension_count_computation="$(grep -F 'extensions_count="$(wc -l < "$scratch/ext"' "$rehearsal" 2>/dev/null || true)"
[[ -n "$extension_count_computation" ]] || { echo "FAIL: extension count must be computed from the inventory" >&2; exit 1; }
summary_extension_count="$(grep -F 'extensions_count=%s' "$rehearsal" 2>/dev/null || true)"
[[ "$summary_extension_count" == *'"$extensions_count"'* ]] || { echo "FAIL: summary must emit the computed extension count" >&2; exit 1; }
grep -F 'DIRECT_URL does not match the inspected container port mapping' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must bind recovery URL endpoint to container mapping" >&2; exit 1; }
grep -F 'QUEST_RUNTIME_DATABASE_URL is required and unsafe' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must require a least-privileged runtime URL" >&2; exit 1; }
grep -F 'RECOVERY_ADMIN_URL' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must use the protected recovery URL contract" >&2; exit 1; }
! grep -F 'SET ROLE' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must not use a contradictory SET ROLE path" >&2; exit 1; }
grep -F 'pg_stat_activity' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must independently inspect target connection binding" >&2; exit 1; }
grep -F "current_database()" "$rehearsal" | grep -F "current_setting('server_version_num')" | grep -F "pg_stat_ssl" >/dev/null || { echo "FAIL: rehearsal must record session-level target database TLS" >&2; exit 1; }
grep -F 'VERBOSITY=verbose' "$rehearsal" >/dev/null && ! grep -F 'VERBOSITY=sqlstate' "$rehearsal" >/dev/null || { echo "FAIL: denial probe must retain SQLSTATE and permission-denied text" >&2; exit 1; }
! grep -F 'psql -X -q -A -t -F' "$rehearsal" >/dev/null || { echo "FAIL: runtime write probe must not suppress PostgreSQL transaction command-status rows" >&2; exit 1; }
grep -F "tablename NOT IN ('_prisma_migrations','_migration_ledger')" "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must count runtime policies excluding migration ledgers" >&2; exit 1; }
grep -F 'roles_nobypassrls_status' "$rehearsal" "$verify" >/dev/null || { echo "FAIL: rehearsal evidence must explicitly prove NOBYPASSRLS" >&2; exit 1; }
grep -F 'quest-write-probe' "$rehearsal" >/dev/null && grep -F 'quest_write_probe_status' "$rehearsal" "$verify" >/dev/null || { echo "FAIL: rehearsal must run and record a runtime write probe" >&2; exit 1; }
grep -F 'cross-schema-denial' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must prove cross-schema runtime denial" >&2; exit 1; }
grep -F 'rehearsal_live_gate_token' "$root/ops/rehearsal/rehearsal-contract.sh" >/dev/null && grep -F 'owner_deployment_host_evidence_required' "$verify" >/dev/null || { echo "FAIL: live rehearsal gate must require the exact contract token" >&2; exit 1; }
grep -Eq 'postgres:17.*sha256:' "$rehearsal" >/dev/null || { echo "FAIL: rehearsal must require an immutable PostgreSQL 17 image" >&2; exit 1; }
grep -Eq '\^postgres:17-bookworm@sha256:\[0-9a-f\]\{64\}\$' "$rehearsal" >/dev/null || { echo "FAIL: producer image allowlist is not the documented PostgreSQL 17 Bookworm digest" >&2; exit 1; }
grep -Eq '\^postgres:17-bookworm@sha256:\[0-9a-f\]\{64\}\$' "$verify" >/dev/null || { echo "FAIL: verifier image allowlist does not match producer" >&2; exit 1; }
! grep -Eq "server_version.*PostgreSQL_17" "$rehearsal" "$verify" || { echo "FAIL: server_version contract still uses fabricated PostgreSQL_17 text" >&2; exit 1; }
mkdir -p "$tmp/bin" "$tmp/evidence" "$tmp/ca"; chmod 700 "$tmp" "$tmp/evidence" "$tmp/ca"
printf 'fixture identity\n' > "$tmp/identity"; printf 'fixture ca\n' > "$tmp/ca/ca.crt"; printf 'fixture recovery cert\n' > "$tmp/recovery-client.crt"; printf 'fixture recovery key\n' > "$tmp/recovery-client.key"; chmod 600 "$tmp/identity" "$tmp/ca/ca.crt" "$tmp/recovery-client.crt" "$tmp/recovery-client.key"
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$tmp/prerequisite-signing-private.pem" >/dev/null 2>&1; chmod 600 "$tmp/prerequisite-signing-private.pem"
source "$root/ops/rehearsal/rehearsal-contract.sh"
[[ "$(rehearsal_runtime_role public)" == quest_runtime && "$(rehearsal_runtime_role valorant)" == val_runtime && "$(rehearsal_runtime_policy_name public users)" == users_runtime_all ]] || { echo 'FAIL: shared runtime policy contract changed' >&2; exit 1; }
printf '#!/usr/bin/env bash\nexit 0\n' > "$tmp/safe-hook"; chmod 700 "$tmp/safe-hook"
rehearsal_safe_hook_path "$tmp/safe-hook" || { echo 'FAIL: shared safe hook path contract rejected a valid hook' >&2; exit 1; }
printf '#!/usr/bin/env bash\nexit 0\n' > "$tmp/unsafe hook"; chmod 700 "$tmp/unsafe hook"
! rehearsal_safe_hook_path "$tmp/unsafe hook" || { echo 'FAIL: shared hook path contract accepted whitespace' >&2; exit 1; }
printf '#!/usr/bin/env bash\nexit 0\n' > "$tmp/production-hook"; chmod 700 "$tmp/production-hook"
! rehearsal_safe_hook_path "$tmp/production-hook" || { echo 'FAIL: shared hook path contract accepted a production-looking path' >&2; exit 1; }
grep -F '[[ ! -L "$current" ]]' "$root/ops/rehearsal/rehearsal-contract.sh" >/dev/null || { echo 'FAIL: shared hook path contract does not reject symlink ancestors' >&2; exit 1; }
for endpoint in 'bad_checksum|archive-checksum' 'bad_decryption|archive-decryption' 'wrong_ca|valorant-health' 'blocked_network|valorant-health' 'failed_service_health|valorant-health' 'attempted_mutation_callback|quest-api'; do IFS='|' read -r injection endpoint_id <<< "$endpoint"; [[ "$(rehearsal_failure_endpoint_id "$injection")" == "$endpoint_id" ]] || { echo "FAIL: endpoint mapping changed for $injection" >&2; exit 1; }; done
grep -F 'source "$contract"' "$rehearsal" >/dev/null || { echo 'FAIL: producer does not load the shared rehearsal contract' >&2; exit 1; }
grep -F 'source "$contract"' "$verify" >/dev/null || { echo 'FAIL: verifier does not load the shared rehearsal contract' >&2; exit 1; }
printf 'source_major=17\nsource_version=PostgreSQL_17.4\nprovenance=operator_recorded\n' > "$tmp/source-version.env"; chmod 600 "$tmp/source-version.env"
printf 'target_kind=disposable_postgresql17\ntarget_id=quest-fixture-20260827\ncontainer_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\npublic_root=%s\nprivate_root=%s\n' "$tmp/wrapper-parent/public" "$tmp/wrapper-parent/private" > "$tmp/target-sentinel.env"; chmod 600 "$tmp/target-sentinel.env"
printf 'not an archive\n' > "$tmp/quest-production-20260827T000000Z.tar.gz.enc"; cat > "$tmp/recovery.env" <<EOF
RECOVERY_ADMIN_URL=postgresql://quest_recovery_admin:fixture@127.0.0.1:55432/quest_restore
RECOVERY_CLIENT_CERT_FILE=$tmp/recovery-client.crt
RECOVERY_CLIENT_KEY_FILE=$tmp/recovery-client.key
QUEST_RUNTIME_DATABASE_URL=postgresql://quest_runtime:fixture@127.0.0.1:55432/quest_restore
UPLOAD_ROOT=$tmp/wrapper-parent/public
PRIVATE_UPLOAD_ROOT=$tmp/wrapper-parent/private
BACKUP_AGE_IDENTITY_FILE=$tmp/identity
EOF
chmod 600 "$tmp/recovery.env"; printf '0%.0s' {1..64} > "$tmp/quest-production-20260827T000000Z.tar.gz.enc.sha256"; printf '  %s\n' "$(basename "$tmp/quest-production-20260827T000000Z.tar.gz.enc")" >> "$tmp/quest-production-20260827T000000Z.tar.gz.enc.sha256"
for command in age psql pg_restore pg_dump rsync; do printf '%s\n' '#!/usr/bin/env bash' 'if [[ "$1" == --version ]]; then echo "fixture (PostgreSQL) 17.4"; exit 0; fi' '[[ "$(basename "$0")" == age ]] && exit 1' 'exit 0' > "$tmp/bin/$command"; chmod 700 "$tmp/bin/$command"; done
real_stat="$(command -v stat)"; export REAL_STAT="$real_stat"
cat > "$tmp/bin/stat" <<'EOF'
#!/usr/bin/env bash
case "$*" in
  *world-readable-target-sentinel.env*) printf '644\n'; exit 0 ;;
  *group-readable-target-sentinel.env*) printf '640\n'; exit 0 ;;
esac
exec "${REAL_STAT:?}" "$@"
EOF
chmod 700 "$tmp/bin/stat"
refused() { local label="$1" expected="$2" stem stdout stderr; shift 2; stem="${label//[^A-Za-z0-9_]/_}"; stdout="$tmp/refused-${stem}.stdout"; stderr="$tmp/refused-${stem}.stderr"; if "$@" >"$stdout" 2>"$stderr"; then echo "FAIL: $label accepted" >&2; exit 1; fi; [[ "$(tr -d '\r' < "$stderr")" == "Restore rehearsal refused: $expected" ]] || { echo "FAIL: $label returned an unexpected refusal diagnostic" >&2; printf 'expected: %s\nactual: %s\n' "Restore rehearsal refused: $expected" "$(tr -d '\r' < "$stderr")" >&2; exit 1; }; echo "ok: $label"; }
evidence_refused() { local label="$1" expected="$2" stem stdout stderr; shift 2; stem="${label//[^A-Za-z0-9_]/_}"; stdout="$tmp/refused-${stem}.stdout"; stderr="$tmp/refused-${stem}.stderr"; if "$@" >"$stdout" 2>"$stderr"; then echo "FAIL: $label accepted" >&2; exit 1; fi; [[ "$(tr -d '\r' < "$stderr")" == "Restore rehearsal evidence refused: $expected" ]] || { echo "FAIL: $label returned an unexpected refusal diagnostic" >&2; printf 'expected: %s\nactual: %s\n' "Restore rehearsal evidence refused: $expected" "$(tr -d '\r' < "$stderr")" >&2; exit 1; }; echo "ok: $label"; }
refused "missing confirmation" "explicit disposable-target confirmation is required" env REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
sed 's#127.0.0.1:55432#prod-db.example:5432#' "$tmp/recovery.env" > "$tmp/production.env"; chmod 600 "$tmp/production.env"
refused "production-looking target" "database host looks like production" env REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/production.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/target-sentinel.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
refused "missing target sentinel" "REHEARSAL_TARGET_SENTINEL_FILE must be an absolute regular file" env REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
umask 000; printf 'target_kind=disposable_postgresql17\ntarget_id=quest-fixture-20260827\ncontainer_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\npublic_root=%s\nprivate_root=%s\n' "$tmp/wrapper-parent/public" "$tmp/wrapper-parent/private" > "$mode_tmp/world-readable-target-sentinel.env"; chmod 644 "$mode_tmp/world-readable-target-sentinel.env"; umask 077; refused "world-readable target sentinel" "target sentinel is not private" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$mode_tmp/world-readable-target-sentinel.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
umask 000; printf 'target_kind=disposable_postgresql17\ntarget_id=quest-fixture-20260827\ncontainer_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\npublic_root=%s\nprivate_root=%s\n' "$tmp/wrapper-parent/public" "$tmp/wrapper-parent/private" > "$mode_tmp/group-readable-target-sentinel.env"; chmod 640 "$mode_tmp/group-readable-target-sentinel.env"; umask 077; refused "group-readable target sentinel" "target sentinel is not private" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$mode_tmp/group-readable-target-sentinel.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
mkdir -p "$tmp/existing-parent/public" "$tmp/existing-parent/private"; cp "$tmp/recovery.env" "$tmp/existing.env"; sed -i "s#$tmp/wrapper-parent/public#$tmp/existing-parent/public#; s#$tmp/wrapper-parent/private#$tmp/existing-parent/private#" "$tmp/existing.env"; cp "$tmp/target-sentinel.env" "$tmp/existing-target.env"; sed -i "s#$tmp/wrapper-parent/public#$tmp/existing-parent/public#; s#$tmp/wrapper-parent/private#$tmp/existing-parent/private#" "$tmp/existing-target.env"; chmod 600 "$tmp/existing.env" "$tmp/existing-target.env"; refused "existing generic upload parent" "upload parent must not already exist" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/existing.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/existing-target.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
cat > "$tmp/bin/docker" <<'EOF'
#!/usr/bin/env bash
if [[ "$*" == *NetworkSettings.Ports* ]]; then printf '%s\n' '{"5432/tcp":[{"HostIp":"127.0.0.1","HostPort":"55555"}]}'
else printf '%s\n' 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|/quest-rehearsal-fixture|true|postgres:17-bookworm@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|0'; fi
EOF
chmod 700 "$tmp/bin/docker"; mkdir -p "$tmp/mismatch-payload/public" "$tmp/mismatch-payload/private"; printf '%s\n' 'database_scope=application_public_and_valorant_schemas' 'valorant_schema_included=true' 'public_upload_root=public' 'private_upload_root=private' > "$tmp/mismatch-payload/manifest.txt"; : > "$tmp/mismatch-payload/database.dump"
cat > "$tmp/bin/age" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == --version ]]; then echo 'fixture age 1.0'; exit 0; fi
tar --create --gzip --file="$5" -C "${MISMATCH_PAYLOAD_DIR:?}" manifest.txt database.dump public private
EOF
chmod 700 "$tmp/bin/age"; printf '%s  %s\n' "$(sha256sum "$tmp/quest-production-20260827T000000Z.tar.gz.enc" | cut -d' ' -f1)" "$(basename "$tmp/quest-production-20260827T000000Z.tar.gz.enc")" > "$tmp/quest-production-20260827T000000Z.tar.gz.enc.sha256"
cp "$tmp/recovery.env" "$tmp/mismatch.env"; sed -i "s#$tmp/wrapper-parent/public#$tmp/mismatch-parent/public#; s#$tmp/wrapper-parent/private#$tmp/mismatch-parent/private#" "$tmp/mismatch.env"; cp "$tmp/target-sentinel.env" "$tmp/mismatch-target.env"; sed -i "s#$tmp/wrapper-parent/public#$tmp/mismatch-parent/public#; s#$tmp/wrapper-parent/private#$tmp/mismatch-parent/private#" "$tmp/mismatch-target.env"; chmod 600 "$tmp/mismatch.env" "$tmp/mismatch-target.env"; refused "URL/container port mismatch" "DIRECT_URL does not match the inspected container port mapping" env PATH="$tmp/bin:$PATH" MISMATCH_PAYLOAD_DIR="$tmp/mismatch-payload" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/mismatch.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/mismatch-target.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
printf '%s\n' '#!/usr/bin/env bash' 'if [[ "$1" == --version ]]; then echo "fixture (PostgreSQL) 17.4"; exit 0; fi' '[[ "$(basename "$0")" == age ]] && exit 1' 'exit 0' > "$tmp/bin/age"; chmod 700 "$tmp/bin/age"
cp "$tmp/recovery.env" "$tmp/nested.env"; sed -i "s#UPLOAD_ROOT=.*#UPLOAD_ROOT=$tmp/public#; s#PRIVATE_UPLOAD_ROOT=.*#PRIVATE_UPLOAD_ROOT=$tmp/public/nested#" "$tmp/nested.env"; chmod 600 "$tmp/nested.env"
cp "$tmp/target-sentinel.env" "$tmp/nested-target.env"; sed -i "s#$tmp/wrapper-parent/public#$tmp/public#; s#$tmp/wrapper-parent/private#$tmp/public/nested#" "$tmp/nested-target.env"; chmod 600 "$tmp/nested-target.env"
refused "nested roots" "upload roots must not be nested" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/nested.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/nested-target.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
cp "$tmp/recovery.env" "$tmp/traversal.env"; sed -i "s#PRIVATE_UPLOAD_ROOT=.*#PRIVATE_UPLOAD_ROOT=$tmp/private/../private-target#" "$tmp/traversal.env"; chmod 600 "$tmp/traversal.env"
cp "$tmp/target-sentinel.env" "$tmp/traversal-target.env"; sed -i "s#$tmp/wrapper-parent/private#$tmp/private/../private-target#" "$tmp/traversal-target.env"; chmod 600 "$tmp/traversal-target.env"
refused "traversal target" "PRIVATE_UPLOAD_ROOT contains a traversal component" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/traversal.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/traversal-target.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
printf '%s  %s\n' "$(printf '0%.0s' {1..64})" "$(basename "$tmp/quest-production-20260827T000000Z.tar.gz.enc")" > "$tmp/quest-production-20260827T000000Z.tar.gz.enc.sha256"
refused "bad checksum" "archive checksum verification failed" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/target-sentinel.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
printf '%s  %s\n' "$(sha256sum "$tmp/quest-production-20260827T000000Z.tar.gz.enc" | cut -d' ' -f1)" "$(basename "$tmp/quest-production-20260827T000000Z.tar.gz.enc")" > "$tmp/quest-production-20260827T000000Z.tar.gz.enc.sha256"
refused "decryption failure" "age decryption failed" env PATH="$tmp/bin:$PATH" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/target-sentinel.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/prerequisite-signing-private.pem" POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc"
if command -v openssl >/dev/null 2>&1; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$tmp/wrapper-signing-private.pem" >/dev/null 2>&1; openssl pkey -in "$tmp/wrapper-signing-private.pem" -pubout -out "$tmp/wrapper-signing-public.pem" >/dev/null 2>&1; chmod 600 "$tmp/wrapper-signing-private.pem" "$tmp/wrapper-signing-public.pem"
  mkdir -p "$tmp/wrapper-payload/public/poster-images" "$tmp/wrapper-payload/private/event-album-originals"; printf '%s\n' 'database_scope=application_public_and_valorant_schemas' 'valorant_schema_included=true' 'public_upload_root=public' 'private_upload_root=private' 'public_event_album_preview_root=public/poster-images' 'private_event_album_original_root=private/event-album-originals' > "$tmp/wrapper-payload/manifest.txt"; : > "$tmp/wrapper-payload/database.dump"; printf public > "$tmp/wrapper-payload/public/poster-images/file"; printf private > "$tmp/wrapper-payload/private/event-album-originals/file"
  cat > "$tmp/bin/age" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == --version ]]; then echo 'fixture age 1.0'; exit 0; fi
tar --create --gzip --file="$5" -C "${FIXTURE_PAYLOAD_DIR:?}" manifest.txt database.dump public private
EOF
  cat > "$tmp/bin/psql" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == --version ]]; then echo 'fixture (PostgreSQL) 17.4'; exit 0; fi
for arg in "$@"; do [[ "$arg" == -f || "$arg" == --file=* ]] && exit 0; done
has_c=0; quiet=0; sql=''; for ((i=1; i<=$#; i++)); do arg="${!i}"; if [[ "$arg" == -c || "$arg" == -tAc ]]; then has_c=1; j=$((i+1)); sql="${!j}"; fi; [[ "$arg" == -q ]] && quiet=1; done
if (( ! has_c )); then printf '%s|quest_restore|quest_recovery_admin|quest_recovery_admin|5432|12345\n' "${PGAPPNAME:?}" >> "${TARGET_BINDING_MARKER:?}"; printf '%s\n' "${PGAPPNAME:?}|quest_restore|quest_recovery_admin|quest_recovery_admin|5432|12345" "quest_restore|170004|on|${PGAPPNAME:?}|12345"; sleep 5; exit 0; fi
if [[ "$sql" == *defaclnamespace* && "$sql" == *IS\ NULL* ]]; then printf '%s\n' 'quest_migrator|<global>|T|quest_migrator=U/quest_migrator' 'quest_migrator|<global>|f|quest_migrator=X/quest_migrator' 'val_migrator|<global>|T|val_migrator=U/val_migrator' 'val_migrator|<global>|f|val_migrator=X/val_migrator'; exit 0; fi
if [[ "$sql" == *defaclobjtype* ]]; then printf '%s\n' 'quest_migrator|public|S|quest_runtime=rwU/quest_migrator' 'quest_migrator|public|T|quest_migrator=U/quest_migrator' 'quest_migrator|public|f|quest_migrator=X/quest_migrator' 'quest_migrator|public|r|quest_runtime=arwd/quest_migrator' 'val_migrator|valorant|S|val_runtime=rwU/val_migrator' 'val_migrator|valorant|T|val_migrator=U/val_migrator' 'val_migrator|valorant|f|val_migrator=X/val_migrator' 'val_migrator|valorant|r|val_runtime=arwd/val_migrator'; exit 0; fi
if [[ "$sql" == *schemaname*count* ]]; then printf 'public|2\nvalorant|2\n'; exit 0; fi
if [[ "$sql" == *pg_policies* ]]; then printf 'public\tusers\tt\tusers_runtime_all\tquest_runtime\tALL\ttrue\ttrue\npublic\tevents\tt\tevents_runtime_all\tquest_runtime\tALL\ttrue\ttrue\nvalorant\tmatches\tt\tmatches_runtime_all\tval_runtime\tALL\ttrue\ttrue\nvalorant\tteams\tt\tteams_runtime_all\tval_runtime\tALL\ttrue\ttrue\nvalorant\t_migration_ledger\tf\t<none>\t<none>\t<none>\t<none>\t<none>\n'; exit 0; fi
case "$sql" in
  *FROM\ valorant.*) printf 'quest_runtime|quest_runtime|cross_schema_denied|%s|12347|on\n' "${PGAPPNAME:?}"; printf '%s\n' 'ERROR: 42501: permission denied for schema valorant' >&2; exit 1 ;;
  *INSERT\ INTO\ public.\"users\"*) if (( quiet )); then printf '%s\n' "quest_runtime|quest_runtime|write_verified|${PGAPPNAME:?}|12346|on"; else printf '%s\n' 'BEGIN' 'INSERT 0 1' "quest_runtime|quest_runtime|write_verified|${PGAPPNAME:?}|12346|on" 'ROLLBACK'; fi ;;
  *current_database*session_user*) printf 'quest_restore|170004|on|quest_recovery_admin|172.18.0.2|5432|quest-restore-target\n' ;;
  *pg_stat_ssl*public.\"users\"*) printf 'quest_runtime|quest_runtime|2|%s|12345|on\n' "${PGAPPNAME:?}" ;;
  *pg_stat_ssl*) printf 'quest_restore|170004|on|%s|12345\n' "${PGAPPNAME:?}" ;;
  *current_database*ssl*) printf 'quest_restore|170004|on\n' ;;
  *current_setting*session_user*) printf 'quest_restore|170004|on|quest_recovery_admin|172.18.0.2|5432|quest-restore-target\n' ;;
  *quest.rehearsal_target_id*) printf 'quest-fixture-20260827\n' ;;
  *pg_settings*) printf '%s\n' 'server_version|17.4_Debian_17.4-1.pgdg' 'server_version_num|170004' 'ssl|on' 'ssl_min_protocol_version|TLSv1.2' 'row_security|on' 'default_transaction_read_only|off' 'listen_addresses|*' ;;
  *server_version_num*) printf '170004\n' ;;
  *extname*) printf 'plpgsql|1.0\n' ;;
  *to_jsonb*) printf '20260827_init|complete\n' ;;
  *to_regclass*) printf 'absent\n' ;;
  *count*FILTER*) printf 'public|2|3\nvalorant|2|3\n' ;;
  *EXISTS*pg_roles*) printf 'verified\n' ;;
  *count*pg_default_acl*) printf 'verified\n' ;;
  *rolcanlogin*) printf '%s\n' 'quest_migrator|t|f|f|f|f|f|f' 'quest_runtime|t|f|f|f|f|f|f' 'val_migrator|t|f|f|f|f|f|f' 'val_runtime|t|f|f|f|f|f|f' ;;
  *pg_auth_members*) printf '0\n' ;;
  *FROM\ pg_namespace\ n\ JOIN\ pg_roles*) printf '%s\n' 'public|quest_migrator' 'valorant|val_migrator' ;;
  *SELECT*schema\|public*) printf '%s\n' 'schema|public|quest_migrator|USAGE|t' 'schema|public|quest_migrator|CREATE|t' 'schema|public|quest_runtime|USAGE|t' 'schema|valorant|val_migrator|USAGE|t' 'schema|valorant|val_migrator|CREATE|t' 'schema|valorant|val_runtime|USAGE|t' 'schema|valorant|quest_runtime|USAGE_DENIED|t' 'schema|public|val_runtime|USAGE_DENIED|t' ;;
  *SELECT*table\|public*) printf '%s\n' 'table|public|quest_runtime|all|t' 'table|valorant|val_runtime|all|t' 'sequence|public|quest_runtime|usage_select|t' 'sequence|valorant|val_runtime|usage_select|t' ;;
  *x.grantee=0*) printf 'verified\n' ;;
  *IS\ NULL*) printf '%s\n' 'quest_migrator|<global>|f|quest_migrator=X/quest_migrator' 'quest_migrator|<global>|T|quest_migrator=U/quest_migrator' 'val_migrator|<global>|f|val_migrator=X/val_migrator' 'val_migrator|<global>|T|val_migrator=U/val_migrator' ;;
  *defaclobjtype*) printf '%s\n' 'quest_migrator|public|r|quest_runtime=arwd/quest_migrator' 'quest_migrator|public|S|quest_runtime=rwU/quest_migrator' 'quest_migrator|public|f|quest_migrator=X/quest_migrator' 'quest_migrator|public|T|quest_migrator=U/quest_migrator' 'val_migrator|valorant|r|val_runtime=arwd/val_migrator' 'val_migrator|valorant|S|val_runtime=rwU/val_migrator' 'val_migrator|valorant|f|val_migrator=X/val_migrator' 'val_migrator|valorant|T|val_migrator=U/val_migrator' ;;
  *pg_database_size*) printf '4096\n' ;;
  *INSERT\ INTO\ public.\"users\"*) if (( quiet )); then printf '%s\n' "quest_runtime|quest_runtime|write_verified|${PGAPPNAME:?}|12346|on"; else printf '%s\n' 'BEGIN' 'INSERT 0 1' "quest_runtime|quest_runtime|write_verified|${PGAPPNAME:?}|12346|on" 'ROLLBACK'; fi ;;
  *FROM\ valorant.*) printf 'quest_runtime|quest_runtime|cross_schema_denied|%s|12347|on\n' "${PGAPPNAME:?}"; printf '%s\n' 'ERROR: 42501: permission denied for schema valorant' >&2; exit 1 ;;
  *public.\"users\"*) printf 'quest_runtime|quest_runtime|2\n' ;;
  *schemaname*count*) printf 'public|2\nvalorant|2\n' ;;
  *pg_policies*) printf 'public\tusers\tt\tusers_runtime_all\tquest_runtime\tALL\ttrue\ttrue\nvalorant\tmatches\tt\tmatches_runtime_all\tval_runtime\tALL\ttrue\ttrue\nvalorant\t_migration_ledger\tf\t<none>\t<none>\t<none>\t<none>\t<none>\n' ;;
  *has_schema_privilege*) printf 'verified\n' ;;
  *count*) printf '0\n' ;;
esac
EOF
  cat > "$tmp/bin/pg_restore" <<'EOF'
#!/usr/bin/env bash
if [[ "$1" == --version ]]; then echo 'pg_restore (PostgreSQL) 17.4'; exit 0; fi
if [[ "$1" == --list ]]; then printf '%s\n' '3; 2615 2200 SCHEMA - public postgres' '4; 1259 2201 TABLE public users postgres' '5; 2615 2202 SCHEMA - valorant postgres' '6; 1259 2203 TABLE valorant matches postgres'; exit 0; fi
exit 0
EOF
  chmod 700 "$tmp/bin/pg_restore"
  cat > "$tmp/bin/docker" <<'EOF'
#!/usr/bin/env bash
if [[ "$*" == *'container exec'* ]]; then printf '%s|quest_restore|quest_recovery_admin|active|5432|12345\n' "${PGAPPNAME:?}" >> "${TARGET_BINDING_MARKER:?}"; printf '%s|quest_restore|quest_recovery_admin|active|5432|12345\n' "${PGAPPNAME:?}"; exit 0; fi
if [[ "$*" == *NetworkSettings.Ports* ]]; then printf '%s\n' '{"5432/tcp":[{"HostIp":"127.0.0.1","HostPort":"55432"}]}'; else printf '%s\n' 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|/quest-rehearsal-fixture|true|postgres:17-bookworm@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|0'; fi
EOF
  cat > "$tmp/bin/rsync" <<'EOF'
#!/usr/bin/env bash
rm -rf -- "$4"; mkdir -p -- "$4"; cp -a -- "$3/." "$4/"
EOF
  cat > "$tmp/bin/curl" <<'EOF'
#!/usr/bin/env bash
output=''; headers=''; method='GET'; url=''; args=("$@"); for ((i=0; i<${#args[@]}; i++)); do case "${args[$i]}" in -o) i=$((i+1)); output="${args[$i]}";; -D) i=$((i+1)); headers="${args[$i]}";; -X) i=$((i+1)); method="${args[$i]}";; http*) url="${args[$i]}";; esac; done
if [[ "$method" == POST ]]; then printf 'HTTP/1.1 503 Service Unavailable\nX-Write-Freeze: validation\n' > "$headers"; printf '{}' > "$output"; printf 503; elif [[ "$url" == *freeze.test/status* ]]; then printf '{"mode":"validation","writersEnabled":false}' > "$output"; printf 200; else printf '{"status":"ok","db":"up"}' > "$output"; printf 200; fi
EOF
  cat > "$tmp/bin/time" <<'EOF'
#!/usr/bin/env bash
[[ "$1" == -f && "$3" == -o ]] || exit 2
output="$4"; shift 4; "$@"; status=$?; printf 'cpu_seconds=0.1\npeak_memory_kb=1024\n' > "$output"; exit "$status"
EOF
  for command in age psql docker rsync curl time; do chmod 700 "$tmp/bin/$command"; done
  cat > "$tmp/security-hook" <<'EOF'
#!/usr/bin/env bash
printf 'security-verified\n'
EOF
  cat > "$tmp/no-admission-hook" <<'EOF'
#!/usr/bin/env bash
printf 'verified\n'
EOF
  for kind in bad_checksum bad_decryption wrong_ca blocked_network failed_service_health attempted_mutation_callback; do case "$kind" in bad_checksum) service=quest-backup; class=archive_checksum_failed; endpoint=archive-checksum; pre=running; post=running;; bad_decryption) service=quest-backup; class=age_decryption_failed; endpoint=archive-decryption; pre=running; post=running;; wrong_ca) service=valorant-health; class=certificate_verification_failed; endpoint=valorant-health; pre=running; post=running;; blocked_network) service=valorant-health; class=network_blocked; endpoint=valorant-health; pre=running; post=blocked;; failed_service_health) service=valorant-health; class=service_health_failed; endpoint=valorant-health; pre=running; post=stopped;; attempted_mutation_callback) service=quest-api; class=writer_mutation_rejected; endpoint=quest-api; pre=running; post=blocked;; esac; printf '%s\n' '#!/usr/bin/env bash' "printf '%s\\n' 'result=passed' 'failure_class=$class' 'service_identity=$service' 'endpoint_id=$endpoint' \"endpoint_sha256=\${FAILURE_ENDPOINT_SHA256}\" 'pre_state=$pre' 'post_state=$post' 'containment=verified' 'unaffected_service=verified'" > "$tmp/$kind-hook"; chmod 700 "$tmp/$kind-hook"; done
  : > "$tmp/target-binding.log"
  if ! env PATH="$tmp/bin:$PATH" REHEARSAL_TIME_COMMAND="$tmp/bin/time" FIXTURE_PAYLOAD_DIR="$tmp/wrapper-payload" TARGET_BINDING_MARKER="$tmp/target-binding.log" SECURITY_VERIFY_COMMAND="$tmp/security-hook" NO_WRITER_ADMISSION_COMMAND="$tmp/no-admission-hook" QUEST_LIVENESS_URL=https://quest-live.test/health QUEST_READINESS_URL=https://quest-ready.test/health VALORANT_HEALTH_URL=https://valorant-health.test/health VALORANT_CA_FILE="$tmp/ca/ca.crt" FREEZE_STATUS_URL=https://freeze.test/status FREEZE_MUTATION_URL=https://freeze.test/mutation FREEZE_CALLBACK_URL=https://freeze.test/callback FAILURE_INJECTION_BAD_CHECKSUM_COMMAND="$tmp/bad_checksum-hook" FAILURE_INJECTION_BAD_DECRYPTION_COMMAND="$tmp/bad_decryption-hook" FAILURE_INJECTION_WRONG_CA_COMMAND="$tmp/wrong_ca-hook" FAILURE_INJECTION_BLOCKED_NETWORK_COMMAND="$tmp/blocked_network-hook" FAILURE_INJECTION_FAILED_SERVICE_HEALTH_COMMAND="$tmp/failed_service_health-hook" FAILURE_INJECTION_ATTEMPTED_MUTATION_CALLBACK_COMMAND="$tmp/attempted_mutation_callback-hook" REHEARSAL_CONFIRMATION=DISPOSABLE_QUEST_REHEARSAL REHEARSAL_EVIDENCE_DIR="$tmp/evidence" BACKUP_ENV_FILE="$tmp/recovery.env" SOURCE_VERSION_EVIDENCE_FILE="$tmp/source-version.env" REHEARSAL_TARGET_SENTINEL_FILE="$tmp/target-sentinel.env" REHEARSAL_SIGNING_PRIVATE_KEY="$tmp/wrapper-signing-private.pem" REHEARSAL_RPO_SECONDS=86400 REHEARSAL_RPO_DECISION=met REHEARSAL_RTO_SECONDS=60 REHEARSAL_RTO_DECISION=met POSTGRES17_BIN="$tmp/bin" bash "$rehearsal" "$tmp/quest-production-20260827T000000Z.tar.gz.enc" >"$tmp/wrapper.log" 2>&1; then echo 'FAIL: wrapper-path target-binding fixture failed' >&2; cat "$tmp/wrapper.log" >&2; exit 1; fi
  env REHEARSAL_TRUSTED_SIGNING_PUBLIC_KEY="$tmp/wrapper-signing-public.pem" bash "$verify" "$tmp/quest-production-20260827T000000Z.tar.gz.enc" "$tmp/evidence" >/dev/null || { echo 'FAIL: wrapper-generated evidence did not pass its verifier' >&2; exit 1; }
  [[ "$(grep -Ec 'quest-rehearsal-[0-9a-f]{64}\|quest_restore\|quest_recovery_admin\|quest_recovery_admin\|5432\|12345' "$tmp/target-binding.log")" -ge 2 ]] || { echo 'FAIL: wrapper-path fixture did not establish both direct bindings' >&2; cat "$tmp/target-binding.log" >&2; exit 1; }
  [[ "$(grep -Ec 'quest-rehearsal-[0-9a-f]{64}\|quest_restore\|quest_recovery_admin\|active\|5432\|12345' "$tmp/target-binding.log")" -ge 2 ]] || { echo 'FAIL: wrapper-path fixture did not establish both independent bindings' >&2; cat "$tmp/target-binding.log" >&2; exit 1; }
  echo 'ok: successful wrapper-path pre/post evidence generation'
  [[ ! -e "$tmp/wrapper-parent" && ! -e "$tmp/wrapper-parent/public" && ! -e "$tmp/wrapper-parent/private" ]] || { echo 'FAIL: successful rehearsal did not remove disposable wrapper parent and roots' >&2; exit 1; }
fi
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"; sha() { for _ in {1..64}; do printf '%s' "$1"; done; }; nonce_value=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; nonce_after_value=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
printf '%s\n' "format_version=1" "evidence_status=complete" "rehearsal_mode=disposable" "restore_status=verified" "created_at_utc=$now" "restore_start_utc=$now" "restore_end_utc=$now" "restore_duration_seconds=12" "archive_name=quest-production-fixture.tar.gz.enc" "archive_sha256=$(sha a)" "checksum_status=verified" "decryption_status=verified" "manifest_database_scope=application_public_and_valorant_schemas" "manifest_valorant_schema_included=true" "source_postgres_major=17" "source_major_gate=none" "client_psql_major=17" "client_pg_restore_major=17" "client_pg_dump_major=17" "public_table_count=2" "valorant_table_count=2" "public_object_count=3" "valorant_object_count=3" "quest_migration_ledger_status=verified" "quest_migration_count=4" "valorant_migration_ledger_status=verified" "valorant_migration_count=4" "roles_status=verified" "owners_status=verified" "grants_status=verified" "default_acl_status=verified" "extensions_status=verified" "extensions_count=1" "settings_status=verified" "rls_status=verified" "rls_enabled_table_count=2" "rls_table_count=2" "public_upload_file_count=1" "public_upload_byte_count=10" "public_upload_checksum=$(sha b)" "private_upload_file_count=1" "private_upload_byte_count=10" "private_upload_checksum=$(sha c)" "quest_liveness_status=ok" "quest_readiness_status=ok" "quest_database_status=up" "valorant_health_status=ok" "valorant_database_status=up" "valorant_ca_status=verified" "freeze_mode=validation" "writers_disabled=true" "mutation_rejection=verified" "no_writer_admission=verified" "failure_injection_bad_checksum=passed" "failure_injection_bad_decryption=passed" "failure_injection_wrong_ca=passed" "failure_injection_blocked_network=passed" "failure_injection_failed_service_health=passed" "failure_injection_attempted_mutation_callback=passed" "resource_cpu_seconds=1.2" "resource_peak_memory_kb=2048" "resource_disk_bytes=4096" "rto_seconds=30" "rto_decision=met" > "$tmp/evidence/rehearsal-evidence.env"; chmod 600 "$tmp/evidence/rehearsal-evidence.env"
sed -i 's#quest-production-fixture.tar.gz.enc#quest-production-20260827T000000Z.tar.gz.enc#' "$tmp/evidence/rehearsal-evidence.env"; sed -i 's#restore_duration_seconds=12#restore_duration_seconds=0#' "$tmp/evidence/rehearsal-evidence.env"; printf '%s\n' 'target_postgres_major=17' >> "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'target_server_version_num=170004' 'target_ssl_status=on' 'public_policy_count=1' 'valorant_policy_count=1' 'runtime_policy_status=verified' 'roles_nobypassrls_status=verified' 'quest_read_write_probe_status=verified' 'quest_write_probe_status=verified' 'cross_schema_denial_status=verified' >> "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'target_kind=disposable_postgresql17' 'target_id=quest-fixture-20260827' 'target_container_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' "target_sentinel_sha256=$(sha256sum "$tmp/target-sentinel.env" | cut -d' ' -f1)" 'target_container_disk_bytes_before=1024' 'target_container_disk_bytes_after=2048' 'target_database_size_bytes=4096' >> "$tmp/evidence/rehearsal-evidence.env"
printf 'plpgsql|1.0\n' > "$tmp/evidence/rehearsal-ext-before.tsv"; printf '%s\n' 'server_version|17.4_Debian_17.4-1.pgdg' 'server_version_num|170004' 'ssl|on' 'ssl_min_protocol_version|TLSv1.2' 'row_security|on' 'default_transaction_read_only|off' 'listen_addresses|*' > "$tmp/evidence/rehearsal-settings-before.tsv"
printf '%s\n' 'target_host=127.0.0.1' 'target_port=55432' 'target_database_name=quest_restore' "target_nonce_sha256=$(printf '%s' "$nonce_value" | sha256sum | cut -d' ' -f1)" "target_nonce_after_sha256=$(printf '%s' "$nonce_after_value" | sha256sum | cut -d' ' -f1)" "bootstrap_sql_sha256=$(sha256sum "$root/ops/docker/postgres/init/001-bootstrap-roles.sql" | cut -d' ' -f1)" 'extensions_before_status=verified' 'extensions_before_count=1' "extensions_before_inventory_sha256=$(sha256sum "$tmp/evidence/rehearsal-ext-before.tsv" | cut -d' ' -f1)" 'settings_before_status=verified' "settings_before_inventory_sha256=$(sha256sum "$tmp/evidence/rehearsal-settings-before.tsv" | cut -d' ' -f1)" 'quest_read_probe_status=verified' 'quest_read_probe_count=2' 'quest_read_probe_session_user=quest_runtime' 'quest_read_probe_current_user=quest_runtime' >> "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'target_server_version_num=170004' 'target_ssl_status=on' 'public_policy_count=1' 'valorant_policy_count=1' 'runtime_policy_status=verified' 'roles_nobypassrls_status=verified' 'quest_read_write_probe_status=verified' 'quest_write_probe_status=verified' 'cross_schema_denial_status=verified' >> "$tmp/evidence/rehearsal-observations.env"
printf '%s\n' "source_version_provenance=operator_recorded" "source_version_record_sha256=$(sha256sum "$tmp/source-version.env" | cut -d' ' -f1)" "observations_sha256=PLACEHOLDER" "memberships_status=verified" "security_verify_status=verified" "security_verify_output_sha256=$(printf security-verified | sha256sum | cut -d' ' -f1)" "extensions_inventory_sha256=PLACEHOLDER" "settings_inventory_sha256=PLACEHOLDER" "roles_observations_sha256=PLACEHOLDER" "memberships_observations_sha256=PLACEHOLDER" "owners_observations_sha256=PLACEHOLDER" "grants_observations_sha256=PLACEHOLDER" "default_acl_observations_sha256=PLACEHOLDER" "rls_observations_sha256=PLACEHOLDER" "upload_checksum_scope=post_restore_tree" "upload_source_equivalence=not_claimed_without_source_inventory" >> "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'quest_migrator|t|f|f|f|f|f|f' 'quest_runtime|t|f|f|f|f|f|f' 'val_migrator|t|f|f|f|f|f|f' 'val_runtime|t|f|f|f|f|f|f' > "$tmp/evidence/rehearsal-roles.tsv"
printf 'public\tusers\tt\tusers_runtime_all\tquest_runtime\tALL\ttrue\ttrue\nvalorant\tmatches\tt\tmatches_runtime_all\tval_runtime\tALL\ttrue\ttrue\nvalorant\t_migration_ledger\tf\t<none>\t<none>\t<none>\t<none>\t<none>\n' > "$tmp/evidence/rehearsal-rls.tsv"
printf '%s\n' 'schema|public|quest_migrator|USAGE|t' 'schema|public|quest_migrator|CREATE|t' 'schema|public|quest_runtime|USAGE|t' 'schema|valorant|val_migrator|USAGE|t' 'schema|valorant|val_migrator|CREATE|t' 'schema|valorant|val_runtime|USAGE|t' 'schema|valorant|quest_runtime|USAGE_DENIED|t' 'schema|public|val_runtime|USAGE_DENIED|t' 'table|public|quest_runtime|all|t' 'table|valorant|val_runtime|all|t' 'sequence|public|quest_runtime|usage_select|t' 'sequence|valorant|val_runtime|usage_select|t' > "$tmp/evidence/rehearsal-grants.tsv"
printf '%s\n' 'quest_migrator|public|r|fixture' 'quest_migrator|public|S|fixture' 'quest_migrator|public|f|fixture' 'quest_migrator|public|T|fixture' 'val_migrator|valorant|r|fixture' 'val_migrator|valorant|S|fixture' 'val_migrator|valorant|f|fixture' 'val_migrator|valorant|T|fixture' > "$tmp/evidence/rehearsal-acl.tsv"
cp "$tmp/source-version.env" "$tmp/evidence/rehearsal-source-version.env"
printf '0\n' > "$tmp/evidence/rehearsal-memberships.tsv"; printf '%s\n' 'public|quest_migrator' 'valorant|val_migrator' > "$tmp/evidence/rehearsal-owners.tsv"; printf 'verified\n' > "$tmp/evidence/rehearsal-grants.tsv"; printf 'verified\n' > "$tmp/evidence/rehearsal-acl.tsv"; printf 'plpgsql|1.0\n' > "$tmp/evidence/rehearsal-ext.tsv"; printf '%s\n' 'server_version|17.4_Debian_17.4-1.pgdg' 'server_version_num|170004' 'ssl|on' 'ssl_min_protocol_version|TLSv1.2' 'row_security|on' 'default_transaction_read_only|off' 'listen_addresses|*' > "$tmp/evidence/rehearsal-settings.tsv"; printf '2|2\n' > "$tmp/evidence/rehearsal-rls.tsv"
printf '0\n' > "$tmp/evidence/rehearsal-memberships.tsv"; printf '%s\n' 'schema|public|quest_migrator|USAGE|t' 'schema|public|quest_migrator|CREATE|t' 'schema|public|quest_runtime|USAGE|t' 'schema|valorant|val_migrator|USAGE|t' 'schema|valorant|val_migrator|CREATE|t' 'schema|valorant|val_runtime|USAGE|t' 'schema|valorant|quest_runtime|USAGE_DENIED|t' 'schema|public|val_runtime|USAGE_DENIED|t' 'table|public|quest_runtime|all|t' 'table|valorant|val_runtime|all|t' 'sequence|public|quest_runtime|usage_select|t' 'sequence|valorant|val_runtime|usage_select|t' > "$tmp/evidence/rehearsal-grants.tsv"; printf '%s\n' 'quest_migrator|public|r|quest_runtime=arwd/quest_migrator' 'quest_migrator|public|S|quest_runtime=rwU/quest_migrator' 'quest_migrator|public|f|quest_migrator=X/quest_migrator' 'quest_migrator|public|T|quest_migrator=U/quest_migrator' 'val_migrator|valorant|r|val_runtime=arwd/val_migrator' 'val_migrator|valorant|S|val_runtime=rwU/val_migrator' 'val_migrator|valorant|f|val_migrator=X/val_migrator' 'val_migrator|valorant|T|val_migrator=U/val_migrator' 'quest_migrator|<global>|f|quest_migrator=X/quest_migrator' 'quest_migrator|<global>|T|quest_migrator=U/quest_migrator' 'val_migrator|<global>|f|val_migrator=X/val_migrator' 'val_migrator|<global>|T|val_migrator=U/val_migrator' > "$tmp/evidence/rehearsal-acl.tsv"; printf 'public\tusers\tt\tusers_runtime_all\tquest_runtime\tALL\ttrue\ttrue\nvalorant\tmatches\tt\tmatches_runtime_all\tval_runtime\tALL\ttrue\ttrue\nvalorant\t_migration_ledger\tf\t<none>\t<none>\t<none>\t<none>\t<none>\t<none>\n' > "$tmp/evidence/rehearsal-rls.tsv"
printf '%s\n' 'quest_migrator|public|S|quest_runtime=rwU/quest_migrator' 'quest_migrator|public|T|quest_migrator=U/quest_migrator' 'quest_migrator|public|f|quest_migrator=X/quest_migrator' 'quest_migrator|public|r|quest_runtime=arwd/quest_migrator' 'val_migrator|valorant|S|val_runtime=rwU/val_migrator' 'val_migrator|valorant|T|val_migrator=U/val_migrator' 'val_migrator|valorant|f|val_migrator=X/val_migrator' 'val_migrator|valorant|r|val_runtime=arwd/val_migrator' 'quest_migrator|<global>|T|quest_migrator=U/quest_migrator' 'quest_migrator|<global>|f|quest_migrator=X/quest_migrator' 'val_migrator|<global>|T|val_migrator=U/val_migrator' 'val_migrator|<global>|f|val_migrator=X/val_migrator' > "$tmp/evidence/rehearsal-acl.tsv"
for artifact in roles memberships owners grants acl ext settings rls; do field="${artifact}_observations_sha256"; [[ "$artifact" == acl ]] && field=default_acl_observations_sha256; hash="$(sha256sum "$tmp/evidence/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; sed -i "s/^${field}=PLACEHOLDER$/${field}=$hash/" "$tmp/evidence/rehearsal-evidence.env"; done
ext_hash="$(sha256sum "$tmp/evidence/rehearsal-ext.tsv" | cut -d' ' -f1)"; settings_hash="$(sha256sum "$tmp/evidence/rehearsal-settings.tsv" | cut -d' ' -f1)"; sed -i "s/extensions_inventory_sha256=PLACEHOLDER/extensions_inventory_sha256=$ext_hash/; s/settings_inventory_sha256=PLACEHOLDER/settings_inventory_sha256=$settings_hash/" "$tmp/evidence/rehearsal-evidence.env"
{ printf '%s\n' 'format_version=1' 'observation_status=complete' 'restore_command_status=verified' 'checksum_command_status=verified' 'decryption_command_status=verified' 'source_version_provenance=operator_recorded'; grep -E '^(source_version_record_sha256|source_postgres_major|target_postgres_major|client_psql_major|client_pg_restore_major|client_pg_dump_major|public_table_count|valorant_table_count|public_object_count|valorant_object_count|quest_migration_ledger_status|quest_migration_count|valorant_migration_ledger_status|valorant_migration_count|public_upload_file_count|public_upload_byte_count|public_upload_checksum|private_upload_file_count|private_upload_byte_count|private_upload_checksum|quest_liveness_status|quest_readiness_status|quest_database_status|valorant_health_status|valorant_database_status|valorant_ca_status|freeze_mode|writers_disabled|mutation_rejection|no_writer_admission|failure_injection_[a-z_]+|resource_cpu_seconds|resource_peak_memory_kb|resource_disk_bytes|rto_seconds|rto_decision|upload_checksum_scope|upload_source_equivalence|extensions_inventory_sha256|settings_inventory_sha256|security_verify_status|security_verify_output_sha256)=' "$tmp/evidence/rehearsal-evidence.env"; printf '%s\n' 'manifest_scope=application_public_and_valorant_schemas' 'manifest_valorant_schema_included=true' 'roles_command_status=verified' 'memberships_command_status=verified' 'owners_command_status=verified' 'grants_command_status=verified' 'default_acl_command_status=verified' 'rls_command_status=verified'; for artifact in roles memberships owners grants acl rls; do field="${artifact}_observations_sha256"; [[ "$artifact" == acl ]] && field=default_acl_observations_sha256; grep "^${field}=" "$tmp/evidence/rehearsal-evidence.env"; done; } > "$tmp/evidence/rehearsal-observations.env"
chmod 600 "$tmp/evidence"/rehearsal-*.tsv; printf 'security-verified' > "$tmp/evidence/rehearsal-security-verifier.output"; chmod 600 "$tmp/evidence/rehearsal-security-verifier.output"; obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; archive_hash="$(sha256sum "$tmp/quest-production-20260827T000000Z.tar.gz.enc" | cut -d' ' -f1)"; sed -i "s/observations_sha256=PLACEHOLDER/observations_sha256=$obs_hash/; s/^archive_sha256=.*/archive_sha256=$archive_hash/" "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'quest_migration_ledger_before_status=absent' 'valorant_migration_ledger_before_status=absent' 'rpo_seconds=86400' 'rpo_decision=met' >> "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'quest_migration_ledger_before_status=absent' 'valorant_migration_ledger_before_status=absent' 'rpo_seconds=86400' 'rpo_decision=met' >> "$tmp/evidence/rehearsal-observations.env"
printf '%s\n' 'target_kind=disposable_postgresql17' 'target_id=quest-fixture-20260827' 'target_container_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' "target_sentinel_sha256=$(sha256sum "$tmp/target-sentinel.env" | cut -d' ' -f1)" 'target_container_disk_bytes_before=1024' 'target_container_disk_bytes_after=2048' 'target_database_size_bytes=4096' >> "$tmp/evidence/rehearsal-observations.env"
printf '%s\n' 'target_host=127.0.0.1' 'target_port=55432' 'target_database_name=quest_restore' "target_nonce_sha256=$(printf '%s' "$nonce_value" | sha256sum | cut -d' ' -f1)" "target_nonce_after_sha256=$(printf '%s' "$nonce_after_value" | sha256sum | cut -d' ' -f1)" "bootstrap_sql_sha256=$(sha256sum "$root/ops/docker/postgres/init/001-bootstrap-roles.sql" | cut -d' ' -f1)" 'extensions_before_status=verified' 'extensions_before_count=1' "extensions_before_inventory_sha256=$(sha256sum "$tmp/evidence/rehearsal-ext-before.tsv" | cut -d' ' -f1)" 'settings_before_status=verified' "settings_before_inventory_sha256=$(sha256sum "$tmp/evidence/rehearsal-settings-before.tsv" | cut -d' ' -f1)" 'quest_read_probe_status=verified' 'quest_read_probe_count=2' 'quest_read_probe_session_user=quest_runtime' 'quest_read_probe_current_user=quest_runtime' >> "$tmp/evidence/rehearsal-observations.env"
printf '%s\n' 'target_server_version_num=170004' 'target_ssl_status=on' 'public_policy_count=1' 'valorant_policy_count=1' 'runtime_policy_status=verified' 'roles_nobypassrls_status=verified' 'quest_read_write_probe_status=verified' 'quest_write_probe_status=verified' 'cross_schema_denial_status=verified' >> "$tmp/evidence/rehearsal-observations.env"
obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s/^observations_sha256=.*/observations_sha256=$obs_hash/" "$tmp/evidence/rehearsal-evidence.env"
cp "$tmp/target-sentinel.env" "$tmp/evidence/rehearsal-target-sentinel.env"; chmod 600 "$tmp/evidence/rehearsal-target-sentinel.env"; printf 'status|absent\n' > "$tmp/evidence/rehearsal-quest-migrations-before.tsv"; printf 'status|absent\n' > "$tmp/evidence/rehearsal-valorant-migrations-before.tsv"; printf '%s\n' '20260827_init|complete' '20260827_users|complete' '20260827_events|complete' '20260827_indexes|complete' > "$tmp/evidence/rehearsal-quest-migrations.tsv"; printf '%s\n' '20260827_init|complete' '20260827_users|complete' '20260827_events|complete' '20260827_indexes|complete' > "$tmp/evidence/rehearsal-valorant-migrations.tsv"
printf '%s\n' 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|/quest-rehearsal-fixture|true|postgres:17-bookworm@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|0' > "$tmp/evidence/rehearsal-target-docker-before.txt"; printf '%s\n' '{"5432/tcp":[{"HostIp":"127.0.0.1","HostPort":"55432"}]}' > "$tmp/evidence/rehearsal-target-port-mapping.txt"; cp "$tmp/evidence/rehearsal-target-port-mapping.txt" "$tmp/evidence/rehearsal-target-port-mapping-after.txt"; printf '%s\n' "quest-rehearsal-$nonce_value|quest_restore|restore|restore|5432|12345" > "$tmp/evidence/rehearsal-connection-binding.txt"; printf '%s\n' "quest-rehearsal-$nonce_value|quest_restore|restore|active|5432|12345" > "$tmp/evidence/rehearsal-docker-connection-binding.txt"; cp "$tmp/evidence/rehearsal-target-docker-before.txt" "$tmp/evidence/rehearsal-target-docker-after.txt"; printf '%s\n' "quest-rehearsal-$nonce_after_value|quest_restore|restore|5432|12346" > "$tmp/evidence/rehearsal-connection-binding-after.txt"; printf '%s\n' "quest-rehearsal-$nonce_after_value|quest_restore|restore|active|5432|12346" > "$tmp/evidence/rehearsal-docker-connection-binding-after.txt"; printf '%s\n' "quest_runtime|quest_runtime|2|quest-runtime-probe-$nonce_after_value|12345|on" > "$tmp/evidence/rehearsal-quest-read-probe.tsv"
for target_artifact in target-docker-before target-port-mapping target-port-mapping-after connection-binding docker-connection-binding target-docker-after connection-binding-after docker-connection-binding-after; do field="${target_artifact//-/_}_sha256"; case "$target_artifact" in target-port-mapping) field=target_mapping_sha256 ;; target-port-mapping-after) field=target_mapping_after_sha256 ;; connection-binding) field=target_connection_before_sha256 ;; docker-connection-binding) field=target_docker_connection_before_sha256 ;; connection-binding-after) field=target_connection_after_sha256 ;; docker-connection-binding-after) field=target_docker_connection_after_sha256 ;; esac; hash="$(sha256sum "$tmp/evidence/rehearsal-${target_artifact}.txt" | cut -d' ' -f1)"; printf '%s=%s\n' "$field" "$hash" >> "$tmp/evidence/rehearsal-observations.env"; printf '%s=%s\n' "$field" "$hash" >> "$tmp/evidence/rehearsal-evidence.env"; done
obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s/^observations_sha256=.*/observations_sha256=$obs_hash/" "$tmp/evidence/rehearsal-evidence.env"
for hook in bad-checksum-hook bad-decryption-hook wrong-ca-hook blocked-network-hook failed-service-health-hook mutation-callback-hook; do printf '#!/usr/bin/env bash\nexit 0\n' > "$tmp/$hook"; chmod 700 "$tmp/$hook"; done; cp "$tmp/bad-checksum-hook" "$tmp/evidence/rehearsal-failure-hook-bad_checksum.sh"; cp "$tmp/bad-decryption-hook" "$tmp/evidence/rehearsal-failure-hook-bad_decryption.sh"; cp "$tmp/wrong-ca-hook" "$tmp/evidence/rehearsal-failure-hook-wrong_ca.sh"; cp "$tmp/blocked-network-hook" "$tmp/evidence/rehearsal-failure-hook-blocked_network.sh"; cp "$tmp/failed-service-health-hook" "$tmp/evidence/rehearsal-failure-hook-failed_service_health.sh"; cp "$tmp/mutation-callback-hook" "$tmp/evidence/rehearsal-failure-hook-attempted_mutation_callback.sh"; chmod 700 "$tmp/evidence"/rehearsal-failure-hook-*.sh
printf '%s\n' 'result=passed' 'failure_class=archive_checksum_failed' 'service_identity=quest-backup' 'endpoint_id=archive-checksum' 'endpoint_sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' 'pre_state=running' 'post_state=running' 'containment=verified' > "$tmp/evidence/rehearsal-failure-bad_checksum.output"; printf '%s\n' 'result=passed' 'failure_class=age_decryption_failed' 'service_identity=quest-backup' 'endpoint_id=archive-decryption' 'endpoint_sha256=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' 'pre_state=running' 'post_state=running' 'containment=verified' > "$tmp/evidence/rehearsal-failure-bad_decryption.output"; printf '%s\n' 'result=passed' 'failure_class=certificate_verification_failed' 'service_identity=valorant-health' 'endpoint_id=valorant-health' 'endpoint_sha256=cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc' 'pre_state=running' 'post_state=running' 'containment=verified' > "$tmp/evidence/rehearsal-failure-wrong_ca.output"; printf '%s\n' 'result=passed' 'failure_class=network_blocked' 'service_identity=valorant-health' 'endpoint_id=valorant-health' 'endpoint_sha256=dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd' 'pre_state=running' 'post_state=blocked' 'containment=verified' > "$tmp/evidence/rehearsal-failure-blocked_network.output"; printf '%s\n' 'result=passed' 'failure_class=service_health_failed' 'service_identity=valorant-health' 'endpoint_id=valorant-health' 'endpoint_sha256=eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee' 'pre_state=running' 'post_state=stopped' 'containment=verified' > "$tmp/evidence/rehearsal-failure-failed_service_health.output"; printf '%s\n' 'result=passed' 'failure_class=writer_mutation_rejected' 'service_identity=quest-api' 'endpoint_id=quest-api' 'endpoint_sha256=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff' 'pre_state=running' 'post_state=blocked' 'containment=verified' > "$tmp/evidence/rehearsal-failure-attempted_mutation_callback.output"
printf '%s\n' "bad_checksum|$tmp/bad-checksum-hook|$(sha256sum "$tmp/bad-checksum-hook" | cut -d' ' -f1)|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-bad_checksum.output" | cut -d' ' -f1)" "bad_decryption|$tmp/bad-decryption-hook|$(sha256sum "$tmp/bad-decryption-hook" | cut -d' ' -f1)|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-bad_decryption.output" | cut -d' ' -f1)" "wrong_ca|$tmp/wrong-ca-hook|$(sha256sum "$tmp/wrong-ca-hook" | cut -d' ' -f1)|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-wrong_ca.output" | cut -d' ' -f1)" "blocked_network|$tmp/blocked-network-hook|$(sha256sum "$tmp/blocked-network-hook" | cut -d' ' -f1)|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-blocked_network.output" | cut -d' ' -f1)" "failed_service_health|$tmp/failed-service-health-hook|$(sha256sum "$tmp/failed-service-health-hook" | cut -d' ' -f1)|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-failed_service_health.output" | cut -d' ' -f1)" "attempted_mutation_callback|$tmp/mutation-callback-hook|$(sha256sum "$tmp/mutation-callback-hook" | cut -d' ' -f1)|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-attempted_mutation_callback.output" | cut -d' ' -f1)" > "$tmp/evidence/rehearsal-failure-injections.tsv"
printf '%s\n' "bad_checksum|$tmp/bad-checksum-hook|$(sha256sum "$tmp/bad-checksum-hook" | cut -d' ' -f1)|archive-checksum|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-bad_checksum.output" | cut -d' ' -f1)" "bad_decryption|$tmp/bad-decryption-hook|$(sha256sum "$tmp/bad-decryption-hook" | cut -d' ' -f1)|archive-decryption|bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-bad_decryption.output" | cut -d' ' -f1)" "wrong_ca|$tmp/wrong-ca-hook|$(sha256sum "$tmp/wrong-ca-hook" | cut -d' ' -f1)|valorant-health|cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-wrong_ca.output" | cut -d' ' -f1)" "blocked_network|$tmp/blocked-network-hook|$(sha256sum "$tmp/blocked-network-hook" | cut -d' ' -f1)|valorant-health|dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-blocked_network.output" | cut -d' ' -f1)" "failed_service_health|$tmp/failed-service-health-hook|$(sha256sum "$tmp/failed-service-health-hook" | cut -d' ' -f1)|valorant-health|eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-failed_service_health.output" | cut -d' ' -f1)" "attempted_mutation_callback|$tmp/mutation-callback-hook|$(sha256sum "$tmp/mutation-callback-hook" | cut -d' ' -f1)|quest-api|ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-attempted_mutation_callback.output" | cut -d' ' -f1)" > "$tmp/evidence/rehearsal-failure-injections.tsv"
printf '%s\n' "bad_checksum|$tmp/bad-checksum-hook|$(sha256sum "$tmp/bad-checksum-hook" | cut -d' ' -f1)|$tmp/evidence/rehearsal-failure-hook-bad_checksum.sh|$(sha256sum "$tmp/evidence/rehearsal-failure-hook-bad_checksum.sh" | cut -d' ' -f1)|archive-checksum|aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-bad_checksum.output" | cut -d' ' -f1)" "bad_decryption|$tmp/bad-decryption-hook|$(sha256sum "$tmp/bad-decryption-hook" | cut -d' ' -f1)|$tmp/evidence/rehearsal-failure-hook-bad_decryption.sh|$(sha256sum "$tmp/evidence/rehearsal-failure-hook-bad_decryption.sh" | cut -d' ' -f1)|archive-decryption|bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-bad_decryption.output" | cut -d' ' -f1)" "wrong_ca|$tmp/wrong-ca-hook|$(sha256sum "$tmp/wrong-ca-hook" | cut -d' ' -f1)|$tmp/evidence/rehearsal-failure-hook-wrong_ca.sh|$(sha256sum "$tmp/evidence/rehearsal-failure-hook-wrong_ca.sh" | cut -d' ' -f1)|valorant-health|cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-wrong_ca.output" | cut -d' ' -f1)" "blocked_network|$tmp/blocked-network-hook|$(sha256sum "$tmp/blocked-network-hook" | cut -d' ' -f1)|$tmp/evidence/rehearsal-failure-hook-blocked_network.sh|$(sha256sum "$tmp/evidence/rehearsal-failure-hook-blocked_network.sh" | cut -d' ' -f1)|valorant-health|dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-blocked_network.output" | cut -d' ' -f1)" "failed_service_health|$tmp/failed-service-health-hook|$(sha256sum "$tmp/failed-service-health-hook" | cut -d' ' -f1)|$tmp/evidence/rehearsal-failure-hook-failed_service_health.sh|$(sha256sum "$tmp/evidence/rehearsal-failure-hook-failed_service_health.sh" | cut -d' ' -f1)|valorant-health|eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-failed_service_health.output" | cut -d' ' -f1)" "attempted_mutation_callback|$tmp/mutation-callback-hook|$(sha256sum "$tmp/mutation-callback-hook" | cut -d' ' -f1)|$tmp/evidence/rehearsal-failure-hook-attempted_mutation_callback.sh|$(sha256sum "$tmp/evidence/rehearsal-failure-hook-attempted_mutation_callback.sh" | cut -d' ' -f1)|quest-api|ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff|passed|$(sha256sum "$tmp/evidence/rehearsal-failure-attempted_mutation_callback.output" | cut -d' ' -f1)" > "$tmp/evidence/rehearsal-failure-injections.tsv"
for failure_output in "$tmp/evidence"/rehearsal-failure-*.output; do sed -i '/^unaffected_service=/d' "$failure_output"; printf '%s\n' 'unaffected_service=verified' >> "$failure_output"; done
for injection in bad_checksum bad_decryption wrong_ca blocked_network failed_service_health attempted_mutation_callback; do output_hash="$(sha256sum "$tmp/evidence/rehearsal-failure-${injection}.output" | cut -d' ' -f1)"; awk -F'|' -v id="$injection" -v hash="$output_hash" 'BEGIN { OFS=FS } $1 == id { $9=hash } { print }' "$tmp/evidence/rehearsal-failure-injections.tsv" > "$tmp/evidence/rehearsal-failure-injections.tsv.new"; mv "$tmp/evidence/rehearsal-failure-injections.tsv.new" "$tmp/evidence/rehearsal-failure-injections.tsv"; done
printf '%s\n' 'public|2|3' 'valorant|2|3' > "$tmp/evidence/rehearsal-schema-counts.tsv"; printf '%s\n' 'public|1' 'valorant|1' > "$tmp/evidence/rehearsal-policy-counts.tsv"; printf '%s\n' "quest-rehearsal-$nonce_value|12345|on" > "$tmp/evidence/rehearsal-target-session-tls.tsv"; printf '%s\n' 'BEGIN' 'INSERT 0 1' 'quest_runtime|quest_runtime|write_verified' 'ROLLBACK' > "$tmp/evidence/rehearsal-quest-write-probe.tsv"; printf '%s\n' 'sqlstate=42501' 'error_class=permission_denied' 'diagnostic=ERROR: permission denied for schema valorant' > "$tmp/evidence/rehearsal-cross-schema-denial.tsv"; printf '%s\n' 'status=verified' 'public_root_removed=true' 'private_root_removed=true' 'parent_removed=true' > "$tmp/evidence/rehearsal-upload-cleanup.tsv"; chmod 600 "$tmp/evidence"/rehearsal-*.tsv
for pair in 'schema-counts|schema_counts_observations_sha256' 'policy-counts|policy_counts_observations_sha256' 'target-session-tls|target_session_tls_observations_sha256' 'quest-write-probe|quest_write_probe_observations_sha256' 'cross-schema-denial|cross_schema_denial_observations_sha256' 'upload-cleanup|upload_cleanup_observations_sha256'; do artifact="${pair%%|*}"; field="${pair#*|}"; hash="$(sha256sum "$tmp/evidence/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; printf '%s=%s\n' "$field" "$hash" >> "$tmp/evidence/rehearsal-observations.env"; printf '%s=%s\n' "$field" "$hash" >> "$tmp/evidence/rehearsal-evidence.env"; done
printf '%s\n' 'target_ssl_session_status=verified' 'live_disposable_rehearsal_gate=owner_deployment_host_evidence_required' >> "$tmp/evidence/rehearsal-observations.env"; printf '%s\n' 'target_ssl_session_status=verified' 'live_disposable_rehearsal_gate=owner_deployment_host_evidence_required' >> "$tmp/evidence/rehearsal-evidence.env"
obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s/^observations_sha256=.*/observations_sha256=$obs_hash/" "$tmp/evidence/rehearsal-evidence.env"
sed -i 's/^public|1$/public|2/; s/^valorant|1$/valorant|2/' "$tmp/evidence/rehearsal-policy-counts.tsv"; sed -i 's/public_policy_count=1/public_policy_count=2/g; s/valorant_policy_count=1/valorant_policy_count=2/g' "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; policy_hash="$(sha256sum "$tmp/evidence/rehearsal-policy-counts.tsv" | cut -d' ' -f1)"; sed -i "s#^policy_counts_observations_sha256=.*#policy_counts_observations_sha256=$policy_hash#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"
printf 'public\tevents\tt\tevents_runtime_all\tquest_runtime\tALL\ttrue\ttrue\nvalorant\tteams\tt\tteams_runtime_all\tval_runtime\tALL\ttrue\ttrue\n' >> "$tmp/evidence/rehearsal-rls.tsv"; rls_hash="$(sha256sum "$tmp/evidence/rehearsal-rls.tsv" | cut -d' ' -f1)"; sed -i "s#^rls_observations_sha256=.*#rls_observations_sha256=$rls_hash#" "$tmp/evidence/rehearsal-evidence.env"; sed -i "s#^rls_observations_sha256=.*#rls_observations_sha256=$rls_hash#" "$tmp/evidence/rehearsal-observations.env"; obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s/^observations_sha256=.*/observations_sha256=$obs_hash/" "$tmp/evidence/rehearsal-evidence.env"
sed -i 's/quest_restore|restore|5432|12346/quest_restore|restore|restore|5432|12346/' "$tmp/evidence/rehearsal-connection-binding-after.txt"; target_after_hash="$(sha256sum "$tmp/evidence/rehearsal-connection-binding-after.txt" | cut -d' ' -f1)"; sed -i "s#^target_connection_after_sha256=.*#target_connection_after_sha256=$target_after_hash#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; printf '%s\n' "quest_read_probe_application_name=quest-runtime-probe-$nonce_after_value" 'quest_read_probe_backend_pid=12345' 'quest_read_probe_ssl=on' >> "$tmp/evidence/rehearsal-evidence.env"; printf '%s\n' "quest_read_probe_application_name=quest-runtime-probe-$nonce_after_value" 'quest_read_probe_backend_pid=12345' 'quest_read_probe_ssl=on' >> "$tmp/evidence/rehearsal-observations.env"; obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s/^observations_sha256=.*/observations_sha256=$obs_hash/" "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' "quest-rehearsal-$nonce_value|quest_restore|restore|restore|5432|12345" "quest_restore|170004|on|quest-rehearsal-$nonce_value|12345" > "$tmp/evidence/rehearsal-connection-binding.txt"
printf '%s\n' "quest-rehearsal-$nonce_after_value|quest_restore|restore|restore|5432|12346" "quest_restore|170004|on|quest-rehearsal-$nonce_after_value|12346" > "$tmp/evidence/rehearsal-connection-binding-after.txt"
printf '%s\n' 'BEGIN' 'INSERT 0 1' "quest_runtime|quest_runtime|write_verified|quest-write-probe-$nonce_after_value|12346|on" 'ROLLBACK' > "$tmp/evidence/rehearsal-quest-write-probe.tsv"
printf '%s\n' 'session_user=quest_runtime' 'current_user=quest_runtime' "application_name=quest-denial-probe-$nonce_after_value" 'backend_pid=12347' 'ssl=on' 'sqlstate=42501' 'error_class=permission_denied' 'diagnostic=ERROR: 42501: permission denied for schema valorant' > "$tmp/evidence/rehearsal-cross-schema-denial.tsv"
printf '%s\n' 'quest_write_probe_session_user=quest_runtime' 'quest_write_probe_current_user=quest_runtime' "quest_write_probe_application_name=quest-write-probe-$nonce_after_value" 'quest_write_probe_backend_pid=12346' 'quest_write_probe_ssl=on' 'cross_schema_denial_session_user=quest_runtime' 'cross_schema_denial_current_user=quest_runtime' "cross_schema_denial_application_name=quest-denial-probe-$nonce_after_value" 'cross_schema_denial_backend_pid=12347' 'cross_schema_denial_ssl=on' 'upload_cleanup_status=verified' >> "$tmp/evidence/rehearsal-evidence.env"
printf '%s\n' 'quest_write_probe_session_user=quest_runtime' 'quest_write_probe_current_user=quest_runtime' "quest_write_probe_application_name=quest-write-probe-$nonce_after_value" 'quest_write_probe_backend_pid=12346' 'quest_write_probe_ssl=on' 'cross_schema_denial_session_user=quest_runtime' 'cross_schema_denial_current_user=quest_runtime' "cross_schema_denial_application_name=quest-denial-probe-$nonce_after_value" 'cross_schema_denial_backend_pid=12347' 'cross_schema_denial_ssl=on' 'upload_cleanup_status=verified' >> "$tmp/evidence/rehearsal-observations.env"
for pair in 'target-session-tls|target_session_tls_observations_sha256' 'quest-write-probe|quest_write_probe_observations_sha256' 'cross-schema-denial|cross_schema_denial_observations_sha256' 'upload-cleanup|upload_cleanup_observations_sha256'; do artifact="${pair%%|*}"; field="${pair#*|}"; hash="$(sha256sum "$tmp/evidence/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; sed -i "s#^${field}=.*#${field}=${hash}#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; done
for pair in 'connection-binding|target_connection_before_sha256' 'connection-binding-after|target_connection_after_sha256'; do artifact="${pair%%|*}"; field="${pair#*|}"; hash="$(sha256sum "$tmp/evidence/rehearsal-${artifact}.txt" | cut -d' ' -f1)"; sed -i "s#^${field}=.*#${field}=${hash}#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; done
obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s/^observations_sha256=.*/observations_sha256=$obs_hash/" "$tmp/evidence/rehearsal-evidence.env"
verify_fixture() { env REHEARSAL_TRUSTED_SIGNING_PUBLIC_KEY="$tmp/signing-public.pem" bash "$verify" "$tmp/quest-production-20260827T000000Z.tar.gz.enc" "$tmp/evidence"; }
if command -v openssl >/dev/null 2>&1; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$tmp/signing-private.pem" >/dev/null 2>&1; openssl pkey -in "$tmp/signing-private.pem" -pubout -out "$tmp/signing-public.pem" >/dev/null 2>&1; chmod 600 "$tmp/signing-private.pem" "$tmp/signing-public.pem"
  (cd "$tmp/evidence" && for artifact in rehearsal-evidence.env rehearsal-observations.env rehearsal-source-version.env rehearsal-security-verifier.output rehearsal-target-sentinel.env rehearsal-failure-injections.tsv rehearsal-failure-bad_checksum.output rehearsal-failure-bad_decryption.output rehearsal-failure-wrong_ca.output rehearsal-failure-blocked_network.output rehearsal-failure-failed_service_health.output rehearsal-failure-attempted_mutation_callback.output rehearsal-failure-hook-bad_checksum.sh rehearsal-failure-hook-bad_decryption.sh rehearsal-failure-hook-wrong_ca.sh rehearsal-failure-hook-blocked_network.sh rehearsal-failure-hook-failed_service_health.sh rehearsal-failure-hook-attempted_mutation_callback.sh rehearsal-roles.tsv rehearsal-memberships.tsv rehearsal-owners.tsv rehearsal-grants.tsv rehearsal-acl.tsv rehearsal-ext-before.tsv rehearsal-ext.tsv rehearsal-settings-before.tsv rehearsal-settings.tsv rehearsal-rls.tsv rehearsal-schema-counts.tsv rehearsal-policy-counts.tsv rehearsal-target-session-tls.tsv rehearsal-quest-write-probe.tsv rehearsal-cross-schema-denial.tsv rehearsal-upload-cleanup.tsv rehearsal-quest-migrations-before.tsv rehearsal-valorant-migrations-before.tsv rehearsal-quest-migrations.tsv rehearsal-valorant-migrations.tsv rehearsal-target-docker-before.txt rehearsal-target-port-mapping.txt rehearsal-target-port-mapping-after.txt rehearsal-connection-binding.txt rehearsal-docker-connection-binding.txt rehearsal-target-docker-after.txt rehearsal-connection-binding-after.txt rehearsal-docker-connection-binding-after.txt rehearsal-quest-read-probe.tsv; do sha256sum "$artifact"; done) > "$tmp/evidence/rehearsal-evidence.manifest"; chmod 600 "$tmp/evidence/rehearsal-evidence.manifest"; openssl dgst -sha256 -sign "$tmp/signing-private.pem" -out "$tmp/evidence/rehearsal-evidence.sig" "$tmp/evidence/rehearsal-evidence.manifest"; chmod 600 "$tmp/evidence/rehearsal-evidence.sig"
  verify_fixture >/dev/null; echo "ok: valid signed evidence"
  resign_fixture() { (cd "$tmp/evidence" && for artifact in rehearsal-evidence.env rehearsal-observations.env rehearsal-source-version.env rehearsal-security-verifier.output rehearsal-target-sentinel.env rehearsal-failure-injections.tsv rehearsal-failure-bad_checksum.output rehearsal-failure-bad_decryption.output rehearsal-failure-wrong_ca.output rehearsal-failure-blocked_network.output rehearsal-failure-failed_service_health.output rehearsal-failure-attempted_mutation_callback.output rehearsal-failure-hook-bad_checksum.sh rehearsal-failure-hook-bad_decryption.sh rehearsal-failure-hook-wrong_ca.sh rehearsal-failure-hook-blocked_network.sh rehearsal-failure-hook-failed_service_health.sh rehearsal-failure-hook-attempted_mutation_callback.sh rehearsal-roles.tsv rehearsal-memberships.tsv rehearsal-owners.tsv rehearsal-grants.tsv rehearsal-acl.tsv rehearsal-ext-before.tsv rehearsal-ext.tsv rehearsal-settings-before.tsv rehearsal-settings.tsv rehearsal-rls.tsv rehearsal-schema-counts.tsv rehearsal-policy-counts.tsv rehearsal-target-session-tls.tsv rehearsal-quest-write-probe.tsv rehearsal-cross-schema-denial.tsv rehearsal-upload-cleanup.tsv rehearsal-quest-migrations-before.tsv rehearsal-valorant-migrations-before.tsv rehearsal-quest-migrations.tsv rehearsal-valorant-migrations.tsv rehearsal-target-docker-before.txt rehearsal-target-port-mapping.txt rehearsal-target-port-mapping-after.txt rehearsal-connection-binding.txt rehearsal-docker-connection-binding.txt rehearsal-target-docker-after.txt rehearsal-connection-binding-after.txt rehearsal-docker-connection-binding-after.txt rehearsal-quest-read-probe.tsv; do sha256sum "$artifact"; done) > "$tmp/evidence/rehearsal-evidence.manifest"; openssl dgst -sha256 -sign "$tmp/signing-private.pem" -out "$tmp/evidence/rehearsal-evidence.sig" "$tmp/evidence/rehearsal-evidence.manifest" >/dev/null 2>&1; }
  rebind_raw_artifact() { local artifact="$1" field hash obs_hash; case "$artifact" in acl) field=default_acl_observations_sha256 ;; ext) field=extensions_inventory_sha256 ;; settings) field=settings_inventory_sha256 ;; *) echo "FAIL: unknown raw artifact: $artifact" >&2; exit 1 ;; esac; hash="$(sha256sum "$tmp/evidence/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; sed -i "s#^${field}=.*#${field}=${hash}#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s#^observations_sha256=.*#observations_sha256=${obs_hash}#" "$tmp/evidence/rehearsal-evidence.env"; resign_fixture; }
  rebind_summary_field() { local field="$1" value="$2" obs_hash; sed -i "s#^${field}=.*#${field}=${value}#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s#^observations_sha256=.*#observations_sha256=${obs_hash}#" "$tmp/evidence/rehearsal-evidence.env"; resign_fixture; }
  rebind_failure_output() { local injection="$1" output_hash; output_hash="$(sha256sum "$tmp/evidence/rehearsal-failure-${injection}.output" | cut -d' ' -f1)"; awk -F'|' -v id="$injection" -v hash="$output_hash" 'BEGIN { OFS=FS } $1 == id { $9=hash } { print }' "$tmp/evidence/rehearsal-failure-injections.tsv" > "$tmp/evidence/rehearsal-failure-injections.tsv.new"; mv "$tmp/evidence/rehearsal-failure-injections.tsv.new" "$tmp/evidence/rehearsal-failure-injections.tsv"; resign_fixture; }
  cp "$tmp/evidence/rehearsal-acl.tsv" "$tmp/acl.good"; sed -i 's#quest_runtime=arwd/quest_migrator#arbitrary#' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl; evidence_refused "arbitrary ACL payload" "default ACL payload does not match canonical bootstrap contract" verify_fixture; mv "$tmp/acl.good" "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl
  sed -i 's#quest_runtime=arwd/quest_migrator#wrong_grantee=arwd/quest_migrator#' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl; evidence_refused "wrong ACL grantee" "default ACL payload does not match canonical bootstrap contract" verify_fixture; sed -i 's#wrong_grantee=arwd/quest_migrator#quest_runtime=arwd/quest_migrator#' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl
  sed -i 's#quest_runtime=arwd/quest_migrator#quest_runtime=r--/quest_migrator#' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl; evidence_refused "wrong ACL privilege" "default ACL payload does not match canonical bootstrap contract" verify_fixture; sed -i 's#quest_runtime=r--/quest_migrator#quest_runtime=arwd/quest_migrator#' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl
  printf 'quest_migrator|public|r|=r/quest_migrator\n' >> "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl; evidence_refused "PUBLIC default ACL grant" "default ACL payload does not match canonical bootstrap contract" verify_fixture; sed -i '/^quest_migrator|public|r|=r\/quest_migrator$/d' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl
  printf 'quest_migrator|public|r|unexpected=arwd/quest_migrator\n' >> "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl; evidence_refused "extra default ACL row" "default ACL payload does not match canonical bootstrap contract" verify_fixture; sed -i '/^quest_migrator|public|r|unexpected=arwd\/quest_migrator$/d' "$tmp/evidence/rehearsal-acl.tsv"; rebind_raw_artifact acl
  cp "$tmp/evidence/rehearsal-ext.tsv" "$tmp/ext.good"; sed -i 's/plpgsql|1.0/plpgsql|2.0/' "$tmp/evidence/rehearsal-ext.tsv"; rebind_raw_artifact ext; evidence_refused "unsafe extension version" "extension inventory changed between before/after restore" verify_fixture; mv "$tmp/ext.good" "$tmp/evidence/rehearsal-ext.tsv"; rebind_raw_artifact ext
  cp "$tmp/evidence/rehearsal-settings.tsv" "$tmp/settings.good"; sed -i 's/^ssl|on$/ssl|off/' "$tmp/evidence/rehearsal-settings.tsv"; rebind_raw_artifact settings; evidence_refused "unsafe PostgreSQL setting" "PostgreSQL settings changed between before/after restore" verify_fixture; mv "$tmp/settings.good" "$tmp/evidence/rehearsal-settings.tsv"; rebind_raw_artifact settings
  cp "$tmp/evidence/rehearsal-failure-wrong_ca.output" "$tmp/wrong-ca.good"; sed -i 's/^containment=verified$/containment=failed/' "$tmp/evidence/rehearsal-failure-wrong_ca.output"; rebind_failure_output wrong_ca; evidence_refused "uncontained wrong-CA evidence" "failure-injection containment evidence is invalid" verify_fixture; mv "$tmp/wrong-ca.good" "$tmp/evidence/rehearsal-failure-wrong_ca.output"; rebind_failure_output wrong_ca
  cp "$tmp/evidence/rehearsal-failure-failed_service_health.output" "$tmp/service-health.good"; sed -i 's/^service_identity=valorant-health$/service_identity=unknown-service/' "$tmp/evidence/rehearsal-failure-failed_service_health.output"; rebind_failure_output failed_service_health; evidence_refused "unknown failed-service identity" "failure-injection containment evidence is invalid" verify_fixture; mv "$tmp/service-health.good" "$tmp/evidence/rehearsal-failure-failed_service_health.output"; rebind_failure_output failed_service_health
rebind_new_artifact() { local artifact="$1" field hash obs_hash; case "$artifact" in schema-counts) field=schema_counts_observations_sha256 ;; policy-counts) field=policy_counts_observations_sha256 ;; target-session-tls) field=target_session_tls_observations_sha256 ;; quest-write-probe) field=quest_write_probe_observations_sha256 ;; cross-schema-denial) field=cross_schema_denial_observations_sha256 ;; upload-cleanup) field=upload_cleanup_observations_sha256 ;; rls) field=rls_observations_sha256 ;; *) echo "FAIL: unknown new signed artifact: $artifact" >&2; exit 1 ;; esac; hash="$(sha256sum "$tmp/evidence/rehearsal-${artifact}.tsv" | cut -d' ' -f1)"; sed -i "s#^${field}=.*#${field}=${hash}#" "$tmp/evidence/rehearsal-evidence.env" "$tmp/evidence/rehearsal-observations.env"; obs_hash="$(sha256sum "$tmp/evidence/rehearsal-observations.env" | cut -d' ' -f1)"; sed -i "s#^observations_sha256=.*#observations_sha256=${obs_hash}#" "$tmp/evidence/rehearsal-evidence.env"; resign_fixture; }
expect_new_artifact_refusal() { local label="$1" artifact="$2" expression="$3" expected="${4:-new signed artifact binding failed: $2}"; cp "$tmp/evidence/rehearsal-${artifact}.tsv" "$tmp/${artifact}.good"; sed -i "$expression" "$tmp/evidence/rehearsal-${artifact}.tsv"; rebind_new_artifact "$artifact"; evidence_refused "$label" "$expected" verify_fixture; mv "$tmp/${artifact}.good" "$tmp/evidence/rehearsal-${artifact}.tsv"; rebind_new_artifact "$artifact"; }
expect_new_artifact_refusal "unprotected public table" rls 's/public\tusers\tt/public\tusers\tf/' 'Quest RLS policy is incomplete'
expect_new_artifact_refusal "policy-count/artifact mismatch" policy-counts 's/^public|2$/public|3/' 'public policy count is not recomputed from the signed artifact'
expect_new_artifact_refusal "non-permission denial error" cross-schema-denial 's/^error_class=permission_denied$/error_class=timeout/' 'signed cross-schema denial is not bound to its nonce session and TLS'
expect_new_artifact_refusal "quiet-mode write output" quest-write-probe '/^BEGIN$/d; /^ROLLBACK$/d' 'signed write probe artifact is invalid'
expect_new_artifact_refusal "plaintext session" target-session-tls 's/|on$/|off/' 'session-level pg_stat_ssl evidence is invalid or nonce-unbound'
expect_new_artifact_refusal "failed cleanup" upload-cleanup 's/^status=verified$/status=failed/' 'signed disposable upload cleanup evidence is invalid'
cp "$tmp/evidence/rehearsal-evidence.env" "$tmp/summary.good"; sed -i 's/^quest_write_probe_status=verified$/quest_write_probe_status=failed/' "$tmp/evidence/rehearsal-evidence.env"; resign_fixture; evidence_refused "summary/observation status mismatch" "runtime security probe evidence is incomplete" verify_fixture; mv "$tmp/summary.good" "$tmp/evidence/rehearsal-evidence.env"; resign_fixture
else
  evidence_refused "missing signature tool" "openssl is required to verify evidence signatures" bash "$verify" "$tmp/quest-production-20260827T000000Z.tar.gz.enc" "$tmp/evidence"; echo "skipped valid signed evidence: openssl unavailable"
fi
if command -v openssl >/dev/null 2>&1; then mv "$tmp/evidence/rehearsal-observations.env" "$tmp/evidence/rehearsal-observations.env.missing"; evidence_refused "summary without raw observations" "raw command observations are missing" verify_fixture; mv "$tmp/evidence/rehearsal-observations.env.missing" "$tmp/evidence/rehearsal-observations.env"; fi
sed -i 's/manifest_valorant_schema_included=true/manifest_valorant_schema_included=false/' "$tmp/evidence/rehearsal-evidence.env"; resign_fixture; evidence_refused "incomplete manifest evidence" "manifest scope is incomplete" verify_fixture
sed -i 's/manifest_valorant_schema_included=false/manifest_valorant_schema_included=true/' "$tmp/evidence/rehearsal-evidence.env"; resign_fixture; rebind_summary_field valorant_health_status failed; evidence_refused "wrong health evidence" "health status is not ok: valorant_health_status" verify_fixture
rebind_summary_field valorant_health_status ok; rebind_summary_field valorant_ca_status failed; evidence_refused "wrong CA evidence" "status is not verified: valorant_ca_status" verify_fixture
rebind_summary_field valorant_ca_status verified; rebind_summary_field freeze_mode off; evidence_refused "blocked writer/freeze evidence" "freeze evidence is incomplete" verify_fixture
echo "PostgreSQL 17 rehearsal fixture tests passed (no Docker, database, VPS, or remote contacted)."
