export const teamCountries = [
  "Sri Lanka",
  "India",
  "Bangladesh",
  "Pakistan",
  "Nepal",
  "Maldives",
  "Bhutan",
  "Afghanistan",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Japan",
  "South Korea",
  "United Arab Emirates",
  "Saudi Arabia",
  "Australia",
  "United Kingdom",
  "United States",
  "Canada",
  "Other",
] as const;
